/**
 * Données de démonstration : produits africains rares (épicerie).
 *
 * Elles servent :
 *  - de catalogue de secours quand la base de données n'est pas configurée (mode démo) ;
 *  - de source pour générer `db/seed.sql` (npm run db:seed-sql).
 *
 * Producteurs et références sont FICTIFS. Les textes ne contiennent
 * volontairement aucune allégation de santé.
 */
import type { Category, Product, Variant } from "../types";

const id = (prefix: string, n: number) =>
  `${prefix}0000000-0000-4000-a000-${n.toString(16).padStart(12, "0")}`;

export const demoCategories: Category[] = [
  { id: id("1", 1), slug: "epices", name: "Épices & aromates", position: 1, description: "Poivres, graines et mélanges d'épices introuvables en grande surface, sélectionnés à la source." },
  { id: id("1", 2), slug: "cereales", name: "Farines & céréales", position: 2, description: "Fonio, attiéké, couscous de mil : les céréales anciennes et les semoules du continent." },
  { id: id("1", 3), slug: "feuilles", name: "Feuilles & fleurs séchées", position: 3, description: "Feuilles de ndolé, de manioc, fleurs d'hibiscus : séchées sur place pour garder leur goût." },
  { id: id("1", 4), slug: "poissons", name: "Poissons & fumés", position: 4, description: "Poissons séchés, fumés ou fermentés et crevettes séchées, les exhausteurs de goût de la cuisine africaine." },
  { id: id("1", 5), slug: "huiles", name: "Huiles & pâtes", position: 5, description: "Huile de palme rouge, pâte d'arachide, pulpe de noix de palme : la base des grandes sauces." },
];

const cat = (slug: string) => demoCategories.find((c) => c.slug === slug)!.id;

let variantCounter = 0;
function variants(productId: string, list: Array<[label: string, priceCents: number, stock: number]>): Variant[] {
  return list.map(([label, priceCents, stock], position) => {
    variantCounter += 1;
    return {
      id: id("3", variantCounter),
      productId,
      label,
      priceCents,
      stock,
      sku: `AH-${variantCounter.toString().padStart(4, "0")}`,
      position,
    };
  });
}

type ProductSeed = Omit<Product, "variants" | "id" | "createdAt" | "isActive" | "images"> & {
  variants: Array<[string, number, number]>;
};

const seeds: ProductSeed[] = [
  // ----------------------------------------------------- Épices & aromates
  {
    slug: "poivre-de-penja",
    name: "Poivre blanc de Penja",
    categoryId: cat("epices"),
    shortDescription: "Le poivre blanc des terres volcaniques du Cameroun, puissant et parfumé.",
    description:
      "Cultivé au pied du mont Koupé, sur les sols volcaniques de la vallée du Moungo, le poivre de Penja est l'un des rares poivres africains à bénéficier d'une indication géographique protégée. Ses grains, trempés puis séchés au soleil, offrent un piquant franc et des notes boisées et musquées.\n\nÀ moudre au dernier moment.",
    originCountry: "Cameroun",
    originRegion: "Penja, Littoral",
    producer: "Coopérative du Moungo (fictif)",
    composition: "Poivre blanc en grains (Piper nigrum).",
    allergens: [],
    usageTips: "Sur les poissons braisés, le ndolé, les viandes grillées. Moudre en fin de cuisson pour garder tout son parfum.",
    conservation: "À l'abri de la lumière et de l'humidité, dans un bocal fermé.",
    tags: ["IGP", "poivre"],
    featured: true,
    variants: [["50 g", 890, 40], ["100 g", 1590, 25]],
  },
  {
    slug: "soumbala",
    name: "Soumbala (nététou)",
    categoryId: cat("epices"),
    shortDescription: "Graines de néré fermentées, le condiment de caractère du Sahel.",
    description:
      "Le soumbala est obtenu par la fermentation des graines de néré, un arbre de la savane. Façonné en boules puis séché, il apporte aux sauces une profondeur et un goût umami incomparables. Au Sénégal on l'appelle nététou.\n\nUne petite quantité suffit.",
    originCountry: "Burkina Faso",
    originRegion: "Région des Hauts-Bassins",
    producer: "Groupement de femmes de Bobo (fictif)",
    composition: "Graines de néré (Parkia biglobosa) fermentées, sel.",
    allergens: [],
    usageTips: "Écraser une boule dans le mafé, les sauces feuilles ou le riz gras, en début de cuisson.",
    conservation: "Au sec, dans une boîte hermétique (l'odeur est puissante).",
    tags: ["fermenté", "umami"],
    featured: true,
    variants: [["100 g", 690, 30], ["250 g", 1490, 15]],
  },
  {
    slug: "berbere",
    name: "Berbéré d'Éthiopie",
    categoryId: cat("epices"),
    shortDescription: "Le mélange d'épices rouge et chaud de la cuisine éthiopienne.",
    description:
      "Piment, fenugrec, gingembre, korarima, ajowan, clou de girofle : le berbéré est l'âme des wats éthiopiens. Notre mélange est torréfié puis moulu en petites quantités à Addis-Abeba.\n\nPiquant et très aromatique.",
    originCountry: "Éthiopie",
    originRegion: "Addis-Abeba",
    producer: "Maison Selam (fictif)",
    composition: "Piment, paprika, fenugrec, gingembre, ail, korarima, ajowan, clou de girofle, sel.",
    allergens: [],
    usageTips: "Base du doro wat et du misir wat. Faire revenir dans le beurre épicé avant d'ajouter les oignons.",
    conservation: "À l'abri de la lumière, dans un bocal fermé.",
    tags: ["mélange", "piquant"],
    featured: false,
    variants: [["80 g", 790, 30]],
  },
  {
    slug: "yaji-suya",
    name: "Yaji, épices à suya",
    categoryId: cat("epices"),
    shortDescription: "Le mélange arachide-piment des grillades de rue nigérianes.",
    description:
      "Le yaji est le mélange qui enrobe le suya, la brochette grillée vendue au coin des rues de Lagos à Kano. Arachide torréfiée (kuli-kuli), piment, gingembre et épices : un enrobage croustillant et relevé.",
    originCountry: "Nigeria",
    originRegion: "Kano",
    producer: "Mallam Spices (fictif)",
    composition: "Arachide torréfiée, piment, gingembre, ail, oignon, bouillon d'épices, sel.",
    allergens: ["arachide"],
    usageTips: "Frotter la viande avec le yaji avant de la griller, puis en saupoudrer à la sortie du feu.",
    conservation: "Au sec, dans un bocal fermé.",
    tags: ["grillade", "piquant"],
    featured: true,
    variants: [["100 g", 790, 25]],
  },
  {
    slug: "poivre-de-selim",
    name: "Poivre de Selim (djar)",
    categoryId: cat("epices"),
    shortDescription: "Gousses fumées aux notes de résine et de muscade.",
    description:
      "Le poivre de Selim, appelé djar au Sénégal ou kani en Côte d'Ivoire, se présente en longues gousses sombres. Légèrement fumées, elles parfument le café Touba, les bouillons et les marinades de notes résineuses, musquées et poivrées.",
    originCountry: "Sénégal",
    originRegion: "Casamance",
    producer: "Les Cueilleurs de Ziguinchor (fictif)",
    composition: "Gousses de Xylopia aethiopica.",
    allergens: [],
    usageTips: "Écraser les gousses et les infuser dans les bouillons, ou les moudre avec le café.",
    conservation: "Au sec, à l'abri de la lumière.",
    tags: ["cueillette", "fumé"],
    featured: false,
    variants: [["50 g", 690, 30]],
  },
  // ---------------------------------------------------- Farines & céréales
  {
    slug: "fonio",
    name: "Fonio précuit",
    categoryId: cat("cereales"),
    shortDescription: "La plus ancienne céréale d'Afrique de l'Ouest, fine et légère.",
    description:
      "Cultivé depuis des millénaires dans le Sahel, le fonio est une toute petite graine qui cuit en quelques minutes à la vapeur. Son goût léger, entre noisette et semoule, en fait l'accompagnement idéal des sauces.\n\nFonio décortiqué et précuit, prêt en 5 minutes.",
    originCountry: "Mali",
    originRegion: "Région de Kayes",
    producer: "Fonio du Mandé (fictif)",
    composition: "Fonio (Digitaria exilis) décortiqué et précuit.",
    allergens: [],
    usageTips: "Cuire à la vapeur ou verser dans l'eau bouillante salée, couvrir 5 minutes puis égrainer à la fourchette.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["céréale ancienne"],
    featured: true,
    variants: [["500 g", 590, 50], ["1 kg", 990, 30]],
  },
  {
    slug: "attieke-sec",
    name: "Attiéké déshydraté",
    categoryId: cat("cereales"),
    shortDescription: "La semoule de manioc fermenté de Côte d'Ivoire, prête à réhydrater.",
    description:
      "L'attiéké est une semoule de manioc fermenté, légèrement acidulée, qui accompagne le poisson braisé dans tous les maquis ivoiriens. Cette version séchée se conserve longtemps et retrouve sa texture en quelques minutes à la vapeur.",
    originCountry: "Côte d'Ivoire",
    originRegion: "Dabou",
    producer: "Les Femmes de Dabou (fictif)",
    composition: "Manioc fermenté, séché.",
    allergens: [],
    usageTips: "Humidifier, laisser gonfler 5 minutes puis réchauffer à la vapeur. Servir avec oignons, tomates et piment.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["manioc", "fermenté"],
    featured: false,
    variants: [["500 g", 490, 40], ["1 kg", 890, 20]],
  },
  {
    slug: "couscous-de-mil",
    name: "Couscous de mil (thiéré)",
    categoryId: cat("cereales"),
    shortDescription: "Graines de mil roulées à la main, pour le thiakry et le thiéré.",
    description:
      "Au Sénégal, le mil est roulé à la main en petites graines appelées araw ou thiéré, puis séché. Il sert autant aux plats salés qu'au thiakry, le dessert au lait caillé.",
    originCountry: "Sénégal",
    originRegion: "Kaolack",
    producer: "Atelier Sine-Saloum (fictif)",
    composition: "Farine de mil.",
    allergens: [],
    usageTips: "Cuire à la vapeur deux fois en égrainant entre les deux cuissons.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["mil"],
    featured: false,
    variants: [["500 g", 550, 30]],
  },
  // -------------------------------------------- Feuilles & fleurs séchées
  {
    slug: "feuilles-de-ndole",
    name: "Feuilles de ndolé séchées",
    categoryId: cat("feuilles"),
    shortDescription: "Les feuilles amères indispensables au plat national camerounais.",
    description:
      "Le ndolé (Vernonia) est une plante aux feuilles amères que l'on lave longuement avant de la cuisiner avec des arachides. Nos feuilles sont lavées, émincées et séchées au Cameroun : il suffit de les réhydrater.",
    originCountry: "Cameroun",
    originRegion: "Douala, Littoral",
    producer: "Jardins de Bonabéri (fictif)",
    composition: "Feuilles de Vernonia amygdalina lavées et séchées.",
    allergens: [],
    usageTips: "Réhydrater 30 minutes dans l'eau tiède, rincer deux fois puis presser avant de cuisiner.",
    conservation: "Au sec, à l'abri de la lumière.",
    tags: ["feuilles", "Cameroun"],
    featured: true,
    variants: [["100 g", 790, 30], ["250 g", 1790, 15]],
  },
  {
    slug: "feuilles-de-manioc",
    name: "Feuilles de manioc pilées (pondu)",
    categoryId: cat("feuilles"),
    shortDescription: "Pondu séché, pour le plat mijoté emblématique des deux Congo.",
    description:
      "Les jeunes feuilles de manioc sont pilées puis séchées pour préparer le pondu (ou saka-saka). Il mijote longuement avec de l'huile de palme, du poisson fumé et des aubergines.",
    originCountry: "RD Congo",
    originRegion: "Kinshasa",
    producer: "Mama Pondu (fictif)",
    composition: "Feuilles de manioc pilées et séchées.",
    allergens: [],
    usageTips: "Réhydrater, puis cuire au moins 1 h 30 à feu doux : les feuilles de manioc doivent être longuement cuites.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["feuilles", "Congo"],
    featured: false,
    variants: [["200 g", 690, 30]],
  },
  {
    slug: "fleurs-de-bissap",
    name: "Fleurs de bissap",
    categoryId: cat("feuilles"),
    shortDescription: "Calices d'hibiscus rouge séchés, pour le jus de bissap.",
    description:
      "Les calices d'hibiscus sabdariffa, séchés au soleil, donnent le bissap, la boisson rouge rubis servie dans toute l'Afrique de l'Ouest. Notre sélection vient de la région de Kaolack, réputée pour ses fleurs charnues et très colorées.",
    originCountry: "Sénégal",
    originRegion: "Kaolack",
    producer: "Coopérative de Kaffrine (fictif)",
    composition: "Calices d'Hibiscus sabdariffa séchés.",
    allergens: [],
    usageTips: "Infuser à froid une nuit ou à chaud 10 minutes, filtrer, sucrer et parfumer à la menthe ou à la fleur d'oranger.",
    conservation: "Au sec, à l'abri de la lumière.",
    tags: ["boisson", "hibiscus"],
    featured: true,
    variants: [["100 g", 490, 60], ["250 g", 990, 30]],
  },
  // ----------------------------------------------------- Poissons & fumés
  {
    slug: "guedj",
    name: "Guedj (poisson séché fermenté)",
    categoryId: cat("poissons"),
    shortDescription: "Le secret du thiéboudienne : un poisson fermenté puis séché au soleil.",
    description:
      "Le guedj est un poisson fermenté puis séché sur les plages de Joal et de Mbour. Utilisé en petite quantité, il donne au thiéboudienne et aux sauces leur goût profond et iodé.\n\nOdeur puissante : c'est normal.",
    originCountry: "Sénégal",
    originRegion: "Joal-Fadiouth",
    producer: "Séchoirs de Joal (fictif)",
    composition: "Poisson fermenté et séché, sel.",
    allergens: ["poisson"],
    usageTips: "Rincer, puis ajouter un morceau dans la sauce en début de cuisson.",
    conservation: "Au sec, dans une boîte hermétique.",
    tags: ["poisson", "fermenté"],
    featured: false,
    variants: [["150 g", 890, 20]],
  },
  {
    slug: "crevettes-sechees",
    name: "Crevettes séchées",
    categoryId: cat("poissons"),
    shortDescription: "Petites crevettes séchées de l'estuaire du Wouri.",
    description:
      "Séchées au soleil puis légèrement fumées, ces petites crevettes relèvent le ndolé, les sauces gombo et les soupes. On les utilise entières ou moulues.",
    originCountry: "Cameroun",
    originRegion: "Estuaire du Wouri",
    producer: "Pêcheurs de Youpwé (fictif)",
    composition: "Crevettes séchées, sel.",
    allergens: ["crustacés"],
    usageTips: "Rincer rapidement, puis ajouter entières en fin de cuisson ou moudre dans la sauce.",
    conservation: "Au sec, dans une boîte hermétique.",
    tags: ["crustacés"],
    featured: false,
    variants: [["100 g", 990, 25]],
  },
  {
    slug: "poisson-fume",
    name: "Machoiron fumé",
    categoryId: cat("poissons"),
    shortDescription: "Poisson-chat fumé au feu de bois, pour le pondu et les sauces.",
    description:
      "Le machoiron est un poisson de rivière fumé lentement au feu de bois. Sa chair ferme et fumée parfume le pondu, les sauces graines et les légumes feuilles.",
    originCountry: "RD Congo",
    originRegion: "Fleuve Congo",
    producer: "Fumoirs de Maluku (fictif)",
    composition: "Poisson-chat (Arius) fumé.",
    allergens: ["poisson"],
    usageTips: "Tremper 15 minutes dans l'eau chaude, retirer les arêtes et émietter dans la sauce.",
    conservation: "Au sec et au frais, dans une boîte hermétique.",
    tags: ["fumé", "poisson"],
    featured: false,
    variants: [["200 g", 1290, 15]],
  },
  // ------------------------------------------------------ Huiles & pâtes
  {
    slug: "huile-de-palme-rouge",
    name: "Huile de palme rouge artisanale",
    categoryId: cat("huiles"),
    shortDescription: "Huile rouge non raffinée, pressée par un petit producteur ivoirien.",
    description:
      "Pressée artisanalement à partir de noix de palme fraîches, cette huile rouge non raffinée garde sa couleur et son goût fruité. C'est la base du pondu, de la sauce graine et de nombreux plats d'Afrique centrale.\n\nIssue d'une petite palmeraie familiale, sans déforestation.",
    originCountry: "Côte d'Ivoire",
    originRegion: "Région de la Mé",
    producer: "Palmeraie Kouassi (fictif)",
    composition: "Huile de palme rouge non raffinée.",
    allergens: [],
    usageTips: "Chauffer doucement sans la faire fumer. Elle fige au frais : c'est normal.",
    conservation: "À température ambiante, à l'abri de la lumière.",
    tags: ["non raffinée"],
    featured: false,
    variants: [["500 ml", 890, 30]],
  },
  {
    slug: "pate-d-arachide",
    name: "Pâte d'arachide pure",
    categoryId: cat("huiles"),
    shortDescription: "Arachides grillées et broyées, rien d'autre. Pour le mafé.",
    description:
      "Arachides de la région de Ségou, grillées puis broyées lentement à la meule. Sans sucre, sans sel ni huile ajoutée : exactement ce qu'il faut pour un vrai mafé.",
    originCountry: "Mali",
    originRegion: "Ségou",
    producer: "Moulin de Ségou (fictif)",
    composition: "Arachides grillées.",
    allergens: ["arachide"],
    usageTips: "Délayer dans un peu de bouillon chaud avant de l'ajouter à la sauce.",
    conservation: "À température ambiante. Remuer avant usage (l'huile remonte naturellement).",
    tags: ["arachide"],
    featured: true,
    variants: [["500 g", 690, 40]],
  },
  {
    slug: "pulpe-de-noix-de-palme",
    name: "Pulpe de noix de palme (nyembwe)",
    categoryId: cat("huiles"),
    shortDescription: "La crème de noix de palme du poulet nyembwe et de la sauce graine.",
    description:
      "Extraite des noix de palme cuites et pilées, cette pulpe orangée est la base du poulet nyembwe gabonais et de la sauce graine ivoirienne. Onctueuse et fruitée.",
    originCountry: "Gabon",
    originRegion: "Estuaire",
    producer: "Conserverie de l'Estuaire (fictif)",
    composition: "Pulpe de noix de palme, eau.",
    allergens: [],
    usageTips: "Diluer dans l'eau et faire réduire lentement avec la viande jusqu'à ce que l'huile remonte.",
    conservation: "Avant ouverture : à température ambiante. Après ouverture : au frais, 5 jours.",
    tags: ["palme"],
    featured: false,
    variants: [["400 g", 490, 40]],
  },
  // ------------------------------------------- Ajouts (nouvelles recettes)
  {
    slug: "graines-d-egusi",
    name: "Graines d'egusi décortiquées",
    categoryId: cat("epices"),
    shortDescription: "Graines de courge africaine, à moudre pour épaissir les soupes nigérianes.",
    description:
      "L'egusi est la graine d'une courge d'Afrique de l'Ouest. Moulue, elle épaissit et parfume la célèbre soupe egusi du Nigeria et du Ghana, avec un goût doux de noisette.\n\nGraines décortiquées à la main, prêtes à moudre.",
    originCountry: "Nigeria",
    originRegion: "État d'Ogun",
    producer: "Coopérative d'Abeokuta (fictif)",
    composition: "Graines de courge egusi (Citrullus lanatus) décortiquées.",
    allergens: [],
    usageTips: "Moudre finement, délayer avec un peu d'eau puis cuire dans la sauce jusqu'à former des grumeaux moelleux.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["graines", "Nigeria"],
    featured: true,
    variants: [["250 g", 790, 30], ["500 g", 1390, 15]],
  },
  {
    slug: "gombo-seche",
    name: "Gombo séché en poudre",
    categoryId: cat("feuilles"),
    shortDescription: "Gombo séché au soleil et moulu, pour la sauce gluante du tô.",
    description:
      "Au Sahel, le gombo est coupé en rondelles, séché au soleil puis moulu. Cette poudre verte donne à la sauce gombo sa texture filante caractéristique, même loin de la saison des récoltes.",
    originCountry: "Burkina Faso",
    originRegion: "Plateau central",
    producer: "Jardins de Koudougou (fictif)",
    composition: "Gombo (Abelmoschus esculentus) séché et moulu.",
    allergens: [],
    usageTips: "Verser en pluie dans la sauce frémissante en fouettant, puis cuire 5 minutes.",
    conservation: "Au sec, à l'abri de la lumière.",
    tags: ["gombo", "Sahel"],
    featured: false,
    variants: [["100 g", 590, 30]],
  },
  {
    slug: "feuilles-de-moringa",
    name: "Feuilles de moringa séchées",
    categoryId: cat("feuilles"),
    shortDescription: "Le nébédaye du Sénégal, pour le thiéré mbuum et les sauces feuilles.",
    description:
      "Au Sénégal, les feuilles de moringa (nébédaye) parfument le thiéré mbuum, un couscous de mil aux feuilles et à l'arachide. Séchées à l'ombre, elles gardent leur couleur vert vif et leur goût herbacé.",
    originCountry: "Sénégal",
    originRegion: "Thiès",
    producer: "Maraîchers des Niayes (fictif)",
    composition: "Feuilles de moringa (Moringa oleifera) séchées.",
    allergens: [],
    usageTips: "Réhydrater quelques minutes puis ajouter dans la sauce ou le couscous en fin de cuisson.",
    conservation: "Au sec, à l'abri de la lumière.",
    tags: ["feuilles", "Sénégal"],
    featured: false,
    variants: [["100 g", 690, 30]],
  },
  {
    slug: "feuilles-de-sorgho",
    name: "Feuilles de sorgho rouge (waakye)",
    categoryId: cat("feuilles"),
    shortDescription: "Les feuilles qui donnent au waakye ghanéen sa couleur brun-rouge.",
    description:
      "Au Ghana, le riz et les haricots du waakye cuisent avec des feuilles de sorgho rouge séchées, qui leur donnent leur couleur brun-rouge caractéristique et un léger parfum.",
    originCountry: "Ghana",
    originRegion: "Tamale",
    producer: "Marché de Tamale (fictif)",
    composition: "Feuilles et tiges de sorgho rouge séchées.",
    allergens: [],
    usageTips: "Rincer, ajouter à l'eau de cuisson du riz et des haricots, puis retirer avant de servir.",
    conservation: "Au sec.",
    tags: ["feuilles", "Ghana"],
    featured: false,
    variants: [["50 g", 490, 40]],
  },
  {
    slug: "feuilles-d-okok",
    name: "Feuilles d'okok émincées",
    categoryId: cat("feuilles"),
    shortDescription: "Les feuilles de forêt de l'eru camerounais, finement émincées et séchées.",
    description:
      "L'okok (ou eru) est une liane de la forêt camerounaise dont les feuilles, émincées très finement, se cuisinent avec de l'huile de palme, de la viande et du poisson fumé.",
    originCountry: "Cameroun",
    originRegion: "Sud-Ouest",
    producer: "Cueilleurs de Kumba (fictif)",
    composition: "Feuilles de Gnetum africanum émincées et séchées.",
    allergens: [],
    usageTips: "Réhydrater 15 minutes dans l'eau tiède avant de cuisiner.",
    conservation: "Au sec, à l'abri de la lumière.",
    tags: ["feuilles", "forêt"],
    featured: false,
    variants: [["100 g", 890, 25]],
  },
  {
    slug: "odika",
    name: "Odika (chocolat indigène)",
    categoryId: cat("huiles"),
    shortDescription: "Pain d'amandes de mangue sauvage, l'ingrédient signature du Gabon.",
    description:
      "L'odika, surnommé « chocolat indigène », est un pain sombre fait d'amandes de mangue sauvage grillées et pressées. Râpé dans les sauces, il leur donne une couleur brune, une texture onctueuse et un goût fumé très particulier.",
    originCountry: "Gabon",
    originRegion: "Ogooué-Ivindo",
    producer: "Forêt de Makokou (fictif)",
    composition: "Amandes de mangue sauvage (Irvingia gabonensis) grillées et pressées.",
    allergens: ["fruits à coque"],
    usageTips: "Râper ou chauffer légèrement pour ramollir, puis délayer dans la sauce en fin de cuisson.",
    conservation: "Au sec et au frais, emballé.",
    tags: ["Gabon", "forêt"],
    featured: true,
    variants: [["150 g", 1190, 15]],
  },
  {
    slug: "farine-de-teff",
    name: "Farine de teff",
    categoryId: cat("cereales"),
    shortDescription: "La minuscule céréale éthiopienne de l'injera.",
    description:
      "Le teff est une céréale minuscule cultivée depuis des millénaires sur les hauts plateaux éthiopiens. Sa farine, fermentée quelques jours, donne l'injera, la grande galette alvéolée qui sert d'assiette et de couvert.",
    originCountry: "Éthiopie",
    originRegion: "Amhara",
    producer: "Moulin de Debre Markos (fictif)",
    composition: "Farine complète de teff (Eragrostis tef).",
    allergens: [],
    usageTips: "Mélanger à l'eau et laisser fermenter 2 à 3 jours avant de cuire les injeras.",
    conservation: "Au sec et au frais, dans un contenant fermé.",
    tags: ["céréale ancienne", "Éthiopie"],
    featured: true,
    variants: [["500 g", 690, 30], ["1 kg", 1190, 15]],
  },
  {
    slug: "poudre-de-baobab",
    name: "Pain de singe (poudre de baobab)",
    categoryId: cat("cereales"),
    shortDescription: "La pulpe acidulée du fruit du baobab, pour le bouye et le ngalakh.",
    description:
      "Le fruit du baobab, appelé pain de singe, renferme une pulpe sèche et farineuse au goût acidulé. Au Sénégal, on en fait le jus de bouye et la crème du ngalakh, le dessert de Pâques.",
    originCountry: "Sénégal",
    originRegion: "Sine-Saloum",
    producer: "Cueilleurs de Fatick (fictif)",
    composition: "Pulpe de fruit du baobab (Adansonia digitata) tamisée.",
    allergens: [],
    usageTips: "Délayer dans l'eau froide ou le lait, filtrer si besoin et sucrer à votre goût.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["baobab", "Sénégal"],
    featured: false,
    variants: [["250 g", 790, 30]],
  },
  {
    slug: "farine-de-foufou",
    name: "Farine de foufou (manioc et plantain)",
    categoryId: cat("cereales"),
    shortDescription: "Pour préparer le fufu lisse et élastique en quelques minutes.",
    description:
      "Mélange de farine de manioc et de plantain, cette farine permet de préparer un fufu lisse et élastique sans piler au mortier. Il accompagne les soupes du Ghana, du Nigeria et d'Afrique centrale.",
    originCountry: "Ghana",
    originRegion: "Kumasi",
    producer: "Moulins Ashanti (fictif)",
    composition: "Farine de manioc, farine de plantain.",
    allergens: [],
    usageTips: "Verser dans l'eau bouillante en remuant vigoureusement avec une spatule jusqu'à obtenir une pâte lisse.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["manioc", "plantain"],
    featured: false,
    variants: [["1 kg", 690, 40]],
  },
];

export const demoProducts: Product[] = seeds.map((seed, index) => {
  const productId = id("2", index + 1);
  return {
    ...seed,
    id: productId,
    images: [`/products/${seed.slug}.webp`],
    isActive: true,
    createdAt: new Date(Date.UTC(2026, 0, 1 + index)).toISOString(),
    variants: variants(productId, seed.variants),
  };
});
