/**
 * Produits ajoutés le 27 septembre 2026 : épicerie, cafés et thés, ustensiles.
 * Chacun est vendu sur Amazon.fr (plus de 3,5 étoiles au relevé) : ASIN, format et prix de la fiche.
 * Fichier généré à partir des fiches rédigées ; à modifier ensuite à la main si besoin.
 */

export interface NouveauProduit {
  slug: string;
  name: string;
  category: string;
  shortDescription: string;
  description: string;
  originCountry: string | null;
  originRegion: string | null;
  composition: string | null;
  allergens: string[];
  usageTips: string | null;
  conservation: string | null;
  tags: string[];
  amazon: { asin: string; label: string; priceCents: number };
}

export const nouveauxProduits: NouveauProduit[] = [
  {
    slug: "piment-pili-pili",
    name: "Piment oiseau pili-pili entier",
    category: "epices",
    shortDescription: "Le petit piment rouge qui relève toutes les sauces du continent.",
    description: "Petit, rouge vif et très piquant, le pili-pili (ou piment oiseau) est présent de Dakar à Kinshasa. Séché entier, il garde son parfum fruité et sa force.\n\nOn le jette entier dans les sauces pour une chaleur douce, ou on l'écrase au mortier pour un piquant franc. Il sert aussi de base aux huiles pimentées maison.",
    originCountry: "Afrique",
    originRegion: null,
    composition: "Piments oiseau (Capsicum frutescens) séchés entiers.",
    allergens: [],
    usageTips: "Ajouter un ou deux piments entiers dans le mafé ou le yassa et les retirer avant de servir si l'on veut un piquant modéré. Se laver les mains après manipulation.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["piment", "piquant"],
    amazon: { asin: "B092VLDV68", label: "100 g", priceCents: 1300 },
  },
  {
    slug: "bitter-kola",
    name: "Bitter kola (petites noix)",
    category: "epices",
    shortDescription: "La noix amère que l'on partage lors des visites et des cérémonies en Afrique de l'Ouest.",
    description: "Le bitter kola est la graine du Garcinia kola, un arbre des forêts d'Afrique de l'Ouest et centrale. Brune et ferme, elle a une amertume franche suivie d'une note légèrement astringente.\n\nAu Nigeria, on l'offre aux invités et on la croque lors des rencontres et des cérémonies traditionnelles, souvent avec la noix de kola. Un produit de tradition plus que de cuisine.",
    originCountry: "Nigeria",
    originRegion: null,
    composition: "Noix de bitter kola (Garcinia kola).",
    allergens: [],
    usageTips: "Retirer la fine peau brune, puis croquer la noix nature, en petits morceaux. Son amertume se marie bien avec une boisson fraîche.",
    conservation: "Au frais et au sec, dans un sachet ou un bocal fermé.",
    tags: ["noix", "tradition", "Nigeria"],
    amazon: { asin: "B09YPZ3T11", label: "20 noix", priceCents: 999 },
  },
  {
    slug: "cafe-touba",
    name: "Café Touba",
    category: "cafes-thes",
    shortDescription: "Le café épicé au poivre de Selim, servi à tous les coins de rue du Sénégal.",
    description: "Né à Touba, ville sainte du mouridisme, le café Touba est un café torréfié avec du djar, le poivre de Selim. Il en ressort une boisson sombre aux notes poivrées, boisées et légèrement fumées.\n\nAu Sénégal, il se boit très sucré, préparé au filtre en tissu et servi dans de petits gobelets, du matin au soir.",
    originCountry: "Sénégal",
    originRegion: "Touba",
    composition: "Café torréfié et moulu, poivre de Selim (djar).",
    allergens: [],
    usageTips: "Préparer au filtre, avec une cuillère de café Touba par tasse, et sucrer généreusement comme au Sénégal.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Sénégal", "épicé"],
    amazon: { asin: "B0B52RYJS8", label: "250 g", priceCents: 1599 },
  },
  {
    slug: "farine-d-igname",
    name: "Farine d'igname (amala / elubo)",
    category: "cereales",
    shortDescription: "La farine d'igname séchée qui donne l'amala, la pâte brune des Yoruba.",
    description: "L'elubo est une farine obtenue à partir d'igname épluchée, séchée puis moulue. Travaillée dans l'eau bouillante, elle donne l'amala, une pâte souple à la couleur brune caractéristique.\n\nAu sud-ouest du Nigeria, l'amala accompagne l'ewedu, le gbegiri et les sauces au poisson ou à la viande.",
    originCountry: "Nigeria",
    originRegion: null,
    composition: "Igname séchée et moulue.",
    allergens: [],
    usageTips: "Verser la farine en pluie dans l'eau bouillante en tournant vivement à la spatule jusqu'à obtenir une pâte lisse et élastique.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["igname", "amala", "Nigeria"],
    amazon: { asin: "B08CF5G29P", label: "1,8 kg", priceCents: 1290 },
  },
  {
    slug: "akpi-djansang",
    name: "Akpi / djansang (graines)",
    category: "epices",
    shortDescription: "Petites graines au goût de noisette qui épaississent et parfument les sauces.",
    description: "L'akpi, appelé djansang au Cameroun, est la graine du Ricinodendron heudelotii, un grand arbre des forêts d'Afrique de l'Ouest et centrale. Torréfiées et moulues, les graines ont un goût doux de noisette et de sésame.\n\nOn l'utilise pour lier et parfumer les sauces, les marinades de poisson braisé et les sauces tomate.",
    originCountry: "Côte d'Ivoire / Cameroun",
    originRegion: null,
    composition: "Graines d'akpi (Ricinodendron heudelotii) séchées.",
    allergens: [],
    usageTips: "Torréfier légèrement à sec, puis moudre ou écraser au mortier avant de les ajouter à la sauce ou à la marinade du poisson braisé.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["graines", "sauce", "Cameroun"],
    amazon: { asin: "B0CP9SPRP8", label: "50 g", priceCents: 899 },
  },
  {
    slug: "assaisonnement-jollof",
    name: "Assaisonnement jollof",
    category: "epices",
    shortDescription: "Un mélange d'épices prêt à l'emploi pour le riz jollof.",
    description: "Le riz jollof, riz rouge cuit dans une sauce tomate épicée, se dispute entre le Nigeria et le Ghana. Ce mélange réunit les épices et aromates qui lui donnent sa couleur et son parfum.\n\nIl permet de réussir un jollof bien assaisonné sans multiplier les pots d'épices.",
    originCountry: "Nigeria / Ghana",
    originRegion: null,
    composition: "Mélange d'épices et d'aromates.",
    allergens: [],
    usageTips: "Ajouter à la base tomate-oignon-piment une fois qu'elle a bien réduit, avant d'y verser le riz et le bouillon.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["mélange", "riz", "jollof"],
    amazon: { asin: "B0B8135LLS", label: "100 g", priceCents: 1196 },
  },
  {
    slug: "maniguette",
    name: "Maniguette (graines de paradis)",
    category: "epices",
    shortDescription: "Des graines au piquant poivré et aux notes d'agrumes, cousines de la cardamome.",
    description: "La maniguette, ou graine de paradis, pousse en gousses sur l'Aframomum melegueta, une plante des côtes d'Afrique de l'Ouest. Ses petites graines brunes offrent un piquant proche du poivre, avec des notes citronnées et florales.\n\nElle parfume les sauces, les grillades et les bouillons, et se moud comme un poivre.",
    originCountry: "Côte d'Ivoire",
    originRegion: null,
    composition: "Gousses de maniguette (Aframomum melegueta).",
    allergens: [],
    usageTips: "Ouvrir la gousse, écraser les graines au mortier et les ajouter en fin de cuisson sur les viandes et poissons grillés.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["poivre", "graines"],
    amazon: { asin: "B0DR681HDS", label: "4 gousses", priceCents: 899 },
  },
  {
    slug: "essesse-sassas",
    name: "Essessè / sassas en poudre",
    category: "epices",
    shortDescription: "Une épice camerounaise au parfum boisé et sucré pour les bouillons et sauces.",
    description: "L'essessè est une épice de la cuisine camerounaise, séchée puis réduite en poudre. Elle apporte un parfum boisé, légèrement sucré et fumé.\n\nOn l'associe au pèbè et au djansang dans les épices des soupes, des bouillons de poisson et des sauces jaunes.",
    originCountry: "Cameroun",
    originRegion: null,
    composition: "Épice d'essessè séchée et moulue.",
    allergens: [],
    usageTips: "En ajouter une petite pincée dans le bouillon en début de cuisson, avec les autres épices à soupe.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["épice", "Cameroun", "soupe"],
    amazon: { asin: "B0CG9Z9QDN", label: "100 g", priceCents: 1599 },
  },
  {
    slug: "infusion-de-tamarin",
    name: "Infusion de tamarin",
    category: "cafes-thes",
    shortDescription: "Le goût acidulé du tamarin, en sachets à infuser.",
    description: "Le tamarin, ou dakhar au Sénégal, est la gousse d'un grand arbre des savanes. Sa pulpe acidulée et fruitée sert aussi bien aux boissons qu'aux sauces.\n\nCette infusion en sachets permet de retrouver facilement la saveur du jus de tamarin, chaude ou froide.",
    originCountry: "Sénégal",
    originRegion: null,
    composition: "Tamarin séché, en sachets à infuser.",
    allergens: [],
    usageTips: "Infuser un sachet dans l'eau chaude, sucrer à son goût ; se boit aussi bien glacé, avec quelques feuilles de menthe.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["infusion", "tamarin", "Sénégal"],
    amazon: { asin: "B079VNZ645", label: "25 sachets", priceCents: 1390 },
  },
  {
    slug: "infusion-de-gingembre",
    name: "Infusion de gingembre",
    category: "cafes-thes",
    shortDescription: "Le piquant du gingembre, en sachets, pour une boisson chaude ou glacée.",
    description: "Au Sénégal, le gingembre se boit en jus, le gnamakoudji, très relevé et bien sucré. Cette infusion en sachets en reprend la saveur piquante, en version plus simple à préparer.\n\nElle se boit chaude, ou refroidie avec du citron et de la menthe.",
    originCountry: "Sénégal",
    originRegion: null,
    composition: "Gingembre séché, en sachets à infuser.",
    allergens: [],
    usageTips: "Infuser un sachet dans l'eau chaude, ajouter un trait de citron et du sucre ou du miel selon le goût.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["infusion", "gingembre", "Sénégal"],
    amazon: { asin: "B079VNZ641", label: "25 sachets", priceCents: 999 },
  },
  {
    slug: "chips-de-plantain",
    name: "Chips de plantain",
    category: "cereales",
    shortDescription: "Fines tranches de banane plantain frites, croustillantes et légèrement salées.",
    description: "Vendues au bord des routes de Douala à Accra, les chips de plantain sont faites de fines tranches de banane plantain frites jusqu'à devenir bien croustillantes.\n\nElles se grignotent à l'apéritif ou accompagnent une boisson fraîche, un jus de bissap ou de gingembre.",
    originCountry: "Afrique de l'Ouest et centrale",
    originRegion: null,
    composition: "Banane plantain, huile végétale, sel.",
    allergens: [],
    usageTips: "À servir nature à l'apéritif, ou avec une sauce pimentée pour tremper.",
    conservation: "Au sec ; une fois le sachet ouvert, bien refermer et consommer rapidement.",
    tags: ["plantain", "apéritif", "snack"],
    amazon: { asin: "B0C6YLBNM4", label: "5 × 85 g", priceCents: 890 },
  },
  {
    slug: "gari-jaune",
    name: "Gari jaune (semoule de manioc)",
    category: "cereales",
    shortDescription: "Semoule de manioc fermenté et torréfié, pour l'eba ou à boire à l'eau fraîche.",
    description: "Le gari est obtenu en râpant du manioc, en le laissant fermenter, puis en le torréfiant en fines graines croquantes. La version jaune doit sa couleur à l'huile de palme ajoutée pendant la cuisson.\n\nAu Bénin, au Nigeria et au Ghana, on le travaille dans l'eau chaude pour faire l'eba, ou on le trempe dans l'eau froide avec du sucre et des arachides.",
    originCountry: "Bénin / Nigeria / Ghana",
    originRegion: null,
    composition: "Manioc fermenté, râpé et torréfié, huile de palme.",
    allergens: [],
    usageTips: "Pour l'eba : verser le gari dans l'eau bouillante, laisser gonfler puis malaxer à la spatule. Servir avec une sauce gombo ou egusi.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["manioc", "gari", "eba"],
    amazon: { asin: "B0D5BX4R97", label: "900 g", priceCents: 990 },
  },
  {
    slug: "farine-de-plantain-pour-fufu",
    name: "Farine de plantain pour fufu",
    category: "cereales",
    shortDescription: "Une farine de plantain pour préparer le fufu sans piler.",
    description: "Au Ghana, le fufu se pile traditionnellement au mortier à partir de plantain et de manioc cuits. Cette farine de plantain séché permet d'obtenir une pâte lisse directement à la casserole.\n\nLe fufu accompagne les soupes légères : soupe d'arachide, light soup, soupe de noix de palme.",
    originCountry: "Ghana",
    originRegion: null,
    composition: "Farine de banane plantain.",
    allergens: [],
    usageTips: "Délayer la farine dans l'eau froide, puis cuire à feu moyen en tournant sans cesse jusqu'à obtenir une pâte ferme et lisse.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["plantain", "fufu", "Ghana"],
    amazon: { asin: "B00MWVXFC0", label: "680 g", priceCents: 990 },
  },
  {
    slug: "chikwangue",
    name: "Chikwangue (bâton de manioc)",
    category: "cereales",
    shortDescription: "Le pain de manioc fermenté des deux Congo, cuit dans des feuilles.",
    description: "La chikwangue, ou kwanga, est une pâte de manioc fermenté façonnée en bâton, enveloppée dans des feuilles puis cuite à la vapeur. Sa texture est ferme et élastique, son goût légèrement acidulé.\n\nEn RD Congo et au Congo, elle accompagne le poisson grillé, le pondu, la moambe et toutes les sauces.",
    originCountry: "RD Congo / Congo",
    originRegion: null,
    composition: "Manioc fermenté.",
    allergens: [],
    usageTips: "Retirer les feuilles, couper en tranches et servir tel quel ou réchauffé à la vapeur, avec du poisson braisé ou une sauce.",
    conservation: "Suivre les indications de l'emballage ; une fois ouverte, conserver au frais et consommer rapidement.",
    tags: ["manioc", "Congo", "fermenté"],
    amazon: { asin: "B0FPPTF2D9", label: "3 × 250 g", priceCents: 1411 },
  },
  {
    slug: "tapioca-de-manioc",
    name: "Tapioca de manioc granulé",
    category: "cereales",
    shortDescription: "Des granules de manioc à gonfler, pour les desserts et les bouillies.",
    description: "Le tapioca granulé est tiré de l'amidon de manioc, humidifié puis roulé en petits grains. Dans l'eau, il gonfle et devient translucide.\n\nEn Afrique de l'Ouest et centrale, on le prépare en bouillie sucrée, trempé dans l'eau froide avec du lait et du sucre, ou dans des desserts à la noix de coco.",
    originCountry: "Afrique de l'Ouest et centrale",
    originRegion: null,
    composition: "Manioc granulé.",
    allergens: [],
    usageTips: "Tremper dans l'eau froide ou chaude jusqu'à ce qu'il gonfle, puis ajouter du lait, du sucre et éventuellement des arachides grillées.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["manioc", "dessert"],
    amazon: { asin: "B0D1P648SL", label: "1 kg", priceCents: 990 },
  },
  {
    slug: "pebe-moulu",
    name: "Pèbè moulu (muscade africaine)",
    category: "epices",
    shortDescription: "La muscade africaine, chaude et parfumée, pour les soupes et les grillades.",
    description: "Le pèbè est la graine du Monodora myristica, un arbre des forêts tropicales. Moulue, elle rappelle la noix de muscade, avec des notes plus douces et légèrement épicées.\n\nAu Cameroun, elle entre dans les épices du poisson braisé, du pèpè soupe et de nombreuses sauces.",
    originCountry: "Cameroun",
    originRegion: null,
    composition: "Graines de pèbè (Monodora myristica) moulues.",
    allergens: [],
    usageTips: "Mélanger à l'ail, au gingembre et au djansang pour mariner le poisson braisé, ou en ajouter une pincée dans le bouillon.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["épice", "Cameroun", "muscade"],
    amazon: { asin: "B0BV7HBJWZ", label: "50 g", priceCents: 899 },
  },
  {
    slug: "biltong",
    name: "Biltong",
    category: "poissons",
    shortDescription: "La viande séchée et épicée d'Afrique du Sud, à grignoter en lamelles.",
    description: "Le biltong est une viande marinée dans le vinaigre et les épices (coriandre, poivre, sel), puis séchée à l'air. Tradition sud-africaine, il se déguste en fines lamelles, à la main.\n\nOn le sert à l'apéritif, lors des braais, ou en randonnée ; il s'émiette aussi dans les salades et les pâtes.",
    originCountry: "Afrique du Sud",
    originRegion: null,
    composition: "Viande de bœuf, vinaigre, sel, épices (coriandre, poivre).",
    allergens: [],
    usageTips: "Trancher finement et servir à température ambiante, en apéritif ou en accompagnement d'une salade.",
    conservation: "Au sec et au frais ; une fois le paquet ouvert, conserver au frais et consommer rapidement.",
    tags: ["viande séchée", "Afrique du Sud", "apéritif"],
    amazon: { asin: "B06VTJD4RF", label: "500 g", priceCents: 8599 },
  },
  {
    slug: "sauce-graine-nkulenus",
    name: "Sauce graine (pulpe de noix de palme)",
    category: "huiles",
    shortDescription: "La base de sauce graine et de soupe de noix de palme, prête à cuisiner.",
    description: "La sauce graine se prépare à partir de la pulpe des noix de palme, longuement bouillies et pilées. Cette crème de palme évite toute cette étape et donne une sauce onctueuse, orangée et parfumée.\n\nElle sert pour la sauce graine ivoirienne, la palm nut soup ghanéenne ou le banga nigérian, avec poisson fumé, viande ou crabe.",
    originCountry: "Ghana",
    originRegion: null,
    composition: "Pulpe de noix de palme.",
    allergens: [],
    usageTips: "Délayer la pulpe dans de l'eau chaude, porter à ébullition puis laisser mijoter avec la viande ou le poisson fumé jusqu'à ce que l'huile remonte.",
    conservation: "Au sec tant que la boîte est fermée ; ensuite, au frais dans un contenant fermé et à utiliser rapidement.",
    tags: ["palme", "sauce graine"],
    amazon: { asin: "B0DZJPCQ6B", label: "390 g", priceCents: 699 },
  },
  {
    slug: "feuilles-de-baobab",
    name: "Feuilles de baobab séchées (lalo)",
    category: "feuilles",
    shortDescription: "La poudre de feuilles de baobab qui lie le couscous et les sauces du Sahel.",
    description: "Le lalo est fait de feuilles de baobab séchées puis réduites en poudre verte. Il donne une texture légèrement filante et un goût herbacé discret.\n\nAu Sénégal, on l'ajoute au thiéré (couscous de mil) pour le rendre souple ; au Mali, il sert à préparer des sauces feuilles.",
    originCountry: "Sénégal / Mali",
    originRegion: null,
    composition: "Feuilles de baobab (Adansonia digitata) séchées et moulues.",
    allergens: [],
    usageTips: "Pour le thiéré, délayer une cuillère de lalo dans un peu d'eau et en humecter le couscous avant la cuisson à la vapeur.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["baobab", "feuilles", "Sénégal"],
    amazon: { asin: "B0DFWZ6FR9", label: "50 g", priceCents: 981 },
  },
  {
    slug: "vanille-bourbon-de-madagascar",
    name: "Vanille bourbon de Madagascar",
    category: "epices",
    shortDescription: "Des gousses de vanille souples et parfumées, de la côte nord-est de Madagascar.",
    description: "La vanille bourbon est cultivée à Madagascar, où chaque fleur est fécondée à la main. Les gousses sont ensuite échaudées, étuvées et séchées lentement pour développer leur arôme.\n\nElle parfume les desserts, les crèmes, le rhum arrangé, mais aussi certaines sauces pour le poisson ou les crustacés.",
    originCountry: "Madagascar",
    originRegion: "Sava",
    composition: "Gousses de vanille (Vanilla planifolia).",
    allergens: [],
    usageTips: "Fendre la gousse, gratter les graines et les infuser dans le lait chaud ; la gousse vidée peut parfumer un bocal de sucre.",
    conservation: "Dans un tube ou un bocal hermétique, au frais et à l'abri de la lumière (pas au réfrigérateur).",
    tags: ["vanille", "Madagascar", "dessert"],
    amazon: { asin: "B0949LGX4T", label: "10 gousses", priceCents: 1590 },
  },
  {
    slug: "sauce-peri-peri",
    name: "Sauce peri-peri",
    category: "epices",
    shortDescription: "La sauce pimentée au citron et à l'ail, héritée de la cuisine du Mozambique.",
    description: "Le peri-peri est un petit piment africain qui a donné son nom à une sauce née au Mozambique et devenue emblématique en Afrique du Sud. Piment, citron, ail et vinaigre composent une sauce vive et piquante.\n\nElle accompagne surtout le poulet grillé, mais aussi les crevettes, le poisson et les frites.",
    originCountry: "Afrique du Sud / Mozambique",
    originRegion: null,
    composition: "Piment, vinaigre, citron, ail, sel, épices.",
    allergens: [],
    usageTips: "Badigeonner le poulet avant de le griller, puis en napper de nouveau à la sortie du feu.",
    conservation: "Au frais une fois ouverte, bouchon bien fermé.",
    tags: ["piment", "sauce", "grillade"],
    amazon: { asin: "B0019MEJPA", label: "117 g", priceCents: 1200 },
  },
  {
    slug: "poivre-sauvage-voatsiperifery",
    name: "Poivre sauvage voatsiperifery",
    category: "epices",
    shortDescription: "Un poivre à queue cueilli en forêt, aux notes boisées et d'agrumes.",
    description: "Le voatsiperifery est un poivre sauvage qui pousse sur des lianes dans les forêts de Madagascar. Ses baies à petite queue sont cueillies à la main, puis séchées.\n\nSon piquant est plus doux que celui du poivre noir, avec des notes fraîches, boisées et légèrement citronnées.",
    originCountry: "Madagascar",
    originRegion: null,
    composition: "Baies de poivre sauvage (Piper borbonense) séchées.",
    allergens: [],
    usageTips: "Moudre au dernier moment sur les poissons, les viandes blanches, les légumes ou même les fruits.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["poivre", "cueillette", "Madagascar"],
    amazon: { asin: "B08M49PCY9", label: "100 g", priceCents: 1490 },
  },
  {
    slug: "ras-el-hanout",
    name: "Ras el hanout",
    category: "epices",
    shortDescription: "Le mélange d'épices marocain, chaud et parfumé, des tajines et couscous.",
    description: "Ras el hanout signifie « la tête de l'épicerie » : chaque épicier compose son propre mélange avec ses meilleures épices. Cumin, coriandre, cannelle, gingembre, curcuma et poivre en forment souvent la base.\n\nIl parfume les tajines, les couscous, les marinades de viande et les légumes rôtis.",
    originCountry: "Maroc",
    originRegion: null,
    composition: "Mélange d'épices.",
    allergens: [],
    usageTips: "Faire revenir une cuillère de ras el hanout dans l'huile avec les oignons avant d'ajouter la viande du tajine.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["mélange", "Maroc", "tajine"],
    amazon: { asin: "B08QZ7P9LL", label: "250 g", priceCents: 999 },
  },
  {
    slug: "souchet",
    name: "Souchet (noix tigrée)",
    category: "cereales",
    shortDescription: "Petits tubercules sucrés au goût de noisette, pour les boissons et les en-cas.",
    description: "Malgré son nom de noix tigrée, le souchet est un petit tubercule cultivé en Afrique de l'Ouest. Il a un goût sucré qui rappelle l'amande et la noisette.\n\nAu Nigeria, on le mixe pour préparer le kunun aya, une boisson lactée ; ailleurs, on le grignote simplement après l'avoir fait tremper.",
    originCountry: "Afrique de l'Ouest",
    originRegion: null,
    composition: "Tubercules de souchet (Cyperus esculentus) séchés.",
    allergens: [],
    usageTips: "Faire tremper une nuit, puis mixer avec de l'eau, des dattes et un peu de gingembre ; filtrer pour obtenir une boisson lactée.",
    conservation: "Au sec, dans un contenant fermé.",
    tags: ["souchet", "boisson", "tubercule"],
    amazon: { asin: "B01LAY7LN8", label: "500 g", priceCents: 1499 },
  },
  {
    slug: "epices-tunisiennes",
    name: "Épices tunisiennes (lot)",
    category: "epices",
    shortDescription: "Un assortiment d'épices pour cuisiner à la tunisienne.",
    description: "Carvi, coriandre, piment, tabel : la cuisine tunisienne aime les épices franches. Ce lot réunit plusieurs épices et mélanges du pays pour composer ses propres assaisonnements.\n\nIl sert pour le couscous, la chakchouka, les ragoûts de légumes et les marinades de poisson.",
    originCountry: "Tunisie",
    originRegion: null,
    composition: "Assortiment d'épices et de mélanges d'épices.",
    allergens: [],
    usageTips: "Faire revenir les épices quelques instants dans l'huile d'olive avant d'ajouter la tomate, pour libérer leur parfum.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["épices", "Tunisie", "assortiment"],
    amazon: { asin: "B0CQVWV82R", label: "6 × 150 g", priceCents: 890 },
  },
  {
    slug: "dukkah",
    name: "Dukkah",
    category: "epices",
    shortDescription: "Le mélange égyptien de fruits à coque, graines et épices, à tremper avec du pain.",
    description: "Le dukkah est un mélange égyptien de fruits à coque torréfiés, de graines de sésame et d'épices comme la coriandre et le cumin, grossièrement concassés.\n\nOn le sert traditionnellement avec du pain trempé dans l'huile d'olive, mais il enrobe aussi très bien les légumes, les salades et les poissons.",
    originCountry: "Égypte",
    originRegion: null,
    composition: "Fruits à coque, graines de sésame, épices, sel.",
    allergens: ["fruits à coque", "sésame"],
    usageTips: "Tremper un morceau de pain dans l'huile d'olive puis dans le dukkah, ou en parsemer une salade ou des légumes rôtis.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["mélange", "Égypte", "apéritif"],
    amazon: { asin: "B08HY51WZC", label: "75 g", priceCents: 1891 },
  },
  {
    slug: "dattes-deglet-nour",
    name: "Dattes Deglet Nour",
    category: "cereales",
    shortDescription: "Des dattes dorées et translucides, au goût de miel.",
    description: "La Deglet Nour, « doigt de lumière », est la variété de dattes phare de Tunisie. Sa chair blonde et translucide a une texture fondante et un goût de miel.\n\nElles se dégustent nature, avec du lait ou du thé, et entrent dans les tajines sucrés-salés, les couscous et les pâtisseries.",
    originCountry: "Tunisie",
    originRegion: "Djérid",
    composition: "Dattes Deglet Nour.",
    allergens: [],
    usageTips: "Dénoyauter et farcir de pâte d'amande, ou ajouter aux tajines d'agneau en fin de cuisson.",
    conservation: "Au frais et au sec, dans une boîte fermée.",
    tags: ["dattes", "Tunisie", "fruits secs"],
    amazon: { asin: "B01MQKD9BU", label: "500 g", priceCents: 1154 },
  },
  {
    slug: "mortier-et-pilon-en-bois",
    name: "Mortier et pilon en bois d'acacia",
    category: "ustensiles",
    shortDescription: "Le mortier en bois pour piler épices, arachides et feuilles.",
    description: "Dans les cuisines africaines, le mortier en bois est un outil du quotidien. En acacia, bois dense et solide, il permet d'écraser épices, ail, piment, arachides grillées ou feuilles.\n\nSa taille le destine aux préparations de tous les jours, pour les pâtes d'épices et les petites quantités.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Piler l'ail, le gingembre et le piment pour le yassa, ou les arachides grillées. Laver à l'eau chaude sans tremper, bien sécher et huiler de temps en temps.",
    conservation: null,
    tags: ["mortier", "bois", "épices"],
    amazon: { asin: "B0972M8VRF", label: "1 pièce", priceCents: 2320 },
  },
  {
    slug: "huile-d-argan",
    name: "Huile d'argan alimentaire",
    category: "huiles",
    shortDescription: "L'huile aux notes de noisette grillée, pressée à partir des amandons d'argan.",
    description: "L'arganier ne pousse qu'au sud-ouest du Maroc. Les amandons de ses fruits sont torréfiés puis pressés pour donner une huile dorée au goût de noisette grillée.\n\nElle s'utilise crue : sur les salades, le couscous, les tajines en fin de cuisson, ou dans l'amlou avec les amandes et le miel.",
    originCountry: "Maroc",
    originRegion: "Souss",
    composition: "Huile vierge d'amandons d'argan torréfiés.",
    allergens: [],
    usageTips: "Utiliser crue, en filet sur un couscous, des légumes ou du pain chaud ; éviter de la chauffer pour garder son goût.",
    conservation: "À l'abri de la lumière et de la chaleur, bouteille bien fermée.",
    tags: ["huile", "Maroc", "argan"],
    amazon: { asin: "B07H516MRQ", label: "250 ml", priceCents: 4990 },
  },
  {
    slug: "citrons-beldi-confits",
    name: "Citrons beldi confits",
    category: "huiles",
    shortDescription: "Les citrons confits au sel, incontournables du tajine marocain.",
    description: "Le citron beldi est une petite variété marocaine à peau fine et parfumée. Confit dans le sel, il perd son acidité et prend un goût doux et intense.\n\nIl est indispensable au tajine de poulet aux olives, et relève aussi les salades, les poissons et les sauces.",
    originCountry: "Maroc",
    originRegion: null,
    composition: "Citrons beldi, sel, eau.",
    allergens: [],
    usageTips: "Rincer, retirer la pulpe si on la trouve trop salée, puis couper l'écorce en lanières et l'ajouter au tajine en fin de cuisson.",
    conservation: "Au frais une fois le pot ouvert, les citrons bien couverts de leur saumure.",
    tags: ["citron", "Maroc", "tajine"],
    amazon: { asin: "B07ZBZYJ7W", label: "300 g", priceCents: 1750 },
  },
  {
    slug: "harissa-artisanale",
    name: "Harissa artisanale",
    category: "epices",
    shortDescription: "La pâte de piment rouge tunisienne, piquante et parfumée au carvi.",
    description: "La harissa est une pâte de piments rouges séchés, pilés avec de l'ail, du sel et des épices comme le carvi et la coriandre, puis couverte d'huile.\n\nEn Tunisie, elle est partout : dans le couscous, la chakchouka, les sandwichs, ou simplement tartinée sur du pain avec de l'huile d'olive.",
    originCountry: "Tunisie",
    originRegion: null,
    composition: "Piments rouges, ail, épices, sel, huile.",
    allergens: [],
    usageTips: "Délayer une cuillère dans un peu de bouillon de couscous, ou la servir à part, arrosée d'huile d'olive.",
    conservation: "Au frais une fois le pot ouvert, recouverte d'un filet d'huile.",
    tags: ["piment", "Tunisie", "pâte"],
    amazon: { asin: "B0CPMDRB3T", label: "1 pot", priceCents: 1898 },
  },
  {
    slug: "marmite-en-aluminium",
    name: "Marmite en aluminium type caldero",
    category: "ustensiles",
    shortDescription: "Une marmite en aluminium épais pour le riz : thiéboudienne, jollof, riz gras.",
    description: "Sa fonte d'aluminium épaisse répartit bien la chaleur et forme au fond ce riz légèrement croustillant si recherché, le xoon au Sénégal.\n\nParfaite pour le thiéboudienne, le riz jollof ou le riz gras, elle sert aussi pour les ragoûts et les sauces.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Cuire le riz à feu doux, couvercle fermé, pour obtenir un fond doré. Laver à l'eau chaude savonneuse et bien sécher ; éviter le lave-vaisselle.",
    conservation: null,
    tags: ["marmite", "riz", "thiéboudienne"],
    amazon: { asin: "B00164U4G4", label: "2,5 l", priceCents: 4258 },
  },
  {
    slug: "marmite-potjie",
    name: "Marmite en fonte à trois pieds (potjie)",
    category: "ustensiles",
    shortDescription: "La marmite en fonte sud-africaine qui se pose directement sur les braises.",
    description: "Le potjie est une marmite ventrue en fonte, montée sur trois pieds, héritée des cuisines de plein air d'Afrique du Sud. Posée sur les braises, elle mijote lentement viande, légumes et épices.\n\nLe potjiekos, ragoût en couches cuit sans remuer, en est le plat emblématique ; elle convient aussi au mafé ou aux ragoûts cuits au feu de bois.",
    originCountry: "Afrique du Sud",
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Superposer viande, légumes et épices sans remuer et laisser mijoter doucement sur les braises. Après usage, laver à l'eau chaude, sécher au feu et huiler légèrement l'intérieur.",
    conservation: null,
    tags: ["fonte", "feu de bois", "Afrique du Sud"],
    amazon: { asin: "B0CZXS1ZHN", label: "1 pièce", priceCents: 5940 },
  },
  {
    slug: "mortier-en-granit",
    name: "Mortier et pilon en granit 14 cm",
    category: "ustensiles",
    shortDescription: "Un mortier lourd et stable pour écraser piment, ail et gingembre.",
    description: "Le granit, lourd et non poreux, écrase efficacement les aromates frais sans glisser. Ce mortier de taille moyenne est idéal pour les pâtes d'épices.\n\nOn y prépare la base ail-gingembre-piment des marinades, les pâtes de piment frais ou les mélanges d'épices en graines.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Écraser ail, gingembre, piment et oignon pour les marinades de poulet yassa ou de poisson braisé. Rincer à l'eau chaude et laisser sécher à l'air.",
    conservation: null,
    tags: ["mortier", "granit", "épices"],
    amazon: { asin: "B0BD8NMF5C", label: "14 cm", priceCents: 2899 },
  },
  {
    slug: "couscoussier",
    name: "Couscoussier inox",
    category: "ustensiles",
    shortDescription: "Le couscoussier pour cuire à la vapeur le fonio, le thiéré et l'attiéké.",
    description: "Le couscoussier associe une marmite et un panier percé qui s'emboîte au-dessus. La sauce ou l'eau mijote en bas pendant que la semoule cuit à la vapeur en haut.\n\nIl sert au couscous du Maghreb comme aux semoules d'Afrique de l'Ouest : fonio, thiéré de mil, attiéké.",
    originCountry: "Afrique du Nord",
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Humidifier la semoule, la cuire à la vapeur dans le panier, l'égrainer puis la remettre à cuire une seconde fois. Laver à l'eau chaude savonneuse et bien sécher.",
    conservation: null,
    tags: ["vapeur", "couscous", "fonio"],
    amazon: { asin: "B000VWV6QO", label: "1 pièce", priceCents: 3884 },
  },
  {
    slug: "faitout-en-fonte-d-aluminium",
    name: "Faitout en fonte d'aluminium 28 cm",
    category: "ustensiles",
    shortDescription: "Un grand faitout pour les mijotés : mafé, ndolé, yassa.",
    description: "La fonte d'aluminium chauffe vite et répartit la chaleur de façon homogène, sans être aussi lourde que la fonte de fer.\n\nC'est l'allié des plats qui mijotent longtemps : mafé, ndolé, yassa, sauces feuilles ou ragoûts.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Faire revenir oignons et viande à feu moyen, puis laisser mijoter à feu doux, couvercle posé. Laver à l'eau chaude avec une éponge non abrasive.",
    conservation: null,
    tags: ["faitout", "mijoté", "mafé"],
    amazon: { asin: "B075V8SPZ3", label: "28 cm", priceCents: 3990 },
  },
  {
    slug: "tamis-en-bois",
    name: "Tamis en bois 20 cm maille fine",
    category: "ustensiles",
    shortDescription: "Un tamis à maille fine pour les farines de teff, de foufou ou le fonio.",
    description: "Le tamis à cadre en bois est un outil classique des cuisines africaines pour affiner les farines et séparer les grains.\n\nIl sert à tamiser la farine de teff pour l'injera, les farines de foufou ou de maïs, et à égrainer le fonio ou le couscous de mil.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Tamiser la farine au-dessus d'un grand saladier en tapotant le cadre. Brosser à sec après usage et laisser sécher à l'air.",
    conservation: null,
    tags: ["tamis", "farine", "fonio"],
    amazon: { asin: "B08DHNY6D5", label: "20 cm", priceCents: 2290 },
  },
  {
    slug: "plaque-a-injera",
    name: "Plaque de cuisson électrique 30 cm",
    category: "ustensiles",
    shortDescription: "Une grande plaque électrique pour cuire l'injera et les crêpes.",
    description: "L'injera, la grande crêpe fermentée de teff d'Éthiopie et d'Érythrée, se cuit sur une large plaque bien chaude. Cette plaque électrique permet de la préparer à la maison.\n\nElle convient aussi aux crêpes de mil, aux galettes et aux crêpes sucrées.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Verser la pâte en spirale du bord vers le centre, couvrir et cuire sans retourner. Nettoyer à l'aide d'un chiffon humide une fois la plaque refroidie.",
    conservation: null,
    tags: ["injera", "crêpes", "Éthiopie"],
    amazon: { asin: "B0DD39QLC9", label: "30 cm", priceCents: 5278 },
  },
  {
    slug: "brochettes-en-metal",
    name: "Brochettes en métal 40 cm (lot de 30)",
    category: "ustensiles",
    shortDescription: "De longues brochettes métalliques pour le suya et les grillades.",
    description: "Le suya, la brochette épicée des rues du Nigeria, se grille sur de longues piques au-dessus des braises. Ces brochettes en métal réutilisables conviennent au barbecue comme au four.\n\nElles servent aussi aux dibi, aux brochettes de poisson ou de légumes.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Enfiler de fines lamelles de viande enrobées de yaji et griller au-dessus des braises. Laver à l'eau chaude savonneuse et bien sécher.",
    conservation: null,
    tags: ["brochettes", "suya", "grillade"],
    amazon: { asin: "B0GWY2YH3X", label: "30 × 40 cm", priceCents: 1899 },
  },
  {
    slug: "verres-a-the",
    name: "Verres à thé facettés 210 ml (lot de 6)",
    category: "ustensiles",
    shortDescription: "Les petits verres facettés de l'ataya et du thé à la menthe.",
    description: "Au Sénégal, en Mauritanie comme au Maroc, le thé se sert dans de petits verres facettés. On y fait passer le thé d'un verre à l'autre pour former la mousse.\n\nCe lot de six verres accompagne la théière pour les trois services de l'ataya.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Verser le thé de haut pour former une belle mousse. Laver à l'eau chaude savonneuse et essuyer pour garder la transparence.",
    conservation: null,
    tags: ["verres", "ataya", "thé"],
    amazon: { asin: "B0BWNVD37T", label: "6 × 210 ml", priceCents: 3959 },
  },
  {
    slug: "tajine-en-argile",
    name: "Tajine touareg en argile 30 cm",
    category: "ustensiles",
    shortDescription: "Le plat en terre à couvercle conique des mijotés d'Afrique du Nord.",
    description: "Le tajine est à la fois un plat de cuisson et de service : son couvercle conique renvoie la vapeur vers les aliments, qui cuisent doucement dans leur jus.\n\nIl sert aux tajines de poulet aux citrons confits, d'agneau aux pruneaux ou de légumes, et peut se poser sur la table.",
    originCountry: "Afrique du Nord",
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Cuire à feu doux, idéalement avec un diffuseur, en évitant les chocs de température. Laver à l'eau chaude sans détergent et laisser bien sécher.",
    conservation: null,
    tags: ["tajine", "argile", "Afrique du Nord"],
    amazon: { asin: "B0077C6XDC", label: "30 cm", priceCents: 5190 },
  },
  {
    slug: "theiere-a-ataya",
    name: "Théière marocaine inox 1,2 L",
    category: "ustensiles",
    shortDescription: "La théière à long bec pour le thé à la menthe et l'ataya.",
    description: "Sa forme ventrue et son bec verseur allongé permettent de servir le thé de haut pour former la mousse. On peut la poser directement sur le feu.\n\nElle est utilisée aussi bien pour le thé à la menthe marocain que pour l'ataya sénégalais.",
    originCountry: "Maroc",
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Faire bouillir le thé vert directement dans la théière, ajouter sucre et menthe, puis servir de haut. Rincer à l'eau chaude et bien sécher.",
    conservation: null,
    tags: ["théière", "ataya", "thé à la menthe"],
    amazon: { asin: "B0DJVCC3C6", label: "1,2 l", priceCents: 2999 },
  },
  {
    slug: "passoire-a-couscous",
    name: "Passoire à couscous 23 cm",
    category: "ustensiles",
    shortDescription: "Une passoire qui s'adapte sur une marmite pour cuire à la vapeur.",
    description: "Posée sur une marmite, cette passoire devient un panier vapeur pour le couscous, le fonio ou l'attiéké. Elle sert aussi simplement à égoutter.\n\nUne bonne solution pour cuire les semoules à la vapeur sans couscoussier dédié.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Poser sur une marmite de même diamètre et calfeutrer la jointure avec un torchon humide pour que la vapeur passe par la semoule. Laver à l'eau chaude savonneuse.",
    conservation: null,
    tags: ["vapeur", "passoire", "couscous"],
    amazon: { asin: "B07QQLZ5ML", label: "23 cm", priceCents: 2680 },
  },
  {
    slug: "rechaud-a-charbon-jiko",
    name: "Réchaud à charbon type jiko",
    category: "ustensiles",
    shortDescription: "Le réchaud à charbon kényan, pour cuisiner et griller sur les braises.",
    description: "Le jiko est le réchaud à charbon de bois des cuisines d'Afrique de l'Est. Ce modèle moderne concentre la chaleur des braises pour cuire, mijoter ou griller.\n\nIl convient aux grillades, au nyama choma, au maïs grillé et aux plats qui mijotent sur le feu.",
    originCountry: "Kenya",
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "À utiliser uniquement à l'extérieur ou dans un lieu très bien aéré. Vider les cendres une fois refroidies et brosser la grille.",
    conservation: null,
    tags: ["charbon", "grillade", "Kenya"],
    amazon: { asin: "B0BCXN4K59", label: "1 pièce", priceCents: 7500 },
  },
  {
    slug: "araignee-a-friture",
    name: "Araignée à friture 14 cm",
    category: "ustensiles",
    shortDescription: "L'écumoire pour sortir alloco, puff-puff et beignets de l'huile.",
    description: "Avec son large panier en fils métalliques, l'araignée permet de retirer les fritures de l'huile en les égouttant aussitôt.\n\nIndispensable pour l'alloco, les puff-puff, les accras de haricots ou les beignets de banane.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Retourner et sortir les beignets de l'huile chaude, puis les poser sur du papier absorbant. Laver à l'eau chaude savonneuse et bien sécher.",
    conservation: null,
    tags: ["friture", "beignets", "alloco"],
    amazon: { asin: "B001FWQ5DS", label: "14 cm", priceCents: 2545 },
  },
  {
    slug: "spatules-en-bois",
    name: "Spatules en bois (lot de 8)",
    category: "ustensiles",
    shortDescription: "Des spatules solides pour tourner le tô, le foufou et les sauces.",
    description: "Tourner une pâte de tô, de foufou ou d'amala demande un ustensile solide qui ne rayera pas la marmite. Ce lot de spatules en bois couvre tous les usages.\n\nElles servent aussi pour remuer les sauces, le riz et les mijotés.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Tourner vivement la pâte contre la paroi de la marmite pour la rendre lisse. Laver à la main, bien sécher et huiler de temps en temps.",
    conservation: null,
    tags: ["spatules", "bois", "foufou"],
    amazon: { asin: "B006677VQ2", label: "lot de 8", priceCents: 860 },
  },
  {
    slug: "saladier-en-bois",
    name: "Grand saladier en bois d'acacia 26 cm",
    category: "ustensiles",
    shortDescription: "Un grand plat en bois pour le service et le plat commun.",
    description: "Dans de nombreuses cuisines africaines, on partage le repas autour d'un plat commun. Ce grand saladier en acacia s'y prête bien, tout comme au service des salades et des fruits.\n\nIl met en valeur le thiakry, l'attiéké ou une salade d'avocat.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Servir le plat commun ou une salade ; éviter les liquides très chauds. Laver rapidement à la main, sécher et huiler de temps en temps.",
    conservation: null,
    tags: ["saladier", "bois", "service"],
    amazon: { asin: "B004IZ20MO", label: "26 cm", priceCents: 3131 },
  },
  {
    slug: "bouilloire-emaillee",
    name: "Bouilloire émaillée 2,4 L",
    category: "ustensiles",
    shortDescription: "Une bouilloire émaillée pour l'eau chaude, le thé et les infusions.",
    description: "Les bouilloires émaillées colorées font partie du paysage de nombreuses cuisines africaines. Posée directement sur le feu, elle chauffe l'eau du thé et des infusions.\n\nElle convient pour préparer le kinkeliba, le thé à la menthe ou le café Touba.",
    originCountry: null,
    originRegion: null,
    composition: null,
    allergens: [],
    usageTips: "Chauffer sur le feu à flamme moyenne, sans la laisser à vide. Rincer et sécher après usage ; éviter les éponges abrasives sur l'émail.",
    conservation: null,
    tags: ["bouilloire", "thé", "émail"],
    amazon: { asin: "B08LKKM6C9", label: "2,4 l", priceCents: 3499 },
  },
  {
    slug: "feuilles-de-bananier-fraiches",
    name: "Feuilles de bananier fraîches (lot de 100)",
    category: "ustensiles",
    shortDescription: "Les grandes feuilles pour envelopper le koki, le liboké et les papillotes.",
    description: "En Afrique centrale et de l'Ouest, la feuille de bananier sert d'emballage de cuisson : elle protège les aliments et leur donne un léger parfum végétal.\n\nOn l'utilise pour le koki de haricots, le liboké de poisson, les papillotes et pour tapisser le fond des marmites.",
    originCountry: null,
    originRegion: null,
    composition: "Feuilles de bananier fraîches.",
    allergens: [],
    usageTips: "Passer rapidement les feuilles au-dessus d'une flamme ou dans l'eau chaude pour les assouplir, puis y envelopper la préparation et ficeler.",
    conservation: "Au frais, enveloppées ; se conservent aussi au congélateur.",
    tags: ["bananier", "papillote", "koki"],
    amazon: { asin: "B0D2H42WZ2", label: "100 feuilles", priceCents: 3155 },
  },
  {
    slug: "cafe-du-kivu",
    name: "Café moulu du Kivu (RD Congo)",
    category: "cafes-thes",
    shortDescription: "Un arabica des rives du lac Kivu, rond et fruité.",
    description: "Autour du lac Kivu, à l'est de la RD Congo, les caféiers poussent en altitude sur des sols volcaniques. Le café qui en est issu est rond, avec des notes fruitées et une belle douceur.\n\nMoulu, il convient à la cafetière filtre et à la cafetière italienne.",
    originCountry: "RD Congo",
    originRegion: "Kivu",
    composition: "Café arabica torréfié et moulu.",
    allergens: [],
    usageTips: "Préparer au filtre ou à la cafetière italienne ; bien refermer le paquet après chaque usage.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "RD Congo", "arabica"],
    amazon: { asin: "B074ZLR7JD", label: "250 g moulu", priceCents: 804 },
  },
  {
    slug: "cafe-vert-du-cameroun",
    name: "Café vert du Cameroun à torréfier",
    category: "cafes-thes",
    shortDescription: "Des grains de café vert pour torréfier soi-même, comme à la maison au Cameroun.",
    description: "Dans l'Ouest du Cameroun, de nombreuses familles torréfient encore leur café à la poêle. Ces grains verts, non torréfiés, permettent de retrouver ce geste et de choisir son degré de torréfaction.\n\nUne fois grillés, ils se moulent et se préparent comme n'importe quel café.",
    originCountry: "Cameroun",
    originRegion: null,
    composition: "Grains de café vert non torréfiés.",
    allergens: [],
    usageTips: "Torréfier par petites quantités à la poêle épaisse, en remuant sans cesse jusqu'à la couleur souhaitée, puis laisser reposer avant de moudre.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café vert", "Cameroun", "torréfaction"],
    amazon: { asin: "B0FJH3F4D4", label: "1 kg vert", priceCents: 2479 },
  },
  {
    slug: "cafe-moka-sidamo",
    name: "Café moulu Moka Sidamo",
    category: "cafes-thes",
    shortDescription: "Un moka éthiopien de la région de Sidamo, floral et fruité.",
    description: "L'Éthiopie est le berceau de l'arabica. Dans la région de Sidamo, au sud du pays, le café pousse en altitude et offre une tasse florale, fruitée et délicate.\n\nMoulu, il se prépare au filtre et peut accompagner une cérémonie du café à la maison.",
    originCountry: "Éthiopie",
    originRegion: "Sidamo",
    composition: "Café arabica torréfié et moulu.",
    allergens: [],
    usageTips: "Préparer au filtre ou à la cafetière à piston ; en Éthiopie, on le sert parfois avec une pincée de sel ou de cardamome.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Éthiopie", "moka"],
    amazon: { asin: "B01BSY1IDO", label: "500 g moulu", priceCents: 2029 },
  },
  {
    slug: "cafe-du-kenya",
    name: "Café en grains du Kenya",
    category: "cafes-thes",
    shortDescription: "Un arabica kényan en grains, vif et fruité.",
    description: "Les cafés du Kenya poussent sur les hauts plateaux, au pied du mont Kenya. Ils sont réputés pour leur acidité vive et leurs notes de fruits rouges et d'agrumes.\n\nEn grains, ils gardent tout leur parfum jusqu'à la mouture.",
    originCountry: "Kenya",
    originRegion: null,
    composition: "Café arabica torréfié en grains.",
    allergens: [],
    usageTips: "Moudre juste avant la préparation, plutôt grossièrement pour la cafetière à piston ou le filtre.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Kenya", "grains"],
    amazon: { asin: "B0FHBR3X7S", label: "1 kg grains", priceCents: 4139 },
  },
  {
    slug: "cafe-harrar",
    name: "Café en grains Éthiopie Harrar",
    category: "cafes-thes",
    shortDescription: "Un café éthiopien de l'est du pays, aux notes fruitées et chocolatées.",
    description: "La région de Harrar, à l'est de l'Éthiopie, produit un café séché dans son fruit, au soleil. Il en ressort une tasse corsée, fruitée, avec des notes de cacao.\n\nC'est l'un des cafés les plus typés d'Éthiopie.",
    originCountry: "Éthiopie",
    originRegion: "Harrar",
    composition: "Café arabica torréfié en grains.",
    allergens: [],
    usageTips: "Moudre juste avant la préparation ; il convient particulièrement à la cafetière italienne et à l'expresso.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Éthiopie", "grains"],
    amazon: { asin: "B0FJHDJKKX", label: "1 kg grains", priceCents: 4651 },
  },
  {
    slug: "cafe-yirgacheffe",
    name: "Café en grains Yirgacheffe",
    category: "cafes-thes",
    shortDescription: "Un café éthiopien floral et citronné, de la région de Yirgacheffe.",
    description: "Yirgacheffe, dans le sud de l'Éthiopie, est l'une des régions de café les plus réputées au monde. Ses cafés lavés offrent une tasse légère, aux notes de fleurs blanches et d'agrumes.\n\nUn café à découvrir de préférence en méthode douce.",
    originCountry: "Éthiopie",
    originRegion: "Yirgacheffe",
    composition: "Café arabica torréfié en grains.",
    allergens: [],
    usageTips: "Moudre juste avant la préparation et préparer au filtre ou à la cafetière à piston pour garder ses arômes délicats.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Éthiopie", "floral"],
    amazon: { asin: "B0CCYFVSTV", label: "250 g grains", priceCents: 4200 },
  },
  {
    slug: "cafe-du-cameroun",
    name: "Café en grains du Cameroun (Bamoun)",
    category: "cafes-thes",
    shortDescription: "Un arabica des hauts plateaux de l'Ouest camerounais.",
    description: "Le pays Bamoun, dans l'Ouest du Cameroun, cultive l'arabica sur des terres d'altitude. Il donne un café équilibré, avec du corps et des notes chocolatées.\n\nEn grains, il se moud selon la méthode de préparation choisie.",
    originCountry: "Cameroun",
    originRegion: "Pays Bamoun (Ouest)",
    composition: "Café arabica torréfié en grains.",
    allergens: [],
    usageTips: "Moudre juste avant la préparation, finement pour l'expresso ou plus grossièrement pour le filtre.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Cameroun", "grains"],
    amazon: { asin: "B0FH5L1QC3", label: "1 kg grains", priceCents: 3468 },
  },
  {
    slug: "cafe-du-rwanda",
    name: "Café en grains du Rwanda",
    category: "cafes-thes",
    shortDescription: "Un café du Pays des mille collines, doux et fruité.",
    description: "Au Rwanda, le café pousse sur les collines, en altitude, et est cueilli par de petits producteurs. Il offre une tasse douce, fruitée et sucrée.\n\nEn grains, il garde ses arômes jusqu'à la mouture.",
    originCountry: "Rwanda",
    originRegion: null,
    composition: "Café arabica torréfié en grains.",
    allergens: [],
    usageTips: "Moudre juste avant la préparation ; il se prête à toutes les méthodes, du filtre à l'expresso.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Rwanda", "grains"],
    amazon: { asin: "B08HZ9X7VG", label: "1 kg grains", priceCents: 4033 },
  },
  {
    slug: "cafe-d-ethiopie-bio",
    name: "Café en grains d'Éthiopie bio et équitable",
    category: "cafes-thes",
    shortDescription: "Un arabica éthiopien issu de l'agriculture biologique et du commerce équitable.",
    description: "Ce café éthiopien vient de coopératives de petits producteurs. Il offre les notes florales et fruitées typiques des cafés d'Éthiopie.\n\nEn grains, il se moud selon la préparation choisie : filtre, piston ou expresso.",
    originCountry: "Éthiopie",
    originRegion: null,
    composition: "Café arabica issu de l'agriculture biologique, torréfié en grains.",
    allergens: [],
    usageTips: "Moudre juste avant la préparation pour garder les arômes ; bien refermer le paquet après chaque usage.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Éthiopie", "bio"],
    amazon: { asin: "B08ZT3P8TH", label: "500 g grains", priceCents: 1233 },
  },
  {
    slug: "cafe-de-tanzanie",
    name: "Café en grains de Tanzanie",
    category: "cafes-thes",
    shortDescription: "Un café d'Afrique de l'Est, vif et équilibré.",
    description: "La Tanzanie cultive le café sur les pentes de ses montagnes, notamment autour du Kilimandjaro. Ses cafés sont vifs, équilibrés, avec des notes fruitées.\n\nEn grains, ils se moulent au moment de la préparation.",
    originCountry: "Tanzanie",
    originRegion: null,
    composition: "Café torréfié en grains.",
    allergens: [],
    usageTips: "Moudre juste avant la préparation ; il convient bien au filtre et à la cafetière à piston.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Tanzanie", "grains"],
    amazon: { asin: "B00EC7AGCE", label: "1 kg grains", priceCents: 2999 },
  },
  {
    slug: "cafe-du-burundi",
    name: "Café en grains du Burundi",
    category: "cafes-thes",
    shortDescription: "Un café du cœur de l'Afrique des Grands Lacs, sucré et fruité.",
    description: "Au Burundi, le café est cultivé en altitude par de petits producteurs sur les collines. Il donne une tasse sucrée et fruitée, à l'acidité douce.\n\nEn grains, il se moud selon la méthode choisie.",
    originCountry: "Burundi",
    originRegion: null,
    composition: "Café arabica torréfié en grains.",
    allergens: [],
    usageTips: "Moudre juste avant la préparation ; il se prête à toutes les méthodes, du filtre à l'expresso.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["café", "Burundi", "grains"],
    amazon: { asin: "B08HVPHG6Z", label: "1 kg grains", priceCents: 4039 },
  },
  {
    slug: "rooibos-vert",
    name: "Rooibos vert bio",
    category: "cafes-thes",
    shortDescription: "Le rooibos non fermenté, au goût plus végétal et plus léger.",
    description: "Le rooibos pousse uniquement dans la région du Cederberg, en Afrique du Sud. Dans sa version verte, les feuilles sont séchées sans fermentation : l'infusion est plus claire, avec un goût végétal et légèrement miellé.\n\nIl se boit chaud ou glacé.",
    originCountry: "Afrique du Sud",
    originRegion: "Cederberg",
    composition: "Feuilles de rooibos (Aspalathus linearis) non fermentées, séchées, issues de l'agriculture biologique.",
    allergens: [],
    usageTips: "Infuser dans l'eau chaude, juste avant l'ébullition, puis filtrer. Se boit nature, ou glacé avec un zeste d'orange.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["rooibos", "Afrique du Sud", "infusion"],
    amazon: { asin: "B0D4F4GV8M", label: "200 g", priceCents: 1199 },
  },
  {
    slug: "the-vert-gunpowder",
    name: "Thé vert gunpowder pour ataya",
    category: "cafes-thes",
    shortDescription: "Le thé vert roulé en perles, base de l'ataya et du thé à la menthe.",
    description: "Le gunpowder est un thé vert chinois dont les feuilles sont roulées en petites perles. Il est devenu le thé de référence en Afrique de l'Ouest et au Maghreb.\n\nAu Sénégal, il sert à préparer l'ataya, servi en trois verres de plus en plus sucrés, en prenant le temps de faire la mousse.",
    originCountry: "Chine",
    originRegion: null,
    composition: "Thé vert gunpowder.",
    allergens: [],
    usageTips: "Faire bouillir le thé dans la théière, ajouter sucre et menthe, puis transvaser d'un verre à l'autre pour former la mousse.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["thé vert", "ataya", "Sénégal"],
    amazon: { asin: "B09W1JV9RN", label: "200 g", priceCents: 999 },
  },
  {
    slug: "kinkeliba",
    name: "Feuilles de kinkeliba",
    category: "cafes-thes",
    shortDescription: "Les feuilles de la boisson du petit-déjeuner au Sénégal.",
    description: "Le kinkeliba est un arbuste du Sahel dont on infuse les feuilles séchées. Il donne une boisson ambrée au goût boisé et légèrement amer.\n\nAu Sénégal, on le boit le matin, souvent sucré, avec du pain, et il est très présent au moment du ramadan.",
    originCountry: "Sénégal",
    originRegion: null,
    composition: "Feuilles de kinkeliba (Combretum micranthum) séchées.",
    allergens: [],
    usageTips: "Faire bouillir les feuilles quelques minutes dans l'eau, filtrer puis sucrer ; on peut ajouter une feuille de menthe.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["kinkeliba", "Sénégal", "infusion"],
    amazon: { asin: "B07NLH2LG5", label: "50 g", priceCents: 889 },
  },
  {
    slug: "rooibos",
    name: "Rooibos bio en vrac",
    category: "cafes-thes",
    shortDescription: "L'infusion rouge d'Afrique du Sud, ronde et douce.",
    description: "Le rooibos est un arbuste qui ne pousse que dans la région du Cederberg, en Afrique du Sud. Ses feuilles fermentées puis séchées donnent une infusion rouge ambré, au goût doux et légèrement vanillé.\n\nIl se boit à toute heure, chaud ou glacé, nature ou avec un nuage de lait.",
    originCountry: "Afrique du Sud",
    originRegion: "Cederberg",
    composition: "Feuilles de rooibos (Aspalathus linearis) séchées, issues de l'agriculture biologique.",
    allergens: [],
    usageTips: "Infuser dans l'eau bouillante, puis filtrer. En Afrique du Sud, on le boit souvent avec du lait et du miel.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["rooibos", "Afrique du Sud", "infusion"],
    amazon: { asin: "B07RL8GZCJ", label: "200 g", priceCents: 927 },
  },
  {
    slug: "honeybush",
    name: "Honeybush bio",
    category: "cafes-thes",
    shortDescription: "L'infusion sud-africaine aux notes de miel, cousine du rooibos.",
    description: "Le honeybush pousse dans les montagnes du Cap, en Afrique du Sud. Ses fleurs dégagent un parfum de miel qui lui a donné son nom, et ses feuilles donnent une infusion douce et fruitée.\n\nIl se boit chaud ou glacé.",
    originCountry: "Afrique du Sud",
    originRegion: null,
    composition: "Feuilles et tiges de honeybush (Cyclopia) séchées, issues de l'agriculture biologique.",
    allergens: [],
    usageTips: "Infuser dans l'eau bouillante, puis filtrer ; délicieux glacé avec quelques tranches de pêche.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["honeybush", "Afrique du Sud", "infusion"],
    amazon: { asin: "B082YD6S9H", label: "100 g", priceCents: 1440 },
  },
  {
    slug: "citronnelle-sechee",
    name: "Citronnelle séchée",
    category: "cafes-thes",
    shortDescription: "Des tiges et feuilles de citronnelle pour les infusions et les bouillons.",
    description: "La citronnelle pousse dans de nombreuses cours d'Afrique de l'Ouest, où on l'appelle parfois « beurre de chèvre » ou « thé de Gambie ». Ses feuilles séchées ont un parfum frais et citronné.\n\nOn l'infuse seule ou avec du kinkeliba et de la menthe, et elle parfume aussi les bouillons et les marinades de poisson.",
    originCountry: null,
    originRegion: null,
    composition: "Citronnelle (Cymbopogon citratus) séchée.",
    allergens: [],
    usageTips: "Infuser une poignée dans l'eau bouillante, sucrer à son goût ; ou en glisser quelques brins dans un bouillon de poisson.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["citronnelle", "infusion", "Afrique de l'Ouest"],
    amazon: { asin: "B0D8WT28DC", label: "300 g", priceCents: 1295 },
  },
  {
    slug: "the-noir-du-kenya",
    name: "Thé noir du Kenya",
    category: "cafes-thes",
    shortDescription: "Un thé noir corsé, à la couleur intense, comme on le boit en Afrique de l'Est.",
    description: "Le Kenya est l'un des grands producteurs de thé noir au monde. Ses thés, cultivés sur les hauts plateaux, sont corsés et donnent une infusion très colorée.\n\nAu Kenya, il se prépare en chai : bouilli avec du lait, du sucre et parfois des épices.",
    originCountry: "Kenya",
    originRegion: null,
    composition: "Thé noir, en sachets.",
    allergens: [],
    usageTips: "Pour un chai à la kényane, faire bouillir le thé dans un mélange d'eau et de lait, sucrer puis filtrer.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["thé noir", "Kenya", "chai"],
    amazon: { asin: "B0G53GB1T9", label: "boîte de sachets", priceCents: 747 },
  },
  {
    slug: "the-noir-du-kenya-cardamome",
    name: "Thé noir à la cardamome",
    category: "cafes-thes",
    shortDescription: "Un thé noir corsé parfumé à la cardamome, pour un chai épicé.",
    description: "La cardamome parfume le thé dans toute l'Afrique de l'Est, de Mombasa à Zanzibar. Ce thé noir corsé est déjà aromatisé : il suffit de l'infuser.\n\nIl se boit nature ou préparé en chai, bouilli avec du lait et du sucre.",
    originCountry: "Kenya",
    originRegion: null,
    composition: "Thé noir, cardamome.",
    allergens: [],
    usageTips: "Faire bouillir le sachet dans un mélange d'eau et de lait, sucrer et ajouter une pincée de gingembre pour un chai plus relevé.",
    conservation: "Au sec, à l'abri de la lumière, dans un contenant fermé.",
    tags: ["thé noir", "cardamome", "chai"],
    amazon: { asin: "B00GRS0BUI", label: "boîte de sachets", priceCents: 749 },
  },
];
