/** Recettes ajoutées le 1er octobre 2026 (Nigeria, Ghana, Cameroun, Kenya, Ouganda). */
import type { RecipeSeed } from "./recipe-seed";

const added = "2026-10-01T08:00:00.000Z";

export const recipesNouvelles: RecipeSeed[] = [
  // ---------------------------------------------------------- Akara
  {
    slug: "akara",
    name: "Akara",
    countryCode: "NG",
    region: "Pays yoruba",
    course: "accompagnements",
    shortDescription: "Beignets de niébé mixé avec oignon et piment, croustillants dehors et moelleux dedans.",
    story:
      "L'akara est le beignet de haricots cornille (niébé) du Nigeria, cuisiné partout dans le pays et surtout en pays yoruba. On l'achète le matin au bord des routes, tout juste sorti de l'huile, et on le mange avec de la bouillie de maïs (ogi ou pap) ou glissé dans un morceau de pain.\n\nLe même beignet se retrouve sous d'autres noms sur toute la côte, du Ghana au Bénin, et il a voyagé jusqu'au Brésil, où il est devenu l'acarajé de Bahia.",
    prepMinutes: 30,
    cookMinutes: 20,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [500, "g", "haricots cornille (niébé) secs"],
      [1, null, "oignon"],
      [2, null, "piments scotch bonnet"],
      [1, "c. à café", "sel"],
      [1, "l", "huile de friture"],
    ],
    steps: [
      "Faire tremper les haricots au moins 4 heures dans un grand volume d'eau froide.",
      "Frotter les haricots entre les mains dans l'eau pour détacher les peaux, laisser les peaux remonter à la surface et les jeter. Recommencer jusqu'à ce que les haricots soient bien blancs.",
      "Mixer les haricots avec l'oignon, les piments et un tout petit peu d'eau jusqu'à obtenir une pâte épaisse et lisse.",
      "Fouetter la pâte 5 minutes à la cuillère en bois pour l'aérer, puis saler juste avant la cuisson.",
      "Faire chauffer l'huile dans une marmite profonde. Déposer la pâte par cuillerées et frire 3 à 4 minutes en retournant, jusqu'à ce que les beignets soient bien dorés.",
      "Égoutter sur du papier absorbant et servir chaud.",
    ],
    tips: [
      "Ajoutez le moins d'eau possible au mixage : une pâte trop liquide s'étale dans l'huile et les beignets ne gonflent pas.",
      "Battre la pâte avant la cuisson est le secret d'un akara léger et moelleux.",
    ],
    tags: ["beignets", "niébé", "petit-déjeuner"],
    equipment: ["araignee-a-friture"],
    featured: false,
    createdAt: added,
  },
  // ---------------------------------------------------------- Pepper soup
  {
    slug: "pepper-soup",
    name: "Pepper soup de chèvre",
    countryCode: "NG",
    region: "Sud du Nigeria",
    course: "mijotes",
    shortDescription: "Bouillon clair et très parfumé à la chèvre, relevé de piment, de poivre de Selim et de pèbè.",
    story:
      "La pepper soup est le bouillon épicé du Nigeria. On la prépare avec de la chèvre, du poisson-chat ou du poulet, et l'on y met un mélange d'épices locales : poivre de Selim (uda), pèbè (ehuru) et piment, souvent complétés de feuilles de basilic africain.\n\nElle se sert dans les bars en plein air, les « spots », avec une boisson fraîche, mais aussi à la maison les soirs de pluie et lors des grandes fêtes de famille.",
    prepMinutes: 15,
    cookMinutes: 75,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [1, "kg", "viande de chèvre en morceaux"],
      [1, null, "oignon"],
      [2, null, "piments scotch bonnet"],
      [4, "gousses", "poivre de Selim", "poivre-de-selim"],
      [1, "c. à café", "pèbè moulu", "pebe-moulu"],
      [1, null, "cube de bouillon"],
      [1, "botte", "basilic africain (ou basilic thaï)"],
      [1.5, "l", "eau"],
      [null, null, "sel"],
    ],
    steps: [
      "Rincer la viande, la mettre dans une marmite avec l'oignon émincé, le cube de bouillon et une pincée de sel. Couvrir et laisser rendre son jus 10 minutes à feu moyen.",
      "Faire griller les gousses de poivre de Selim à sec dans une poêle, retirer les graines dures puis piler les gousses.",
      "Verser l'eau sur la viande, ajouter le poivre de Selim, le pèbè et les piments mixés. Porter à ébullition.",
      "Laisser mijoter à couvert 1 heure, jusqu'à ce que la viande soit tendre.",
      "Ajouter les feuilles de basilic ciselées 5 minutes avant la fin, rectifier l'assaisonnement et servir très chaud.",
    ],
    tips: [
      "Remplacez la chèvre par du poisson-chat en tronçons : comptez alors seulement 15 minutes de cuisson.",
      "Servez avec de l'igname bouillie ou du plantain pour un repas complet.",
    ],
    tags: ["soupe", "épicé", "chèvre"],
    equipment: ["marmite-en-aluminium"],
    featured: false,
    createdAt: added,
  },
  // ---------------------------------------------------------- Groundnut soup
  {
    slug: "groundnut-soup",
    name: "Groundnut soup",
    countryCode: "GH",
    region: "Ashanti et Nord du Ghana",
    course: "mijotes",
    shortDescription: "Soupe ghanéenne au poulet et à la pâte d'arachide, tomate et piment, servie avec du fufu ou des boulettes de riz.",
    story:
      "La groundnut soup, ou nkate nkwan en twi, est l'une des grandes soupes du Ghana. Plus fluide que le mafé d'Afrique de l'Ouest sahélienne, elle se prépare en délayant la pâte d'arachide dans un bouillon de poulet parfumé à la tomate, au gingembre et au piment.\n\nLe dimanche, on la sert avec du fufu pilé ou de l'omo tuo, des boulettes de riz bien collant que l'on trempe dans la soupe.",
    prepMinutes: 20,
    cookMinutes: 60,
    servings: 6,
    difficulty: 1,
    ingredients: [
      [1.2, "kg", "poulet découpé en morceaux"],
      [250, "g", "pâte d'arachide", "pate-d-arachide"],
      [2, null, "oignons"],
      [4, null, "tomates"],
      [2, "c. à soupe", "concentré de tomate"],
      [1, "morceau", "gingembre frais (3 cm)"],
      [3, "gousses", "ail"],
      [1, null, "piment scotch bonnet"],
      [1.5, "l", "eau"],
      [null, null, "sel"],
    ],
    steps: [
      "Mixer un oignon, le gingembre et l'ail. Frotter le poulet avec ce mélange, saler et laisser reposer 15 minutes.",
      "Mettre le poulet dans une marmite avec 25 cl d'eau, couvrir et cuire 15 minutes à feu moyen.",
      "Pendant ce temps, faire cuire les tomates, le second oignon et le piment entiers dans un peu d'eau 10 minutes, puis les mixer finement.",
      "Délayer la pâte d'arachide avec une louche d'eau chaude jusqu'à obtenir une crème lisse.",
      "Ajouter au poulet la purée de tomates, le concentré, la crème d'arachide et le reste de l'eau. Bien mélanger.",
      "Laisser mijoter 40 minutes à feu doux en remuant de temps en temps, jusqu'à ce que l'huile de l'arachide remonte à la surface. Rectifier l'assaisonnement.",
    ],
    tips: [
      "La soupe épaissit en refroidissant : allongez-la d'un peu d'eau chaude au moment de réchauffer.",
      "Choisissez une pâte d'arachide pure, faite uniquement d'arachides grillées.",
    ],
    tags: ["soupe", "arachide", "poulet"],
    featured: false,
    createdAt: added,
  },
  // ---------------------------------------------------------- Mbongo tchobi
  {
    slug: "mbongo-tchobi",
    name: "Mbongo tchobi",
    countryCode: "CM",
    region: "Pays bassa, Littoral",
    course: "mijotes",
    shortDescription: "Poisson mijoté dans une sauce noire aux épices grillées (mbongo), au pèbè et au piment.",
    story:
      "Le mbongo tchobi est un plat du peuple bassa, dans la région du Littoral au Cameroun. Sa couleur presque noire vient du mbongo, un mélange d'épices que l'on fait griller jusqu'à les noircir avant de les piler : il donne à la sauce un goût fumé et profond, sans amertume.\n\nOn le prépare surtout avec du poisson frais, parfois avec de la viande, et on le sert avec du plantain vapeur, du manioc ou des bâtons de manioc.",
    prepMinutes: 25,
    cookMinutes: 40,
    servings: 4,
    difficulty: 2,
    ingredients: [
      [1.2, "kg", "poisson frais (bar, carpe ou mâchoiron) en tronçons"],
      [3, "c. à soupe", "mbongo (épices grillées et pilées)"],
      [1, "c. à café", "pèbè moulu", "pebe-moulu"],
      [3, null, "tomates"],
      [2, null, "oignons"],
      [3, "gousses", "ail"],
      [1, "morceau", "gingembre frais (3 cm)"],
      [1, null, "piment frais"],
      [5, "cl", "huile de palme rouge", "huile-de-palme-rouge"],
      [50, "cl", "eau"],
      [null, null, "sel"],
    ],
    steps: [
      "Nettoyer le poisson, le saler et le réserver au frais.",
      "Si le mbongo est en graines, le faire griller à sec dans une poêle jusqu'à ce qu'il noircisse, puis le piler finement.",
      "Mixer les tomates, les oignons, l'ail, le gingembre et le piment avec le mbongo et le pèbè.",
      "Faire chauffer l'huile de palme dans une marmite, y verser la préparation mixée et cuire 15 minutes en remuant, jusqu'à ce que la sauce épaississe.",
      "Ajouter l'eau, porter à frémissement, puis déposer délicatement les morceaux de poisson.",
      "Couvrir et laisser mijoter 15 à 20 minutes à feu doux sans remuer, en secouant simplement la marmite pour ne pas briser le poisson. Rectifier l'assaisonnement.",
    ],
    tips: [
      "Ne remuez pas à la cuillère après avoir mis le poisson : il se défait vite.",
      "Servez avec du plantain cuit à la vapeur, l'accompagnement le plus courant au Cameroun.",
    ],
    tags: ["poisson", "épices", "sauce"],
    equipment: ["marmite-en-aluminium"],
    featured: false,
    createdAt: added,
  },
  // ---------------------------------------------------------- Nyama choma
  {
    slug: "nyama-choma",
    name: "Nyama choma et kachumbari",
    countryCode: "KE",
    region: "Nairobi",
    course: "grillades",
    shortDescription: "Chèvre grillée lentement sur la braise, servie avec le kachumbari, salade fraîche de tomate et d'oignon.",
    story:
      "Nyama choma veut dire « viande grillée » en swahili. Au Kenya, c'est le repas de fête et de week-end par excellence : on choisit son morceau de chèvre ou de bœuf au comptoir, il est grillé lentement sur la braise, puis découpé en petits morceaux sur une planche en bois.\n\nIl est toujours accompagné de kachumbari, une salade de tomates, d'oignon rouge et de coriandre au citron vert, et souvent d'ugali, la pâte de maïs blanc.",
    prepMinutes: 20,
    cookMinutes: 60,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [1.2, "kg", "côtes ou gigot de chèvre (ou d'agneau)"],
      [3, null, "tomates"],
      [1, null, "oignon rouge"],
      [1, "botte", "coriandre fraîche"],
      [2, null, "citrons verts"],
      [1, null, "piment vert"],
      [null, null, "sel"],
      [null, null, "poivre noir"],
    ],
    steps: [
      "Sortir la viande du réfrigérateur 30 minutes avant la cuisson, la saler et la poivrer généreusement.",
      "Allumer le barbecue et attendre que les braises soient bien blanches, sans flammes.",
      "Griller la viande à bonne distance des braises pendant 50 minutes à 1 heure, en la retournant régulièrement, jusqu'à ce qu'elle soit bien dorée à l'extérieur et cuite à cœur.",
      "Pendant la cuisson, préparer le kachumbari : couper les tomates en petits dés, émincer finement l'oignon rouge et le piment, ciseler la coriandre.",
      "Mélanger le tout avec le jus des citrons verts et une pincée de sel.",
      "Laisser reposer la viande 5 minutes, la découper en petits morceaux et servir avec le kachumbari.",
    ],
    tips: [
      "Faites tremper l'oignon émincé 5 minutes dans l'eau froide : il sera plus doux dans le kachumbari.",
      "La cuisson lente, loin des braises, est la clé d'une viande tendre et bien grillée.",
    ],
    tags: ["grillade", "barbecue", "chèvre"],
    equipment: ["rechaud-a-charbon-jiko"],
    featured: false,
    createdAt: added,
  },
  // ---------------------------------------------------------- Matoké
  {
    slug: "matoke",
    name: "Matoké au bœuf",
    countryCode: "UG",
    region: "Buganda",
    course: "mijotes",
    shortDescription: "Bananes vertes à cuire mijotées avec du bœuf, de la tomate et des oignons : le plat de tous les jours en Ouganda.",
    story:
      "Le matoké est une banane verte à cuire, peu sucrée, cultivée en abondance autour du lac Victoria. En Ouganda, et surtout au Buganda, le mot désigne aussi le repas lui-même : il est servi presque tous les jours, et l'on dit souvent qu'un repas sans matoké n'est pas un vrai repas.\n\nTraditionnellement, on le cuit à la vapeur dans des feuilles de bananier avant de l'écraser en purée. Cette version mijotée au bœuf, très courante dans les familles d'Ouganda et du Kenya voisin, cuit les bananes directement dans la sauce.",
    prepMinutes: 25,
    cookMinutes: 60,
    servings: 6,
    difficulty: 1,
    ingredients: [
      [1.5, "kg", "bananes vertes à cuire (matoké) épluchées"],
      [600, "g", "bœuf à braiser en cubes"],
      [2, null, "oignons"],
      [4, null, "tomates"],
      [1, null, "poivron vert"],
      [3, "gousses", "ail"],
      [1, "c. à soupe", "curry en poudre"],
      [4, "c. à soupe", "huile végétale"],
      [1, null, "cube de bouillon"],
      [1, "l", "eau"],
      [1, "botte", "coriandre fraîche"],
      [null, null, "sel"],
    ],
    steps: [
      "Huiler ses mains, éplucher les bananes vertes et les couper en tronçons. Les plonger au fur et à mesure dans de l'eau citronnée.",
      "Dans une marmite, faire dorer le bœuf dans l'huile chaude, puis ajouter les oignons émincés et l'ail haché.",
      "Ajouter les tomates coupées en dés, le poivron, le curry et le cube de bouillon émietté. Cuire 10 minutes.",
      "Verser l'eau, couvrir et laisser mijoter 30 minutes.",
      "Ajouter les bananes égouttées, couvrir et cuire encore 20 à 25 minutes, jusqu'à ce qu'elles soient tendres et que la sauce ait épaissi.",
      "Parsemer de coriandre ciselée et servir.",
    ],
    tips: [
      "Huilez vos mains ou portez des gants pour éplucher les bananes vertes : leur sève tache et colle.",
      "À défaut de matoké, utilisez des plantains bien verts, un peu plus fermes.",
    ],
    tags: ["banane", "bœuf", "quotidien"],
    featured: false,
    createdAt: added,
  },
];
