/** Recettes d'Afrique centrale (données de démonstration). */
import type { RecipeSeed } from "./recipe-seed";

export const recipesAfriqueCentrale: RecipeSeed[] = [
  {
    slug: "poulet-dg",
    name: "Poulet DG",
    countryCode: "CM",
    region: "Douala et Yaoundé",
    course: "mijotes",
    shortDescription: "Poulet doré et plantains mûrs sautés avec carottes, haricots verts et poivrons.",
    story:
      "Le poulet DG, pour « directeur général », serait né dans les années 1980 dans les restaurants de Douala. On raconte qu'il était alors réservé aux tables des patrons, tant le poulet et le plantain frit y étaient servis avec générosité.\n\nDevenu un classique des fêtes et des repas du dimanche dans tout le Cameroun, il réunit dans une même sauteuse le poulet doré, les plantains bien mûrs et une poêlée de légumes colorés.",
    prepMinutes: 30,
    cookMinutes: 60,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [1.5, "kg", "poulet fermier découpé en morceaux"],
      [4, null, "plantains bien mûrs (peau noircie)"],
      [3, null, "carottes"],
      [200, "g", "haricots verts"],
      [1, null, "poivron vert"],
      [2, null, "oignons"],
      [3, null, "tomates"],
      [4, "gousses", "ail"],
      [1, "morceau", "gingembre frais (4 cm)"],
      [15, "cl", "huile de friture"],
      [null, null, "poivre blanc de Penja", "poivre-de-penja"],
      [null, null, "sel"],
    ],
    steps: [
      "Mixer l'ail, le gingembre et un oignon avec un peu d'eau. Frotter les morceaux de poulet avec ce mélange, saler, poivrer au poivre de Penja et laisser mariner au moins 30 minutes.",
      "Placer le poulet dans une cocotte avec un verre d'eau, couvrir et cuire 20 minutes à feu moyen. Égoutter les morceaux en réservant le bouillon.",
      "Faire dorer le poulet dans une poêle avec un peu d'huile chaude jusqu'à ce que la peau soit bien colorée, puis réserver.",
      "Éplucher les plantains, les couper en rondelles épaisses en biais et les frire dans l'huile chaude 3 à 4 minutes de chaque côté. Égoutter sur du papier absorbant.",
      "Dans une grande sauteuse, faire revenir le second oignon émincé, ajouter les tomates concassées, puis les carottes en bâtonnets et les haricots verts. Mouiller avec le bouillon réservé et cuire 10 minutes.",
      "Ajouter le poivron en lanières et le poulet, laisser mijoter 10 minutes, puis incorporer délicatement les plantains. Rectifier l'assaisonnement et servir aussitôt.",
    ],
    tips: [
      "Choisissez des plantains presque noirs : ils caramélisent à la friture et apportent la note sucrée qui fait tout le charme du plat.",
      "Ajoutez les plantains en dernier et remuez à peine pour qu'ils gardent leur forme.",
    ],
    tags: ["fête", "plantain", "poulet"],
    featured: true,
  },
  {
    slug: "eru",
    name: "Eru",
    countryCode: "CM",
    region: "Sud-Ouest, Mamfé",
    course: "mijotes",
    shortDescription: "Feuilles d'okok finement émincées, mijotées avec waterleaf, huile de palme, viande et poisson fumé.",
    story:
      "L'eru est la grande spécialité des Bayangi, peuple de la région de Mamfé, dans le Sud-Ouest du Cameroun. Son nom désigne à la fois le plat et la liane sauvage dont on récolte les feuilles, appelée okok dans d'autres régions du pays.\n\nOn le sert traditionnellement avec du water fufu, une boule de manioc fermenté, lors des réunions de famille et des cérémonies. Sa texture fondante et son goût fumé en font l'un des plats les plus appréciés du Cameroun anglophone.",
    prepMinutes: 30,
    cookMinutes: 60,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [200, "g", "feuilles d'okok (eru) séchées et émincées", "feuilles-d-okok"],
      [1, "kg", "waterleaf frais ou épinards"],
      [500, "g", "bœuf ou peau de bœuf (kanda) en morceaux"],
      [200, "g", "poisson fumé émietté", "poisson-fume"],
      [50, "g", "crevettes séchées", "crevettes-sechees"],
      [30, "cl", "huile de palme rouge", "huile-de-palme-rouge"],
      [1, null, "oignon"],
      [1, null, "piment frais"],
      [1, null, "cube de bouillon"],
      [null, null, "sel"],
    ],
    steps: [
      "Réhydrater les feuilles d'okok 20 minutes dans l'eau tiède, puis les rincer et bien les égoutter.",
      "Cuire la viande 40 minutes dans une marmite avec l'oignon émincé, le cube de bouillon, le sel et juste assez d'eau pour la couvrir.",
      "Laver le waterleaf, l'émincer finement et l'ajouter à la viande. Laisser cuire 5 minutes : les feuilles rendent beaucoup d'eau.",
      "Incorporer le poisson fumé débarrassé de ses arêtes, les crevettes séchées pilées et le piment écrasé. Mélanger.",
      "Ajouter les feuilles d'okok petit à petit en remuant, puis verser l'huile de palme. Couvrir et laisser mijoter 15 minutes à feu doux, jusqu'à ce que le liquide soit presque entièrement absorbé.",
      "Goûter, rectifier le sel et servir bien chaud avec du water fufu ou du garri.",
    ],
    tips: [
      "Si vous utilisez des épinards, égouttez-les bien après la cuisson : ils contiennent moins d'eau que le waterleaf et l'eru ne doit pas être trop sec pour autant.",
      "L'eru est encore meilleur réchauffé le lendemain.",
    ],
    tags: ["feuilles", "huile de palme", "fumé"],
    featured: false,
  },
  {
    slug: "koki",
    name: "Koki",
    countryCode: "CM",
    region: "Littoral et Ouest",
    course: "accompagnements",
    shortDescription: "Gâteau de haricots cornille à l'huile de palme, cuit à la vapeur en feuilles de bananier.",
    story:
      "Le koki est un mets très ancien du Cameroun, préparé aussi bien sur la côte que dans l'Ouest du pays. Les haricots cornille, débarrassés de leur peau puis écrasés, sont battus avec l'huile de palme jusqu'à former une pâte orangée et soyeuse.\n\nEnveloppé dans des feuilles de bananier et cuit longuement à la vapeur, il accompagne volontiers le plantain ou le macabo bouillis. On le partage lors des marchés et des fêtes de village.",
    prepMinutes: 60,
    cookMinutes: 120,
    servings: 8,
    difficulty: 3,
    ingredients: [
      [500, "g", "haricots cornille (niébé) secs"],
      [25, "cl", "huile de palme rouge", "huile-de-palme-rouge"],
      [1, null, "oignon"],
      [1, null, "piment frais"],
      [300, "g", "jeunes feuilles de taro ou épinards"],
      [30, "cl", "eau tiède"],
      [1, null, "cube de bouillon"],
      [null, null, "sel"],
      [null, null, "feuilles de bananier"],
    ],
    steps: [
      "Faire tremper les haricots 6 heures dans l'eau froide. Les frotter entre les mains pour retirer les peaux, qui remontent à la surface, puis rincer.",
      "Mixer les haricots avec l'oignon, le piment et un peu d'eau tiède jusqu'à obtenir une pâte très fine et lisse.",
      "Faire tiédir l'huile de palme sans la laisser fumer, puis l'incorporer peu à peu à la pâte en battant vigoureusement. Ajouter le reste d'eau, le cube émietté, le sel et les feuilles de taro émincées.",
      "Passer les feuilles de bananier quelques secondes au-dessus d'une flamme pour les assouplir. Déposer une louche de pâte au centre de chaque feuille et refermer en paquet bien serré.",
      "Tapisser le fond d'une grande marmite de tiges ou de feuilles de bananier, ajouter un fond d'eau et y ranger les paquets. Couvrir et cuire 2 heures à feu moyen, en rajoutant de l'eau si nécessaire.",
      "Le koki est cuit lorsqu'il est ferme au toucher. Laisser reposer 10 minutes avant d'ouvrir les paquets.",
    ],
    tips: [
      "Plus la pâte est battue, plus le koki est léger : n'hésitez pas à fouetter plusieurs minutes.",
      "À défaut de feuilles de bananier, utilisez des ramequins filmés ou du papier aluminium.",
    ],
    tags: ["haricots", "vapeur", "huile de palme"],
    featured: false,
  },
  {
    slug: "moambe",
    name: "Poulet à la moambé",
    countryCode: "CD",
    region: "Kinshasa",
    course: "mijotes",
    shortDescription: "Poulet mijoté dans une sauce onctueuse à la noix de palme et à la pâte d'arachide.",
    story:
      "La moambé est souvent présentée comme le plat national de la République démocratique du Congo, et on la retrouve aussi au Congo-Brazzaville, en Angola et en Centrafrique. Son nom viendrait du lingala et désigne la sauce obtenue à partir de la pulpe des noix de palme.\n\nChaque famille a sa version : certaines y ajoutent de la pâte d'arachide pour une sauce plus ronde, d'autres la préfèrent nature. On la sert avec du riz, du fufu ou de la chikwangue.",
    prepMinutes: 25,
    cookMinutes: 75,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [1.5, "kg", "poulet découpé en morceaux"],
      [400, "g", "pulpe de noix de palme", "pulpe-de-noix-de-palme"],
      [3, "c. à soupe", "pâte d'arachide", "pate-d-arachide"],
      [2, null, "oignons"],
      [3, null, "tomates"],
      [3, "gousses", "ail"],
      [1, null, "piment frais"],
      [2, "c. à soupe", "huile"],
      [1, null, "cube de bouillon"],
      [null, null, "sel"],
    ],
    steps: [
      "Saler les morceaux de poulet et les faire dorer dans l'huile chaude dans une cocotte, 10 minutes environ. Réserver.",
      "Dans la même cocotte, faire revenir les oignons émincés et l'ail haché, puis ajouter les tomates concassées et cuire 5 minutes.",
      "Délayer la pulpe de noix de palme dans 50 cl d'eau chaude, verser dans la cocotte et porter à frémissement.",
      "Remettre le poulet, ajouter le cube de bouillon et le piment entier. Couvrir et laisser mijoter 40 minutes à feu doux.",
      "Délayer la pâte d'arachide dans une louche de sauce, puis l'incorporer. Cuire encore 15 minutes à découvert en remuant, jusqu'à ce que la sauce nappe la cuillère et que l'huile remonte à la surface.",
      "Retirer le piment, rectifier l'assaisonnement et servir avec du riz blanc ou du fufu.",
    ],
    tips: [
      "Laissez le piment entier pour parfumer sans trop relever ; percez-le si vous aimez une sauce plus piquante.",
      "Un poulet fermier, plus ferme, supporte mieux la longue cuisson.",
    ],
    tags: ["noix de palme", "arachide", "poulet"],
    featured: false,
  },
  {
    slug: "liboke-de-poisson",
    name: "Liboké de poisson",
    countryCode: "CG",
    region: "Brazzaville et bords du fleuve Congo",
    course: "grillades",
    shortDescription: "Poisson aux tomates et aux aromates en papillote de feuilles de bananier, cuit sur la braise.",
    story:
      "Le liboké (pluriel : maboké) est une technique de cuisson emblématique des deux rives du fleuve Congo. Le mot, issu du lingala, désigne le paquet de feuilles de bananier dans lequel on enferme poisson, viande ou légumes avant de le poser sur les braises.\n\nLes pêcheurs du fleuve préparent ainsi le capitaine, le silure ou la carpe, qui cuisent doucement dans leur propre jus. À Brazzaville, le liboké de poisson reste un incontournable des repas partagés en plein air.",
    prepMinutes: 25,
    cookMinutes: 35,
    servings: 4,
    difficulty: 2,
    ingredients: [
      [1, "kg", "poisson ferme (capitaine, tilapia ou carpe) en tronçons"],
      [3, null, "tomates"],
      [2, null, "oignons"],
      [3, "gousses", "ail"],
      [1, "morceau", "gingembre frais (3 cm)"],
      [1, null, "piment frais"],
      [1, "botte", "ciboule"],
      [4, null, "grains de poivre de Selim", "poivre-de-selim"],
      [2, "c. à soupe", "huile"],
      [null, null, "sel"],
      [null, null, "feuilles de bananier"],
    ],
    steps: [
      "Écailler et vider le poisson, le rincer, puis le couper en tronçons. Saler légèrement.",
      "Piler ou mixer l'ail, le gingembre, le piment et les grains de poivre de Selim légèrement écrasés. Frotter le poisson avec cette pâte et laisser reposer 15 minutes.",
      "Couper les tomates et les oignons en dés, ciseler la ciboule et mélanger le tout avec l'huile.",
      "Passer les feuilles de bananier au-dessus d'une flamme pour les assouplir. Sur deux feuilles croisées, déposer une couche de légumes, le poisson, puis le reste des légumes.",
      "Refermer en paquet bien serré et ficeler avec une lanière de feuille ou de la ficelle de cuisine. Emballer d'une seconde feuille pour éviter les fuites.",
      "Poser les papillotes sur des braises moyennes et cuire 30 à 35 minutes en les retournant à mi-cuisson. Ouvrir à table pour profiter du parfum.",
    ],
    tips: [
      "Au four, comptez 35 minutes à 200 °C, papillotes posées sur une plaque.",
      "Servez avec de la chikwangue ou des bananes plantains bouillies.",
    ],
    tags: ["papillote", "braise", "poisson"],
    featured: false,
  },
  {
    slug: "poulet-odika",
    name: "Poulet à l'odika",
    countryCode: "GA",
    region: "Libreville",
    course: "mijotes",
    shortDescription: "Poulet fumé mijoté dans une sauce sombre et onctueuse au « chocolat indigène ».",
    story:
      "L'odika, que les Gabonais surnomment volontiers « chocolat indigène », est une pâte faite des amandes grillées de la mangue sauvage. Moulue puis moulée en pains sombres, elle est vendue sur tous les marchés du Gabon.\n\nRâpée dans la sauce, elle lui donne une couleur brune, une consistance veloutée et un goût légèrement fumé. Le poulet à l'odika est l'un des plats les plus représentatifs de la cuisine gabonaise, souvent servi avec du manioc ou du riz.",
    prepMinutes: 20,
    cookMinutes: 60,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [1.5, "kg", "poulet (idéalement fumé) en morceaux"],
      [100, "g", "odika râpé", "odika"],
      [2, null, "oignons"],
      [2, null, "tomates"],
      [3, "gousses", "ail"],
      [1, null, "piment frais"],
      [5, "cl", "huile de palme rouge", "huile-de-palme-rouge"],
      [1, null, "cube de bouillon"],
      [null, null, "sel"],
    ],
    steps: [
      "Faire revenir les morceaux de poulet dans l'huile de palme chaude pendant 10 minutes, jusqu'à ce qu'ils soient dorés.",
      "Ajouter les oignons émincés, l'ail haché et les tomates concassées. Laisser fondre 5 minutes.",
      "Mouiller avec 60 cl d'eau, ajouter le cube de bouillon et le piment entier. Couvrir et laisser mijoter 30 minutes.",
      "Râper finement l'odika et le délayer dans une louche de bouillon chaud jusqu'à obtenir une crème lisse.",
      "Verser l'odika dans la cocotte en remuant sans cesse, puis cuire 15 minutes à feu doux : la sauce épaissit et devient brune et brillante.",
      "Rectifier le sel, retirer le piment et servir avec du bâton de manioc ou du riz.",
    ],
    tips: [
      "Chauffez légèrement le pain d'odika au-dessus d'une flamme : il se râpe beaucoup plus facilement.",
      "Remuez bien après l'ajout d'odika, la sauce accroche vite au fond de la marmite.",
    ],
    tags: ["odika", "poulet", "Gabon"],
    featured: false,
  },
  {
    slug: "puff-puff",
    name: "Puff-puff",
    countryCode: "NG",
    region: "Lagos",
    course: "douceurs",
    shortDescription: "Petits beignets levés, dorés dehors et moelleux dedans, parfumés à la muscade.",
    story:
      "Le puff-puff est l'un des en-cas de rue les plus populaires du Nigeria, vendu tout chaud dans des sachets en papier au coin des rues de Lagos. On le retrouve sous d'autres noms dans toute la région : bofrot au Ghana, beignets ou « boules » au Cameroun, mikate au Congo.\n\nSimple pâte levée frite en petites boules, il accompagne les fêtes, les anniversaires et les goûters. On le mange nature, saupoudré de sucre ou accompagné d'une sauce pimentée.",
    prepMinutes: 15,
    cookMinutes: 20,
    servings: 6,
    difficulty: 1,
    ingredients: [
      [500, "g", "farine de blé"],
      [100, "g", "sucre"],
      [7, "g", "levure de boulanger sèche"],
      [1, "c. à café", "noix de muscade râpée"],
      [1, "pincée", "sel"],
      [40, "cl", "eau tiède"],
      [1, "l", "huile de friture"],
    ],
    steps: [
      "Dans un saladier, mélanger la farine, le sucre, la levure, la muscade et le sel.",
      "Verser l'eau tiède peu à peu en mélangeant à la main ou à la spatule jusqu'à obtenir une pâte épaisse, collante et lisse, sans grumeaux.",
      "Couvrir d'un linge et laisser lever 1 heure dans un endroit tiède : la pâte doit doubler de volume et se couvrir de bulles.",
      "Chauffer l'huile à 170 °C. Prendre une poignée de pâte et la presser entre le pouce et l'index pour former une petite boule que l'on fait glisser dans l'huile.",
      "Frire les beignets 3 à 4 minutes en les retournant pour qu'ils dorent uniformément. Égoutter sur du papier absorbant.",
      "Servir tiède, nature ou roulé dans du sucre.",
    ],
    tips: [
      "Si l'huile est trop chaude, les puff-puff dorent dehors mais restent crus au cœur : baissez le feu.",
      "Une cuillère trempée dans l'eau permet aussi de former des boules régulières.",
    ],
    tags: ["beignets", "street food", "goûter"],
    featured: true,
  },
  {
    slug: "degue",
    name: "Dégué",
    countryCode: "BF",
    region: "Ouagadougou",
    course: "douceurs",
    shortDescription: "Graines de mil cuites à la vapeur, mêlées à un lait caillé sucré et bien frais.",
    story:
      "Le dégué est un dessert très répandu au Burkina Faso, au Mali, en Côte d'Ivoire et dans toute l'Afrique de l'Ouest sahélienne. Les petites graines de mil roulées, proches du couscous, sont cuites à la vapeur puis mélangées à du lait caillé.\n\nVendu en sachets bien frais sur les marchés et devant les écoles, il se déguste à toute heure, surtout pendant les journées chaudes. Au Sénégal, un dessert voisin porte le nom de thiakry.",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 6,
    difficulty: 1,
    ingredients: [
      [250, "g", "couscous de mil", "couscous-de-mil"],
      [1, "l", "lait caillé ou yaourt nature brassé"],
      [20, "cl", "lait concentré sucré"],
      [80, "g", "sucre"],
      [1, "c. à café", "extrait de vanille"],
      [1, "pincée", "noix de muscade râpée"],
      [20, "g", "beurre"],
    ],
    steps: [
      "Humidifier légèrement le couscous de mil avec 10 cl d'eau froide, bien mélanger du bout des doigts et laisser gonfler 10 minutes.",
      "Cuire le mil 15 minutes à la vapeur dans le haut d'un couscoussier, puis l'égrener dans un grand plat.",
      "Arroser à nouveau de 5 cl d'eau, égrener et remettre à la vapeur 10 minutes. Incorporer le beurre et laisser refroidir complètement.",
      "Fouetter le lait caillé avec le lait concentré, le sucre, la vanille et la muscade jusqu'à obtenir une crème lisse.",
      "Mélanger le mil refroidi à la crème, couvrir et réserver au moins 2 heures au réfrigérateur. Servir très frais dans des bols ou des verres.",
    ],
    tips: [
      "Ajoutez un peu de lait si le dégué épaissit trop au réfrigérateur : le mil continue d'absorber le liquide.",
      "Quelques raisins secs ou un peu de noix de coco râpée apportent une touche gourmande.",
    ],
    tags: ["mil", "lait caillé", "dessert frais"],
    featured: false,
  },
];
