/** Douceurs et boissons (données de démonstration). */
import type { RecipeSeed } from "./recipe-seed";

export const recipesDouceurs: RecipeSeed[] = [
  {
    slug: "cafe-touba",
    name: "Café Touba",
    countryCode: "SN",
    region: "Diourbel, Touba",
    course: "douceurs",
    shortDescription: "Café torréfié maison avec le djar, poivre de Selim aux notes boisées et poivrées.",
    story:
      "Le café Touba porte le nom de la ville sainte fondée par Cheikh Ahmadou Bamba, figure de la confrérie mouride. Selon la tradition, c'est dans l'entourage du cheikh que l'habitude de parfumer le café au djar s'est installée, avant de gagner tout le Sénégal.\n\nAujourd'hui, on le boit à toute heure, servi brûlant et bien sucré dans de petits gobelets, au coin des rues de Dakar comme lors du grand Magal de Touba. Son goût se reconnaît immédiatement : une amertume ronde, relevée par le parfum résineux et légèrement piquant du poivre de Selim.",
    prepMinutes: 10,
    cookMinutes: 25,
    servings: 10,
    difficulty: 2,
    ingredients: [
      [250, "g", "café vert (robusta de préférence)"],
      [15, "g", "poivre de Selim (djar) en gousses", "poivre-de-selim"],
      [2, null, "clous de girofle (facultatif)"],
      [1, "l", "eau"],
      [120, "g", "sucre"],
    ],
    steps: [
      "Faire chauffer une grande poêle épaisse à sec sur feu moyen, puis y verser le café vert. Le remuer sans arrêt avec une cuillère en bois pendant 15 à 20 minutes, jusqu'à ce que les grains deviennent brun foncé et commencent à craquer.",
      "Ajouter les gousses de djar et les clous de girofle, puis poursuivre la torréfaction 3 à 4 minutes en remuant : les épices doivent griller sans noircir et libérer leur parfum.",
      "Étaler le mélange sur un plateau et le laisser refroidir complètement, puis le moudre finement au moulin à café ou au pilon.",
      "Porter l'eau à frémissement. Placer 6 à 7 c. à soupe de mouture dans un filtre en tissu ou en papier, puis verser l'eau chaude lentement par-dessus.",
      "Sucrer le café recueilli et le repasser une seconde fois dans le filtre pour qu'il gagne en corps. Servir très chaud dans de petits verres.",
    ],
    tips: [
      "Conservez la mouture dans un bocal hermétique à l'abri de la lumière : elle garde son parfum plusieurs semaines.",
      "Pour une version plus douce, réduisez le djar à 10 g ; pour un café plus poivré, montez jusqu'à 20 g.",
    ],
    tags: ["café", "épices", "tradition"],
    featured: true,
  },
  {
    slug: "jus-de-gingembre",
    name: "Jus de gingembre (gnamankoudji)",
    countryCode: "CI",
    region: "Abidjan",
    course: "douceurs",
    shortDescription: "Boisson glacée au gingembre frais, citron et ananas, vive et piquante.",
    story:
      "En Côte d'Ivoire, le gnamankoudji est de toutes les fêtes : mariages, baptêmes, anniversaires et soirées de maquis. Vendu en petites bouteilles bien fraîches au bord des routes, il fait partie du paysage d'Abidjan.\n\nChaque famille a sa recette : certains y ajoutent de l'ananas, d'autres de la menthe ou de la vanille. Le principe reste le même, un gingembre généreux dont le piquant est adouci par le sucre et l'acidité du citron.",
    prepMinutes: 25,
    cookMinutes: 0,
    servings: 8,
    difficulty: 1,
    ingredients: [
      [300, "g", "gingembre frais"],
      [0.5, null, "ananas bien mûr"],
      [3, null, "citrons verts"],
      [200, "g", "sucre"],
      [1, null, "sachet de sucre vanillé"],
      [5, null, "feuilles de menthe fraîche (facultatif)"],
      [2, "l", "eau froide"],
    ],
    steps: [
      "Peler le gingembre à la cuillère, puis le couper en rondelles. Peler l'ananas, retirer le cœur et le couper en morceaux.",
      "Mixer le gingembre et l'ananas avec 50 cl d'eau jusqu'à obtenir une purée très fine.",
      "Verser la purée dans un linge propre ou un tamis fin au-dessus d'un saladier, ajouter le reste de l'eau et presser fortement pour extraire tout le jus.",
      "Ajouter le jus des citrons, le sucre, le sucre vanillé et les feuilles de menthe froissées. Mélanger jusqu'à dissolution complète du sucre, puis goûter et ajuster.",
      "Mettre en bouteilles et placer au réfrigérateur au moins 2 heures. Servir très frais, en secouant avant de verser.",
    ],
    tips: [
      "Le jus se garde 3 jours au frais ; il devient plus piquant avec le temps.",
      "Pour un goût plus doux, remplacez une partie du sucre par du miel ou allongez avec un peu plus d'eau.",
    ],
    tags: ["boisson", "gingembre", "fête"],
    featured: false,
  },
  {
    slug: "ngalakh",
    name: "Ngalakh",
    countryCode: "SN",
    region: "Dakar et Petite-Côte",
    course: "douceurs",
    shortDescription: "Le dessert de Pâques sénégalais : mil, pâte d'arachide et pain de singe.",
    story:
      "Le ngalakh est la douceur emblématique de Pâques chez les chrétiens du Sénégal. Le Vendredi saint, les familles en préparent de grandes bassines, puis en offrent des bols à leurs voisins, amis et proches, quelle que soit leur religion.\n\nCe partage est devenu un symbole apprécié de la convivialité sénégalaise. La recette associe trois saveurs du terroir : le mil, l'arachide et le pain de singe, le fruit du baobab, dont l'acidité légère équilibre la richesse de la crème.",
    prepMinutes: 30,
    cookMinutes: 30,
    servings: 8,
    difficulty: 2,
    ingredients: [
      [500, "g", "couscous de mil (sankhal ou arraw)", "couscous-de-mil"],
      [250, "g", "pâte d'arachide", "pate-d-arachide"],
      [150, "g", "poudre de pain de singe (bouye)", "poudre-de-baobab"],
      [200, "g", "sucre"],
      [1.5, "l", "eau"],
      [2, null, "sachets de sucre vanillé"],
      [1, "c. à soupe", "eau de fleur d'oranger"],
      [1, "pincée", "noix de muscade râpée"],
      [80, "g", "raisins secs"],
    ],
    steps: [
      "Humidifier le couscous de mil avec un peu d'eau, l'égrainer à la main, puis le cuire 20 minutes à la vapeur dans un couscoussier. L'égrainer de nouveau et le laisser refroidir.",
      "Dans une casserole, délayer la pâte d'arachide dans 75 cl d'eau chaude avec le sucre. Porter à frémissement et cuire 10 minutes à feu doux en remuant, jusqu'à obtenir une crème lisse. Laisser refroidir.",
      "Délayer la poudre de pain de singe dans 75 cl d'eau froide, puis filtrer au tamis pour retirer les fibres et les éventuels grains.",
      "Mélanger la crème d'arachide refroidie avec le jus de pain de singe, le sucre vanillé, la fleur d'oranger et la muscade. La préparation doit être onctueuse et bien nappante.",
      "Verser cette crème sur le mil, ajouter les raisins secs et mélanger délicatement. Réserver au moins 2 heures au réfrigérateur et servir bien frais.",
    ],
    tips: [
      "Ne faites jamais cuire le pain de singe : il perdrait son acidité fraîche.",
      "Si la crème épaissit trop au froid, détendez-la avec un peu d'eau ou de lait juste avant de servir.",
    ],
    tags: ["Pâques", "mil", "arachide", "partage"],
    featured: false,
  },
  {
    slug: "jus-de-bouye",
    name: "Jus de bouye",
    countryCode: "SN",
    region: "Dakar",
    course: "douceurs",
    shortDescription: "Boisson crémeuse et acidulée au pain de singe, le fruit du baobab.",
    story:
      "Le baobab est l'arbre emblème du Sénégal, présent jusque sur les armoiries du pays. Son fruit, appelé pain de singe, renferme une pulpe blanche et farineuse que l'on nomme bouye en wolof.\n\nDélayée dans l'eau et sucrée, elle donne une boisson onctueuse au goût acidulé, que l'on sert lors des cérémonies familiales, des baptêmes et, pendant le ramadan, à la rupture du jeûne. Souvent enrichi de lait, parfumé à la vanille ou à la fleur d'oranger, le jus de bouye est l'un des grands classiques des tables sénégalaises.",
    prepMinutes: 20,
    cookMinutes: 0,
    servings: 8,
    difficulty: 1,
    ingredients: [
      [200, "g", "poudre de pain de singe (bouye)", "poudre-de-baobab"],
      [1.5, "l", "eau froide"],
      [150, "g", "sucre"],
      [20, "cl", "lait concentré sucré (facultatif)"],
      [1, null, "sachet de sucre vanillé"],
      [1, "c. à café", "eau de fleur d'oranger"],
    ],
    steps: [
      "Verser la poudre de pain de singe dans un grand saladier et ajouter progressivement 1 l d'eau froide en fouettant pour éviter les grumeaux.",
      "Laisser reposer 10 minutes, puis malaxer à la main ou au fouet pour bien détacher la pulpe.",
      "Filtrer au tamis fin ou à travers un linge en pressant, afin d'éliminer les fibres et les éventuels grains.",
      "Ajouter le reste de l'eau, le sucre, le sucre vanillé, la fleur d'oranger et le lait concentré. Mélanger jusqu'à dissolution complète et goûter pour ajuster la douceur.",
      "Mettre en bouteilles et réserver au moins 2 heures au réfrigérateur. Bien secouer avant de servir très frais.",
    ],
    tips: [
      "Sans lait, le jus est plus léger et plus acidulé ; avec lait, il devient crémeux, presque comme un milkshake.",
      "Consommez-le dans les 48 heures, gardé au frais.",
    ],
    tags: ["boisson", "baobab", "ramadan"],
    featured: false,
  },
];
