/**
 * Recettes de démonstration (mode démo et source de db/seed.sql).
 * Photos générées par IA, à remplacer par de vraies photos.
 * Les recettes sont réparties par région dans les fichiers recipes-*.ts.
 */
import type { Recipe } from "../types";
import { buildRecipes, type RecipeSeed } from "./recipe-seed";
import { recipesAfriqueCentrale } from "./recipes-centre";
import { recipesDouceurs } from "./recipes-douceurs";
import { recipesAfriqueEstAustrale } from "./recipes-est-australe";
import { recipesAfriqueOuest } from "./recipes-ouest";

const seeds: RecipeSeed[] = [
  // ---------------------------------------------------------- Mijotés
  {
    slug: "ndole",
    name: "Ndolé aux crevettes",
    countryCode: "CM",
    region: "Littoral, Douala",
    course: "mijotes",
    shortDescription: "Le plat national camerounais : feuilles amères, arachides fondantes et crevettes.",
    story:
      "Né chez les Doualas, sur les rives du Wouri, le ndolé est devenu le plat des grandes occasions dans tout le Cameroun. On le prépare pour les mariages, les baptêmes et les dimanches en famille.\n\nSa magie tient à l'équilibre entre l'amertume des feuilles, patiemment lavées, et la douceur des arachides fraîches longuement mijotées.",
    prepMinutes: 40,
    cookMinutes: 75,
    servings: 6,
    difficulty: 3,
    ingredients: [
      [200, "g", "feuilles de ndolé séchées", "feuilles-de-ndole"],
      [500, "g", "arachides crues décortiquées"],
      [500, "g", "crevettes fraîches décortiquées"],
      [50, "g", "crevettes séchées", "crevettes-sechees"],
      [400, "g", "bœuf à braiser en cubes"],
      [2, null, "oignons"],
      [3, "gousses", "ail"],
      [1, "morceau", "gingembre frais (3 cm)"],
      [10, "cl", "huile d'arachide"],
      [null, null, "poivre blanc de Penja", "poivre-de-penja"],
      [null, null, "sel"],
    ],
    steps: [
      "Réhydrater les feuilles de ndolé 30 minutes dans l'eau tiède, puis les rincer deux fois et les presser fortement pour retirer l'amertume.",
      "Faire tremper les arachides 15 minutes dans l'eau chaude, retirer les peaux, puis les cuire 20 minutes et les mixer en une pâte fine avec un peu d'eau de cuisson.",
      "Faire revenir le bœuf dans une cocotte avec un oignon émincé, l'ail et le gingembre mixés. Couvrir d'eau et laisser mijoter 40 minutes.",
      "Ajouter la pâte d'arachide et les crevettes séchées, puis cuire 15 minutes à feu doux en remuant souvent pour que rien n'attache.",
      "Incorporer les feuilles de ndolé et laisser mijoter encore 15 minutes. Saler et poivrer généreusement au poivre de Penja.",
      "Dans une poêle, faire dorer les crevettes fraîches avec le second oignon émincé dans l'huile, puis les verser sur le ndolé au moment de servir.",
    ],
    tips: [
      "Servez avec du plantain mûr frit (miondo ou bâton de manioc au Cameroun).",
      "Plus les feuilles sont rincées, moins le ndolé est amer : goûtez-les avant de les cuire.",
    ],
    tags: ["fête", "arachide"],
    featured: true,
  },
  {
    slug: "mafe",
    name: "Mafé de bœuf",
    countryCode: "ML",
    region: "Bamako",
    course: "mijotes",
    shortDescription: "Bœuf fondant dans une sauce onctueuse à la pâte d'arachide.",
    story:
      "Le mafé, ou tigadèguèna (« sauce d'arachide » en bambara), vient des Mandingues du Mali. Il s'est répandu dans toute l'Afrique de l'Ouest, chaque pays y ajoutant sa touche.\n\nC'est le plat du quotidien par excellence : une grande marmite qui mijote pendant que la famille se réunit.",
    prepMinutes: 20,
    cookMinutes: 90,
    servings: 6,
    difficulty: 1,
    ingredients: [
      [800, "g", "bœuf à braiser en morceaux"],
      [250, "g", "pâte d'arachide pure", "pate-d-arachide"],
      [2, null, "oignons"],
      [3, "c. à soupe", "concentré de tomate"],
      [2, null, "tomates"],
      [3, null, "carottes"],
      [2, null, "patates douces"],
      [0.25, null, "chou blanc"],
      [1, "boule", "soumbala", "soumbala"],
      [1, null, "piment antillais entier"],
      [4, "c. à soupe", "huile"],
      [null, null, "sel et poivre"],
    ],
    steps: [
      "Faire dorer la viande dans l'huile, puis ajouter les oignons émincés et laisser fondre 5 minutes.",
      "Ajouter le concentré de tomate, les tomates concassées et le soumbala écrasé. Couvrir d'un litre d'eau et laisser cuire 30 minutes.",
      "Délayer la pâte d'arachide dans une louche de bouillon chaud et l'incorporer à la sauce.",
      "Ajouter les carottes, les patates douces, le chou et le piment entier (sans le percer). Cuire 45 minutes à feu doux en remuant régulièrement.",
      "Quand l'huile remonte à la surface, le mafé est prêt. Rectifier l'assaisonnement.",
    ],
    tips: ["Servez avec du riz blanc ou du fonio.", "Le mafé est encore meilleur réchauffé le lendemain."],
    tags: ["arachide", "familial"],
    featured: true,
  },
  {
    slug: "pondu",
    name: "Pondu au poisson fumé",
    countryCode: "CD",
    region: "Kinshasa",
    course: "mijotes",
    shortDescription: "Feuilles de manioc mijotées à l'huile de palme et au poisson fumé.",
    story:
      "Le pondu, ou saka-saka, est le légume-feuille des deux rives du fleuve Congo. Les feuilles de manioc, pilées au mortier, mijotent longuement jusqu'à devenir fondantes.\n\nÀ Kinshasa, on le sert avec de la chikwangue ou du fufu, et chaque famille a sa recette : avec du poisson fumé, de la viande ou simplement des aubergines.",
    prepMinutes: 20,
    cookMinutes: 120,
    servings: 4,
    difficulty: 2,
    ingredients: [
      [200, "g", "feuilles de manioc pilées", "feuilles-de-manioc"],
      [200, "g", "machoiron fumé", "poisson-fume"],
      [10, "cl", "huile de palme rouge", "huile-de-palme-rouge"],
      [2, null, "aubergines africaines (ou 1 aubergine)"],
      [1, null, "oignon"],
      [2, "gousses", "ail"],
      [1, null, "poivron vert"],
      [1, null, "piment"],
      [null, null, "sel"],
    ],
    steps: [
      "Réhydrater les feuilles de manioc dans de l'eau tiède 20 minutes, puis les porter à ébullition dans une grande casserole d'eau.",
      "Laisser cuire à feu doux 1 heure en ajoutant de l'eau si nécessaire : les feuilles de manioc doivent toujours être bien cuites.",
      "Pendant ce temps, faire tremper le poisson fumé dans l'eau chaude, retirer peau et arêtes et l'émietter.",
      "Ajouter l'oignon, l'ail, le poivron et les aubergines coupés en morceaux, puis le poisson. Poursuivre la cuisson 40 minutes.",
      "Verser l'huile de palme rouge, saler, ajouter le piment et laisser mijoter encore 15 minutes à découvert.",
    ],
    tips: ["Accompagnez de chikwangue, de fufu ou de riz.", "Une cuillère de pâte d'arachide rend le pondu plus onctueux."],
    tags: ["feuilles", "fumé"],
    featured: false,
  },
  {
    slug: "doro-wat",
    name: "Doro wat",
    countryCode: "ET",
    region: "Hauts plateaux",
    course: "mijotes",
    shortDescription: "Le ragoût de poulet au berbéré et aux œufs, plat de fête éthiopien.",
    story:
      "Le doro wat est le plat de fête de l'Éthiopie, servi à Noël et à Pâques après les longues périodes de jeûne. Sa préparation commence par une montagne d'oignons cuits à sec pendant près d'une heure.\n\nIl se mange à la main, avec l'injera, la grande crêpe acidulée au teff.",
    prepMinutes: 30,
    cookMinutes: 100,
    servings: 4,
    difficulty: 2,
    ingredients: [
      [8, null, "cuisses de poulet sans peau"],
      [1, "kg", "oignons rouges"],
      [4, "c. à soupe", "berbéré", "berbere"],
      [80, "g", "beurre"],
      [4, "gousses", "ail"],
      [1, "morceau", "gingembre frais (4 cm)"],
      [4, null, "œufs durs"],
      [1, null, "citron"],
      [null, null, "sel"],
    ],
    steps: [
      "Frotter le poulet avec le jus du citron et du sel, et laisser reposer 20 minutes.",
      "Hacher très finement les oignons et les cuire à sec, sans matière grasse, dans une cocotte à feu doux pendant 40 minutes en remuant souvent : ils doivent devenir une compote brune.",
      "Ajouter le beurre, l'ail et le gingembre râpés, puis le berbéré. Cuire 10 minutes en remuant.",
      "Ajouter le poulet et 40 cl d'eau. Laisser mijoter à couvert 45 minutes.",
      "Entailler les œufs durs écalés et les ajouter dans la sauce 10 minutes avant la fin de la cuisson.",
    ],
    tips: ["Servez avec de l'injera, ou à défaut du riz.", "Pour une version authentique, remplacez le beurre par du niter kibbeh (beurre clarifié épicé)."],
    tags: ["fête", "épicé"],
    featured: true,
  },
  {
    slug: "poulet-nyembwe",
    name: "Poulet nyembwe",
    countryCode: "GA",
    region: "Libreville",
    course: "mijotes",
    shortDescription: "Poulet mijoté dans la crème de noix de palme, le plat national gabonais.",
    story:
      "Le poulet nyembwe est le plat national du Gabon. La pulpe de noix de palme, longuement réduite, enrobe la viande d'une sauce orangée, onctueuse et fruitée.\n\nOn le sert avec du riz ou du manioc, souvent le dimanche.",
    prepMinutes: 20,
    cookMinutes: 60,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [1, null, "poulet découpé en morceaux"],
      [400, "g", "pulpe de noix de palme", "pulpe-de-noix-de-palme"],
      [2, null, "oignons"],
      [3, "gousses", "ail"],
      [1, null, "piment"],
      [2, "c. à soupe", "huile"],
      [null, null, "sel et poivre"],
    ],
    steps: [
      "Faire dorer les morceaux de poulet dans l'huile, puis ajouter les oignons émincés et l'ail.",
      "Diluer la pulpe de noix de palme dans 50 cl d'eau chaude et la verser sur le poulet.",
      "Ajouter le piment entier, saler, poivrer et laisser mijoter à feu doux 45 minutes, jusqu'à ce que la sauce épaississe et que l'huile rouge remonte.",
    ],
    tips: ["Servez avec du riz blanc ou des bâtons de manioc."],
    tags: ["palme"],
    featured: false,
  },
  // ------------------------------------------------------- Grillades
  {
    slug: "poulet-yassa",
    name: "Poulet yassa",
    countryCode: "SN",
    region: "Casamance",
    course: "grillades",
    shortDescription: "Poulet grillé, puis mijoté dans une montagne d'oignons au citron.",
    story:
      "Originaire de Casamance, au sud du Sénégal, le yassa est devenu l'un des plats les plus aimés du pays. Le poulet mariné est d'abord grillé au charbon, puis mijote dans les oignons fondus au citron et à la moutarde.\n\nAcidulé, doux et fumé à la fois.",
    prepMinutes: 30,
    cookMinutes: 60,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [1, null, "poulet découpé en morceaux"],
      [6, null, "gros oignons"],
      [4, null, "citrons verts"],
      [2, "c. à soupe", "moutarde"],
      [3, "gousses", "ail"],
      [2, "gousses", "poivre de Selim", "poivre-de-selim"],
      [1, null, "piment"],
      [10, "cl", "huile"],
      [null, null, "olives vertes"],
      [null, null, "sel et poivre"],
    ],
    steps: [
      "Émincer les oignons. Les mélanger avec le jus des citrons, la moutarde, l'ail écrasé, le poivre de Selim moulu, l'huile, du sel et du poivre.",
      "Ajouter le poulet et laisser mariner au moins 4 heures (idéalement une nuit) au frais.",
      "Égoutter le poulet et le griller au barbecue ou au four très chaud jusqu'à ce qu'il soit bien doré.",
      "Faire fondre les oignons de la marinade à feu moyen 20 minutes, puis ajouter le reste de la marinade et un verre d'eau.",
      "Ajouter le poulet grillé, le piment entier et les olives, et laisser mijoter 20 minutes.",
    ],
    tips: ["Servez avec du riz blanc.", "Le poisson (dorade, capitaine) se prépare de la même façon."],
    tags: ["citron", "grillé"],
    featured: true,
  },
  {
    slug: "suya",
    name: "Suya de bœuf",
    countryCode: "NG",
    region: "Kano",
    course: "grillades",
    shortDescription: "Brochettes de bœuf grillées, enrobées d'épices yaji à l'arachide.",
    story:
      "Le suya est la grillade de rue du Nigeria. Venue des Haoussas du nord, elle se vend le soir, au bord des routes, sur des braises rougeoyantes.\n\nLa viande, taillée très fine, est enrobée de yaji, un mélange d'arachide et de piment qui caramélise sur le feu.",
    prepMinutes: 25,
    cookMinutes: 15,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [600, "g", "rumsteck ou faux-filet"],
      [60, "g", "yaji, épices à suya", "yaji-suya"],
      [3, "c. à soupe", "huile d'arachide"],
      [1, null, "oignon rouge"],
      [2, null, "tomates"],
      [null, null, "sel"],
    ],
    steps: [
      "Tailler la viande en tranches très fines, puis l'enfiler en accordéon sur des brochettes.",
      "Badigeonner d'huile, saler, puis enrober généreusement de yaji. Laisser reposer 30 minutes.",
      "Griller sur des braises bien chaudes ou sous le gril du four, 4 à 5 minutes de chaque côté.",
      "Servir saupoudré d'un peu de yaji, avec l'oignon rouge émincé et les tomates en rondelles.",
    ],
    tips: ["Le poulet se prépare aussi en suya.", "Allergène : le yaji contient de l'arachide."],
    tags: ["street food", "piquant"],
    featured: true,
  },
  {
    slug: "poisson-braise-attieke",
    name: "Poisson braisé et attiéké",
    countryCode: "CI",
    region: "Abidjan",
    course: "grillades",
    shortDescription: "Le classique des maquis d'Abidjan : poisson grillé, attiéké et sauce crue.",
    story:
      "Le poisson braisé servi avec de l'attiéké est le plat emblématique des maquis, ces restaurants en plein air d'Abidjan. Le poisson, mariné aux épices, est grillé au charbon et servi avec une sauce crue de tomates, d'oignons et de piment.\n\nOn le mange avec les doigts, entre amis.",
    prepMinutes: 25,
    cookMinutes: 25,
    servings: 4,
    difficulty: 2,
    ingredients: [
      [2, null, "dorades ou bars vidés (500 g chacun)"],
      [400, "g", "attiéké déshydraté", "attieke-sec"],
      [3, null, "tomates"],
      [2, null, "oignons"],
      [1, null, "poivron vert"],
      [1, "morceau", "gingembre frais (3 cm)"],
      [3, "gousses", "ail"],
      [1, null, "piment frais"],
      [2, null, "citrons verts"],
      [6, "c. à soupe", "huile"],
      [null, null, "sel et poivre de Penja", "poivre-de-penja"],
    ],
    steps: [
      "Mixer l'ail, le gingembre, la moitié du piment, un demi-oignon, 3 cuillères d'huile, du sel et du poivre. Entailler les poissons et les enduire de cette marinade. Laisser reposer 30 minutes.",
      "Pour la sauce crue, couper finement les tomates, le reste des oignons, le poivron et le piment. Assaisonner de citron, de sel et d'un filet d'huile.",
      "Griller les poissons sur des braises ou au four à 220 °C, 10 à 12 minutes de chaque côté.",
      "Humidifier l'attiéké avec un peu d'eau salée, le laisser gonfler 5 minutes, puis le réchauffer à la vapeur 10 minutes.",
      "Servir le poisson avec l'attiéké et la sauce crue par-dessus.",
    ],
    tips: ["Ajoutez de l'alloco (bananes plantains frites) pour un repas complet."],
    tags: ["maquis", "poisson"],
    featured: false,
  },
  // --------------------------------------------------- Riz & céréales
  {
    slug: "thieboudienne",
    name: "Thiéboudienne",
    countryCode: "SN",
    region: "Saint-Louis",
    course: "riz-cereales",
    shortDescription: "Le riz au poisson du Sénégal, cuit dans le bouillon de légumes.",
    story:
      "Le thiéboudienne (« riz au poisson » en wolof) serait né à Saint-Louis, au XIXᵉ siècle, dans la cuisine de Penda Mbaye. Il est aujourd'hui inscrit au patrimoine culturel immatériel de l'UNESCO.\n\nLe poisson farci au persil, les légumes et le riz cuisent successivement dans le même bouillon rouge, relevé de guedj et de yeet.",
    prepMinutes: 45,
    cookMinutes: 90,
    servings: 6,
    difficulty: 3,
    ingredients: [
      [1.5, "kg", "poisson ferme (thiof, mérou ou dorade) en tranches"],
      [600, "g", "riz brisé"],
      [1, null, "botte de persil"],
      [4, "gousses", "ail"],
      [2, null, "oignons"],
      [70, "g", "concentré de tomate"],
      [50, "g", "guedj", "guedj"],
      [1, "boule", "nététou (soumbala)", "soumbala"],
      [2, null, "carottes"],
      [1, null, "manioc"],
      [1, null, "aubergine"],
      [0.25, null, "chou blanc"],
      [1, null, "patate douce"],
      [4, null, "gombos"],
      [15, "cl", "huile"],
      [1, null, "piment"],
      [null, null, "sel et poivre"],
    ],
    steps: [
      "Mixer le persil, l'ail, le piment, du sel et du poivre. Entailler les tranches de poisson et les farcir de ce mélange (le « roff »).",
      "Faire dorer le poisson dans l'huile chaude, puis le réserver.",
      "Dans la même huile, faire revenir les oignons, ajouter le concentré de tomate dilué, le guedj et le nététou. Cuire 10 minutes.",
      "Verser 2 litres d'eau, ajouter les légumes coupés en gros morceaux et le poisson. Cuire 40 minutes en retirant les légumes et le poisson au fur et à mesure qu'ils sont cuits.",
      "Laver le riz, le cuire à la vapeur 15 minutes, puis le verser dans le bouillon (il doit juste le couvrir). Cuire à couvert et à feu doux 25 minutes.",
      "Servir le riz dans un grand plat, avec le poisson et les légumes par-dessus. Le riz croustillant du fond (le « xoon ») est la partie la plus recherchée.",
    ],
    tips: ["Pressez un citron vert sur l'assiette au moment de servir.", "Le yeet (mollusque séché) apporte un goût encore plus authentique."],
    tags: ["UNESCO", "poisson", "fête"],
    featured: true,
  },
  {
    slug: "fonio-aux-legumes",
    name: "Fonio aux légumes et sauce arachide",
    countryCode: "BF",
    region: "Bobo-Dioulasso",
    course: "riz-cereales",
    shortDescription: "La céréale ancienne du Sahel, légère, avec une sauce aux légumes.",
    story:
      "Au Burkina Faso et au Mali, le fonio est la céréale des jours de fête et des hôtes de marque. On dit qu'il ne fait jamais honte à celui qui le cuisine, car il est toujours réussi.\n\nCuit à la vapeur en quelques minutes, il accompagne ici une sauce aux légumes relevée de soumbala.",
    prepMinutes: 20,
    cookMinutes: 35,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [300, "g", "fonio précuit", "fonio"],
      [2, null, "courgettes"],
      [2, null, "carottes"],
      [1, null, "oignon"],
      [2, null, "tomates"],
      [100, "g", "pâte d'arachide", "pate-d-arachide"],
      [1, "boule", "soumbala", "soumbala"],
      [3, "c. à soupe", "huile"],
      [null, null, "sel et piment"],
    ],
    steps: [
      "Faire revenir l'oignon émincé dans l'huile, ajouter les tomates concassées et le soumbala écrasé.",
      "Ajouter les carottes et les courgettes en dés, couvrir d'eau et cuire 20 minutes.",
      "Délayer la pâte d'arachide dans un peu de bouillon, l'incorporer et laisser épaissir 10 minutes.",
      "Porter 45 cl d'eau salée à ébullition, verser le fonio, couvrir hors du feu 5 minutes puis égrainer à la fourchette.",
      "Servir le fonio avec la sauce aux légumes.",
    ],
    tips: ["Le fonio se prépare aussi en salade froide, comme un taboulé."],
    tags: ["végétarien", "céréale ancienne"],
    featured: false,
  },
  // --------------------------------------------------- Accompagnements
  {
    slug: "alloco",
    name: "Alloco",
    countryCode: "CI",
    region: "Abidjan",
    course: "accompagnements",
    shortDescription: "Bananes plantains mûres frites, dorées et fondantes.",
    story:
      "L'alloco tire son nom d'Allocodrome, le quartier de Cocody à Abidjan où les vendeuses frient les plantains le soir venu. Il accompagne le poisson braisé, le poulet ou se mange tel quel avec une sauce pimentée.",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [4, null, "bananes plantains bien mûres (peau noire)"],
      [50, "cl", "huile de friture"],
      [1, null, "oignon"],
      [1, null, "piment"],
      [null, null, "sel"],
    ],
    steps: [
      "Éplucher les plantains et les couper en rondelles épaisses ou en biais.",
      "Saler légèrement et frire dans l'huile chaude (170 °C) 4 à 5 minutes, jusqu'à ce qu'ils soient bien dorés.",
      "Égoutter sur du papier absorbant et servir avec l'oignon et le piment hachés.",
    ],
    tips: ["Plus le plantain est mûr, plus l'alloco est sucré et fondant."],
    tags: ["végétarien", "street food"],
    featured: false,
  },
  {
    slug: "kelewele",
    name: "Kelewele",
    countryCode: "GH",
    region: "Accra",
    course: "accompagnements",
    shortDescription: "Dés de plantain épicés au gingembre et au piment, frits.",
    story:
      "Le kelewele est l'en-cas du soir à Accra. Les dés de plantain mûr sont marinés au gingembre, au piment et aux épices avant d'être frits, puis servis avec des arachides grillées.",
    prepMinutes: 15,
    cookMinutes: 15,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [4, null, "bananes plantains mûres"],
      [1, "morceau", "gingembre frais (5 cm)"],
      [1, null, "piment"],
      [0.5, null, "oignon"],
      [2, "gousses", "poivre de Selim", "poivre-de-selim"],
      [50, "cl", "huile de friture"],
      [null, null, "sel"],
    ],
    steps: [
      "Mixer le gingembre, le piment, l'oignon, le poivre de Selim et une pincée de sel avec 2 cuillères d'eau.",
      "Couper les plantains en dés et les enrober de cette pâte. Laisser reposer 15 minutes.",
      "Frire les dés dans l'huile chaude jusqu'à ce qu'ils soient caramélisés, puis égoutter.",
    ],
    tips: ["Servez avec des arachides grillées."],
    tags: ["végétarien", "épicé"],
    featured: false,
  },
  // ---------------------------------------------------------- Douceurs
  {
    slug: "jus-de-bissap",
    name: "Jus de bissap",
    countryCode: "SN",
    region: "Dakar",
    course: "douceurs",
    shortDescription: "La boisson rouge rubis à la fleur d'hibiscus, menthe et fleur d'oranger.",
    story:
      "Le bissap est la boisson de l'hospitalité au Sénégal : on l'offre aux invités, on le sert aux mariages et à la rupture du jeûne pendant le ramadan.\n\nSa couleur rubis et son goût acidulé en font la boisson la plus populaire d'Afrique de l'Ouest.",
    prepMinutes: 15,
    cookMinutes: 10,
    servings: 8,
    difficulty: 1,
    ingredients: [
      [100, "g", "fleurs de bissap", "fleurs-de-bissap"],
      [2, "l", "eau"],
      [200, "g", "sucre"],
      [1, null, "botte de menthe fraîche"],
      [1, "c. à soupe", "eau de fleur d'oranger"],
      [1, "sachet", "sucre vanillé"],
    ],
    steps: [
      "Rincer rapidement les fleurs de bissap à l'eau froide.",
      "Porter l'eau à ébullition, y plonger les fleurs et la menthe, puis laisser infuser 10 minutes hors du feu.",
      "Filtrer, ajouter le sucre, le sucre vanillé et la fleur d'oranger, et bien mélanger.",
      "Laisser refroidir, puis servir très frais.",
    ],
    tips: ["Infusion à froid : laissez les fleurs une nuit dans l'eau froide, le goût est plus fruité.", "Les fleurs infusées peuvent servir une seconde fois."],
    tags: ["boisson", "sans cuisson"],
    featured: true,
  },
  {
    slug: "thiakry",
    name: "Thiakry",
    countryCode: "SN",
    region: "Dakar",
    course: "douceurs",
    shortDescription: "Couscous de mil au lait caillé, vanille et muscade.",
    story:
      "Le thiakry (ou dégué au Burkina Faso) est le dessert frais des fêtes sénégalaises, notamment à la Tabaski. Les graines de mil cuites à la vapeur sont mélangées à un lait caillé sucré et parfumé.",
    prepMinutes: 15,
    cookMinutes: 30,
    servings: 6,
    difficulty: 1,
    ingredients: [
      [250, "g", "couscous de mil", "couscous-de-mil"],
      [1, "l", "lait fermenté (ou yaourt nature)"],
      [200, "g", "lait concentré sucré"],
      [80, "g", "sucre"],
      [1, "sachet", "sucre vanillé"],
      [null, null, "noix de muscade râpée"],
      [null, null, "raisins secs (facultatif)"],
    ],
    steps: [
      "Humidifier le couscous de mil et le cuire à la vapeur 15 minutes. L'égrainer, l'humidifier à nouveau et le recuire 15 minutes.",
      "Laisser refroidir complètement en égrainant à la main.",
      "Fouetter le lait fermenté avec le lait concentré, le sucre, le sucre vanillé et la muscade.",
      "Mélanger avec le mil, ajouter les raisins et servir bien frais.",
    ],
    tips: ["Préparé la veille, il est encore meilleur."],
    tags: ["dessert", "fête"],
    featured: false,
  },
];

export const demoRecipes: Recipe[] = buildRecipes([
  ...seeds,
  ...recipesAfriqueOuest,
  ...recipesAfriqueCentrale,
  ...recipesAfriqueEstAustrale,
  ...recipesDouceurs,
]);
