/** Recettes d'Afrique de l'Est, d'Afrique australe et de Madagascar (données de démonstration). */
import type { RecipeSeed } from "./recipe-seed";

export const recipesAfriqueEstAustrale: RecipeSeed[] = [
  {
    slug: "misir-wat",
    name: "Misir wat",
    countryCode: "ET",
    region: "Addis-Abeba",
    course: "mijotes",
    shortDescription: "Lentilles corail fondantes, mijotées dans une sauce rouge au berbéré.",
    story:
      "Le misir wat est l'un des piliers de la table éthiopienne. Pendant les nombreux jours de jeûne de l'Église orthodoxe éthiopienne, où l'on renonce aux produits animaux, il s'impose comme le plat du quotidien, servi au centre d'une grande injera que l'on partage à la main.\n\nTout commence par des oignons longuement étuvés sans matière grasse, une technique typique de la cuisine éthiopienne, avant l'arrivée du berbéré, ce mélange d'épices rouge et parfumé qui donne au plat sa couleur profonde et sa chaleur.",
    prepMinutes: 15,
    cookMinutes: 50,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [300, "g", "lentilles corail"],
      [3, null, "oignons rouges"],
      [4, "gousses", "ail"],
      [1, "morceau", "gingembre frais (3 cm)"],
      [2, "c. à soupe", "berbéré", "berbere"],
      [2, "c. à soupe", "concentré de tomate"],
      [6, "c. à soupe", "huile végétale (ou niter kibbeh)"],
      [1, "l", "eau chaude"],
      [null, null, "sel"],
    ],
    steps: [
      "Rincer les lentilles corail à l'eau froide jusqu'à ce que l'eau soit claire, puis les égoutter.",
      "Hacher très finement les oignons (ou les mixer). Les faire cuire à sec dans une cocotte à feu moyen pendant 10 minutes en remuant, jusqu'à ce qu'ils perdent leur eau et commencent à colorer.",
      "Ajouter l'huile, l'ail et le gingembre râpés, puis cuire 5 minutes. Incorporer le berbéré et le concentré de tomate et laisser revenir 3 minutes à feu doux, en ajoutant un filet d'eau si le mélange attache.",
      "Verser les lentilles et l'eau chaude. Porter à frémissement, couvrir à moitié et laisser mijoter 25 à 30 minutes en remuant régulièrement, jusqu'à obtenir une texture fondante et nappante.",
      "Saler, rectifier la consistance avec un peu d'eau si besoin et laisser reposer 5 minutes hors du feu avant de servir.",
    ],
    tips: [
      "Servez sur une injera, avec du shiro et des légumes sautés pour composer un beyainetu, l'assiette végétarienne éthiopienne.",
      "Ajustez la quantité de berbéré selon votre goût : une cuillère pour une version douce, trois pour une version bien relevée.",
    ],
    tags: ["végétarien", "lentilles", "épicé"],
    featured: true,
  },
  {
    slug: "shiro",
    name: "Shiro",
    countryCode: "ET",
    region: "Hauts plateaux",
    course: "mijotes",
    shortDescription: "Une purée veloutée de farine de pois chiches, relevée au berbéré.",
    story:
      "Le shiro est présent dans presque tous les foyers d'Éthiopie et d'Érythrée. On le prépare à partir d'une farine de pois chiches ou de fèves grillées, souvent déjà mélangée à des épices, ce qui en fait un plat rapide et économique.\n\nServi fumant dans un petit plat en terre cuite, le shiro tegabino est une spécialité des restaurants d'Addis-Abeba : il arrive encore bouillonnant à table, accompagné d'injera.",
    prepMinutes: 10,
    cookMinutes: 30,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [120, "g", "farine de pois chiches"],
      [2, null, "oignons rouges"],
      [3, "gousses", "ail"],
      [1, "c. à soupe", "berbéré", "berbere"],
      [1, null, "tomate mûre"],
      [5, "c. à soupe", "huile végétale"],
      [75, "cl", "eau"],
      [1, null, "piment vert"],
      [null, null, "sel"],
    ],
    steps: [
      "Hacher très finement les oignons et les faire suer à sec dans une casserole à feu moyen pendant 8 minutes, en remuant.",
      "Ajouter l'huile, l'ail écrasé et la tomate râpée, puis laisser cuire 5 minutes. Incorporer le berbéré et remuer 2 minutes.",
      "Verser l'eau et porter à frémissement. Ajouter la farine de pois chiches en pluie, en fouettant sans arrêt pour éviter les grumeaux.",
      "Baisser le feu et laisser cuire 15 minutes en remuant souvent : la sauce doit devenir lisse, épaisse et brillante. Rallonger d'un peu d'eau si elle devient trop compacte.",
      "Saler, ajouter le piment vert fendu en deux et servir aussitôt, bien chaud.",
    ],
    tips: [
      "Pour un shiro plus parfumé, torréfiez légèrement la farine de pois chiches à sec dans une poêle avant de l'utiliser.",
      "Une cuillère de beurre clarifié épicé (niter kibbeh) en fin de cuisson lui donne une belle rondeur.",
    ],
    tags: ["végétarien", "pois chiches", "rapide"],
    featured: false,
  },
  {
    slug: "injera",
    name: "Injera au teff",
    countryCode: "ET",
    region: "Hauts plateaux",
    course: "accompagnements",
    shortDescription: "La grande galette alvéolée et légèrement acidulée qui sert d'assiette et de couverts.",
    story:
      "L'injera est au cœur du repas éthiopien et érythréen. Préparée à partir de teff, une toute petite céréale cultivée depuis des millénaires sur les hauts plateaux de la Corne de l'Afrique, elle sert à la fois de plateau, de pain et de couverts : on en déchire un morceau pour saisir les sauces.\n\nSa pâte fermente plusieurs jours, ce qui lui donne son goût acidulé et sa surface criblée de petits trous. On la cuit traditionnellement sur un mitad, une large plaque de terre cuite.",
    prepMinutes: 20,
    cookMinutes: 30,
    servings: 6,
    difficulty: 3,
    ingredients: [
      [500, "g", "farine de teff", "farine-de-teff"],
      [75, "cl", "eau tiède non chlorée"],
      [25, "cl", "eau chaude (pour l'absit)"],
      [1, "pincée", "levure boulangère sèche (facultatif)"],
      [1, "pincée", "sel"],
    ],
    steps: [
      "Mélanger la farine de teff et l'eau tiède dans un grand saladier en verre pour obtenir une pâte lisse, ajouter la levure si vous en utilisez. Couvrir d'un torchon et laisser fermenter 2 à 3 jours à température ambiante.",
      "La pâte doit se couvrir de bulles et d'une fine couche de liquide sur le dessus, avec une odeur légèrement acide. Retirer ce liquide jaunâtre, puis bien remuer.",
      "Prélever environ 10 cl de pâte et la cuire dans une petite casserole avec l'eau chaude en fouettant 2 à 3 minutes jusqu'à épaississement (c'est l'absit). Laisser tiédir puis l'incorporer au reste de la pâte avec le sel. Laisser reposer 1 heure : la pâte doit avoir la consistance d'une pâte à crêpes un peu fluide.",
      "Chauffer une grande poêle antiadhésive à feu moyen, sans matière grasse. Verser une louche de pâte en spirale, de l'extérieur vers le centre, et incliner légèrement la poêle.",
      "Dès que des trous apparaissent sur toute la surface, couvrir et cuire encore 1 minute : l'injera se cuit d'un seul côté et ne se retourne pas. Elle est prête quand les bords se décollent.",
      "Faire glisser l'injera sur un torchon propre et la laisser refroidir à plat avant d'empiler les suivantes.",
    ],
    tips: [
      "Si vous débutez, remplacez un tiers du teff par de la farine de blé ou d'orge : la pâte sera plus facile à maîtriser.",
      "Gardez 10 cl de pâte fermentée pour lancer la fournée suivante, comme un levain.",
    ],
    tags: ["teff", "fermentation", "galette"],
    featured: false,
  },
  {
    slug: "pilau",
    name: "Pilau de Zanzibar",
    countryCode: "TZ",
    region: "Zanzibar",
    course: "riz-cereales",
    shortDescription: "Un riz parfumé à la cardamome, au clou de girofle et à la cannelle, cuit avec du bœuf.",
    story:
      "Sur l'île de Zanzibar, longtemps surnommée l'île aux épices, le pilau raconte des siècles d'échanges dans l'océan Indien entre la côte swahilie, l'Arabie et l'Inde. Clou de girofle, cannelle, cardamome et cumin s'y retrouvent dans un riz doré et fumant.\n\nC'est le plat des fêtes, des mariages et des repas de l'Aïd sur toute la côte swahilie, de Mombasa à Dar es Salaam. On le sert volontiers avec un kachumbari, une salade fraîche de tomates et d'oignons.",
    prepMinutes: 25,
    cookMinutes: 75,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [500, "g", "riz basmati"],
      [600, "g", "bœuf à braiser en cubes"],
      [3, null, "oignons"],
      [5, "gousses", "ail"],
      [1, "morceau", "gingembre frais (4 cm)"],
      [2, null, "pommes de terre"],
      [6, null, "gousses de cardamome"],
      [6, null, "clous de girofle"],
      [1, null, "bâton de cannelle"],
      [2, "c. à café", "graines de cumin"],
      [8, "c. à soupe", "huile végétale"],
      [null, null, "poivre noir en grains et sel"],
    ],
    steps: [
      "Cuire le bœuf dans 1,2 l d'eau salée avec la moitié de l'ail et du gingembre pendant 45 minutes. Réserver la viande et le bouillon séparément.",
      "Rincer le riz jusqu'à ce que l'eau soit claire, puis le laisser tremper 20 minutes et l'égoutter. Concasser grossièrement la cardamome, le clou de girofle, le cumin et une demi-cuillère de poivre au mortier.",
      "Dans une grande cocotte, faire dorer longuement les oignons émincés dans l'huile, 15 minutes environ, jusqu'à ce qu'ils soient bien bruns : c'est ce qui donne sa couleur au pilau.",
      "Ajouter les épices concassées, la cannelle, le reste de l'ail et du gingembre, et faire revenir 2 minutes. Ajouter le bœuf et les pommes de terre en gros cubes, puis remuer 3 minutes.",
      "Verser le riz, bien l'enrober, puis mouiller avec 75 cl de bouillon chaud. Saler, porter à ébullition et laisser cuire à découvert jusqu'à ce que le liquide affleure le riz.",
      "Couvrir hermétiquement, baisser au minimum et laisser cuire 15 minutes sans soulever le couvercle. Laisser reposer 10 minutes hors du feu, puis égrener délicatement à la fourchette.",
    ],
    tips: [
      "Servez avec un kachumbari : tomates, oignon rouge et piment en fines tranches, jus de citron vert et coriandre.",
      "Les oignons doivent être bien caramélisés sans brûler, sinon le riz sera amer.",
    ],
    tags: ["épices", "riz", "fête"],
    featured: true,
  },
  {
    slug: "ugali-sukuma-wiki",
    name: "Ugali et sukuma wiki",
    countryCode: "KE",
    region: "Nairobi",
    course: "accompagnements",
    shortDescription: "La pâte ferme de maïs blanc et ses feuilles de chou vert sautées à la tomate.",
    story:
      "L'ugali est l'accompagnement de base au Kenya et dans une grande partie de l'Afrique de l'Est : une pâte ferme de farine de maïs blanc, que l'on roule en boulette dans la main pour attraper sauces et légumes.\n\nSukuma wiki signifie en swahili « pousser la semaine » : ce plat de chou vert (collard) sauté, bon marché et vite préparé, permettait de tenir jusqu'à la fin de la semaine. Le duo se retrouve aussi bien à la maison que dans les petites cantines de Nairobi.",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [400, "g", "farine de maïs blanc fine"],
      [1, "l", "eau"],
      [1, "botte", "chou cavalier (collard) ou chou kale"],
      [1, null, "oignon"],
      [2, null, "tomates"],
      [2, "gousses", "ail"],
      [3, "c. à soupe", "huile végétale"],
      [1, null, "cube de bouillon (facultatif)"],
      [null, null, "sel et poivre de Penja", "poivre-de-penja"],
    ],
    steps: [
      "Pour le sukuma wiki, retirer les grosses côtes du chou, empiler les feuilles, les rouler et les couper en très fines lanières.",
      "Faire revenir l'oignon émincé dans l'huile 5 minutes, ajouter l'ail puis les tomates coupées en dés et cuire 5 minutes jusqu'à ce qu'elles fondent. Ajouter le chou, le bouillon émietté, saler et poivrer. Cuire 5 à 7 minutes à feu vif en remuant : les feuilles doivent rester vertes et légèrement croquantes.",
      "Pour l'ugali, porter l'eau légèrement salée à ébullition dans une casserole à fond épais. Verser un tiers de la farine en pluie en remuant avec une cuillère en bois pour obtenir une bouillie.",
      "Ajouter le reste de la farine progressivement en écrasant la pâte contre les parois pour éliminer les grumeaux. La pâte devient très ferme et se détache des bords.",
      "Couvrir et laisser cuire 3 minutes à feu doux, retourner la pâte, puis cuire encore 3 minutes. Façonner en dôme avec une cuillère mouillée et démouler sur un plat.",
    ],
    tips: [
      "Accompagnez d'un nyama choma (viande grillée) ou d'un ragoût de haricots pour un repas complet.",
      "Pour manger l'ugali à la kényane, prenez-en une petite boule, creusez-la avec le pouce et servez-vous-en comme d'une cuillère.",
    ],
    tags: ["maïs", "légumes verts", "quotidien"],
    featured: false,
  },
  {
    slug: "luwombo",
    name: "Luwombo de poulet",
    countryCode: "UG",
    region: "Buganda",
    course: "mijotes",
    shortDescription: "Poulet et sauce à l'arachide cuits à la vapeur dans des feuilles de bananier.",
    story:
      "Le luwombo est un plat de cérémonie du royaume du Buganda, au centre de l'Ouganda. On raconte qu'il aurait été créé à la fin du XIXe siècle par le cuisinier du kabaka (le roi), et il reste aujourd'hui le plat d'honneur des mariages et des fêtes de famille.\n\nChaque portion est enveloppée dans des feuilles de bananier assouplies au-dessus du feu, puis cuite longuement à la vapeur. La sauce à l'arachide s'imprègne alors du parfum végétal des feuilles.",
    prepMinutes: 45,
    cookMinutes: 90,
    servings: 4,
    difficulty: 3,
    ingredients: [
      [1.2, "kg", "poulet fermier coupé en morceaux"],
      [200, "g", "pâte d'arachide", "pate-d-arachide"],
      [2, null, "oignons"],
      [3, null, "tomates"],
      [3, "gousses", "ail"],
      [2, "c. à soupe", "huile végétale"],
      [40, "cl", "eau chaude"],
      [4, null, "grandes feuilles de bananier"],
      [null, null, "sel et poivre de Penja", "poivre-de-penja"],
    ],
    steps: [
      "Saler et poivrer le poulet, puis le faire dorer dans l'huile 10 minutes. Réserver. Dans la même cocotte, faire fondre les oignons émincés, l'ail et les tomates en dés pendant 8 minutes.",
      "Délayer la pâte d'arachide dans l'eau chaude jusqu'à obtenir une sauce lisse et nappante, l'ajouter aux tomates et cuire 5 minutes à feu doux en remuant. Saler.",
      "Passer rapidement les feuilles de bananier au-dessus d'une flamme ou les plonger quelques secondes dans l'eau bouillante pour les assouplir. Retirer la nervure centrale et les couper en grands carrés.",
      "Superposer deux carrés en croix, déposer au centre un quart du poulet et de la sauce, puis rabattre les bords pour former une aumônière. Fermer avec une lanière de feuille ou de la ficelle de cuisine.",
      "Déposer les paquets dans un grand faitout sur une grille ou un lit de tiges de bananier, avec 3 cm d'eau au fond. Couvrir et cuire à la vapeur 1 heure 15 en surveillant le niveau d'eau.",
      "Servir chaque convive avec son paquet, que l'on ouvre à table.",
    ],
    tips: [
      "Accompagnez de matoke (bananes plantain vertes cuites à la vapeur et écrasées) ou de riz.",
      "Faute de feuilles de bananier, doublez du papier sulfurisé avec du papier aluminium : le goût sera moins typique, mais la cuisson identique.",
    ],
    tags: ["arachide", "vapeur", "fête"],
    featured: false,
  },
  {
    slug: "romazava",
    name: "Romazava",
    countryCode: "MG",
    region: "Hautes Terres, Antananarivo",
    course: "mijotes",
    shortDescription: "Le bouillon national malgache de viande et de brèdes, avec les fameuses brèdes mafane.",
    story:
      "Souvent présenté comme le plat national de Madagascar, le romazava est un bouillon de viande de zébu mijoté avec plusieurs sortes de brèdes, ces feuilles vertes que l'on trouve sur tous les marchés de l'île. Son nom évoquerait un « bouillon clair ».\n\nSa signature, ce sont les brèdes mafane (cresson de Pará) : leurs petites fleurs jaunes provoquent un léger picotement sur la langue. Le romazava se sert en grande quantité, versé sur un bol de riz blanc, base de tous les repas malgaches.",
    prepMinutes: 25,
    cookMinutes: 75,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [800, "g", "bœuf (ou zébu) à bouillir, en cubes"],
      [2, null, "oignons"],
      [3, null, "tomates"],
      [4, "gousses", "ail"],
      [1, "morceau", "gingembre frais (4 cm)"],
      [1, "botte", "brèdes mafane (ou cresson)"],
      [1, "botte", "brèdes chinoises (pak choï)"],
      [1, "botte", "brèdes morelle ou épinards"],
      [2, "c. à soupe", "huile végétale"],
      [null, null, "sel et poivre de Penja", "poivre-de-penja"],
    ],
    steps: [
      "Faire revenir la viande dans l'huile dans un grand faitout 10 minutes, jusqu'à ce qu'elle soit bien colorée.",
      "Ajouter les oignons émincés, puis l'ail et le gingembre pilés ensemble. Cuire 5 minutes avant d'ajouter les tomates coupées en morceaux.",
      "Couvrir d'eau à hauteur (environ 1,5 l), saler et laisser mijoter à couvert 45 minutes, jusqu'à ce que la viande soit tendre.",
      "Laver les brèdes à grande eau, les équeuter et les couper grossièrement. Ajouter d'abord les brèdes chinoises et la morelle, cuire 8 minutes.",
      "Ajouter les brèdes mafane en dernier et cuire encore 5 minutes : elles doivent rester parfumées. Rectifier l'assaisonnement et servir très chaud avec du riz blanc.",
    ],
    tips: [
      "Le cresson de fontaine ou un mélange cresson et épinards remplace correctement les brèdes mafane, sans leur effet picotant.",
      "À Madagascar, on accompagne souvent le romazava d'un sakay, un condiment pimenté, et d'un rougail de tomates.",
    ],
    tags: ["bouillon", "brèdes", "zébu"],
    featured: false,
  },
  {
    slug: "ravitoto",
    name: "Ravitoto sy henakisoa",
    countryCode: "MG",
    region: "Hautes Terres",
    course: "mijotes",
    shortDescription: "Feuilles de manioc pilées mijotées avec du porc, à l'ail et au gingembre.",
    story:
      "Ravitoto signifie littéralement « feuilles pilées » en malgache : ce sont des feuilles de manioc écrasées au pilon, puis cuites longuement avec du porc (henakisoa). C'est l'un des plats les plus aimés de Madagascar, que l'on prépare pour le repas dominical ou lorsque la famille est réunie.\n\nLe gras du porc fond dans les feuilles et leur donne une texture riche et soyeuse, relevée par l'ail et le gingembre. Certaines familles y ajoutent du lait de coco, surtout sur la côte est.",
    prepMinutes: 30,
    cookMinutes: 90,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [300, "g", "feuilles de manioc pilées séchées", "feuilles-de-manioc"],
      [1, "kg", "poitrine ou échine de porc en cubes"],
      [2, null, "oignons"],
      [6, "gousses", "ail"],
      [1, "morceau", "gingembre frais (4 cm)"],
      [2, null, "tomates"],
      [20, "cl", "lait de coco (facultatif)"],
      [null, null, "sel et poivre de Penja", "poivre-de-penja"],
    ],
    steps: [
      "Réhydrater les feuilles de manioc 30 minutes dans l'eau tiède, puis les rincer et les égoutter. Les cuire 20 minutes dans une grande casserole d'eau bouillante et jeter l'eau de cuisson.",
      "Mettre le porc dans une cocotte avec un fond d'eau et un peu de sel. Cuire à couvert 20 minutes, puis retirer le couvercle et laisser l'eau s'évaporer jusqu'à ce que la viande dore dans son propre gras.",
      "Ajouter les oignons émincés, puis l'ail et le gingembre pilés. Faire revenir 5 minutes, ajouter les tomates en dés et cuire encore 5 minutes.",
      "Incorporer les feuilles de manioc égouttées, bien mélanger et mouiller avec 50 cl d'eau. Laisser mijoter à couvert 40 minutes à feu doux en remuant de temps en temps.",
      "Ajouter le lait de coco si vous le souhaitez, cuire encore 10 minutes et rectifier l'assaisonnement. Le plat doit être fondant et peu liquide. Servir avec du riz blanc.",
    ],
    tips: [
      "Les feuilles de manioc doivent toujours être bien cuites : ne raccourcissez pas le temps de cuisson.",
      "Comme beaucoup de plats mijotés, le ravitoto est encore meilleur réchauffé le lendemain.",
    ],
    tags: ["porc", "feuilles de manioc", "dimanche"],
    featured: false,
  },
  {
    slug: "bobotie",
    name: "Bobotie",
    countryCode: "ZA",
    region: "Le Cap",
    course: "mijotes",
    shortDescription: "Un hachis de bœuf doucement épicé au curry, fruité, et gratiné sous une crème à l'œuf.",
    story:
      "Le bobotie est souvent présenté comme le plat national sud-africain. Il est étroitement associé à la cuisine du Cap, et en particulier à la communauté dite Cape Malay, dont les ancêtres venaient d'Asie du Sud-Est et d'Inde. Le mariage des épices, des fruits secs et de la viande hachée témoigne de ce long métissage culinaire.\n\nSous sa couche dorée d'œufs battus au lait, le hachis parfumé au curry, légèrement sucré par la confiture d'abricot et les raisins secs, se sert avec un riz jaune au curcuma et un chutney de fruits.",
    prepMinutes: 25,
    cookMinutes: 60,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [800, "g", "bœuf haché"],
      [2, null, "oignons"],
      [2, "gousses", "ail"],
      [30, "g", "pain de mie rassis (1 tranche)"],
      [35, "cl", "lait"],
      [2, "c. à soupe", "curry en poudre doux"],
      [1, "c. à café", "curcuma"],
      [2, "c. à soupe", "confiture d'abricot ou chutney"],
      [50, "g", "raisins secs"],
      [1, "c. à soupe", "jus de citron"],
      [3, null, "œufs"],
      [4, null, "feuilles de laurier"],
    ],
    steps: [
      "Préchauffer le four à 180 °C. Faire tremper le pain dans 10 cl de lait, puis l'essorer en réservant le lait.",
      "Dans une grande poêle, faire fondre les oignons émincés dans un filet d'huile 8 minutes. Ajouter l'ail, le curry et le curcuma, puis remuer 1 minute.",
      "Ajouter la viande hachée et la faire cuire 8 minutes en l'émiettant. Hors du feu, incorporer le pain essoré, la confiture, les raisins secs, le jus de citron et 1 œuf battu. Saler et poivrer.",
      "Tasser le mélange dans un plat à gratin beurré et enfoncer les feuilles de laurier à la surface.",
      "Battre les 2 œufs restants avec le reste du lait et une pincée de sel, puis verser sur la viande.",
      "Enfourner pour 35 à 40 minutes, jusqu'à ce que la crème soit prise et bien dorée. Laisser reposer 5 minutes avant de servir.",
    ],
    tips: [
      "Servez avec un riz jaune (cuit avec du curcuma, un bâton de cannelle et quelques raisins secs) et un chutney de fruits.",
      "Préparez le hachis la veille : les épices auront le temps de se marier.",
    ],
    tags: ["curry", "gratin", "Cape Malay"],
    featured: true,
  },
  {
    slug: "chakalaka",
    name: "Chakalaka",
    countryCode: "ZA",
    region: "Gauteng, Johannesburg",
    course: "accompagnements",
    shortDescription: "Un condiment pimenté de poivrons, carottes et haricots, compagnon du braai.",
    story:
      "La chakalaka serait née dans les townships de Johannesburg, où les mineurs auraient cuisiné sur le feu des légumes en conserve, des haricots et du piment pour relever la pâte de maïs. Elle est devenue un incontournable de la table sud-africaine.\n\nOn la retrouve à chaque braai, le barbecue sud-africain, à côté des saucisses boerewors et du pap, la bouillie de maïs. Chaque famille a sa recette, plus ou moins piquante.",
    prepMinutes: 15,
    cookMinutes: 30,
    servings: 6,
    difficulty: 1,
    ingredients: [
      [1, null, "oignon"],
      [1, null, "poivron rouge"],
      [1, null, "poivron vert"],
      [3, null, "carottes"],
      [3, "gousses", "ail"],
      [1, "morceau", "gingembre frais (2 cm)"],
      [2, null, "piments frais"],
      [1, "c. à soupe", "curry en poudre"],
      [400, "g", "tomates concassées en conserve"],
      [400, "g", "haricots blancs à la sauce tomate (baked beans)"],
      [3, "c. à soupe", "huile végétale"],
      [null, null, "sel"],
    ],
    steps: [
      "Émincer l'oignon, couper les poivrons en petits dés, râper grossièrement les carottes et hacher finement l'ail, le gingembre et les piments.",
      "Faire revenir l'oignon dans l'huile 5 minutes, puis ajouter l'ail, le gingembre, les piments et le curry. Remuer 1 minute jusqu'à ce que les épices embaument.",
      "Ajouter les poivrons et cuire 5 minutes, puis les carottes râpées et cuire encore 3 minutes.",
      "Verser les tomates concassées, saler et laisser mijoter 10 minutes à feu doux.",
      "Incorporer les haricots avec leur sauce et laisser cuire encore 5 minutes. Servir chaud ou à température ambiante.",
    ],
    tips: [
      "La chakalaka se garde plusieurs jours au réfrigérateur et se sert aussi froide, comme une relish.",
      "Pour une version plus douce, retirez les graines des piments ou n'en mettez qu'un seul.",
    ],
    tags: ["braai", "légumes", "épicé"],
    featured: false,
  },
];
