/** Recettes d'Afrique de l'Ouest (données de démonstration). */
import type { RecipeSeed } from "./recipe-seed";

export const recipesAfriqueOuest: RecipeSeed[] = [
  // ---------------------------------------------------------- Riz jollof
  {
    slug: "riz-jollof",
    name: "Riz jollof",
    countryCode: "NG",
    region: "Lagos",
    course: "riz-cereales",
    shortDescription: "Riz cuit dans une sauce tomate pimentée, fumé au fond de la marmite.",
    story:
      "Le riz jollof tiendrait son nom de l'ancien royaume wolof (Djolof), au Sénégal, où serait né l'ancêtre du plat, le thiéboudienne. Il a voyagé le long de la côte et s'est imposé au Nigeria et au Ghana, qui se disputent aujourd'hui, avec beaucoup d'humour, le titre du « meilleur jollof ».\n\nAu Nigeria, c'est le plat incontournable des « parties » : mariages, anniversaires et fêtes de quartier. Les connaisseurs réclament le riz légèrement fumé qui accroche au fond de la marmite, le fameux « party jollof ».",
    prepMinutes: 25,
    cookMinutes: 60,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [500, "g", "riz long grain étuvé"],
      [4, null, "tomates bien mûres"],
      [2, null, "poivrons rouges"],
      [2, null, "oignons"],
      [1, null, "piment scotch bonnet"],
      [70, "g", "concentré de tomate"],
      [10, "cl", "huile végétale"],
      [75, "cl", "bouillon de volaille"],
      [2, "c. à café", "curry en poudre"],
      [1, "c. à café", "thym séché"],
      [2, null, "feuilles de laurier"],
      [null, null, "mélange yaji (suya) pour relever", "yaji-suya"],
    ],
    steps: [
      "Mixer les tomates, les poivrons, un oignon et le piment en une purée lisse. La faire réduire 15 minutes dans une casserole jusqu'à ce qu'elle épaississe.",
      "Dans une grande marmite, faire chauffer l'huile et y dorer le second oignon émincé. Ajouter le concentré de tomate et le faire frire 5 minutes en remuant, jusqu'à ce qu'il fonce légèrement.",
      "Verser la purée réduite, le curry, le thym, le laurier et une pincée de yaji. Laisser frémir 10 minutes : l'huile doit remonter à la surface.",
      "Rincer le riz jusqu'à ce que l'eau soit claire, puis l'ajouter à la sauce avec le bouillon. Bien mélanger, saler et porter à ébullition.",
      "Couvrir d'une feuille d'aluminium puis du couvercle et cuire 30 minutes à feu très doux, sans remuer, pour que le riz cuise à la vapeur.",
      "En fin de cuisson, monter le feu 3 à 4 minutes pour laisser le fond accrocher légèrement, puis égrainer à la fourchette avant de servir.",
    ],
    tips: [
      "Servez avec du plantain frit (dodo) et du poulet grillé, comme dans les fêtes de Lagos.",
      "Ne remuez pas le riz pendant la cuisson : c'est la vapeur qui le cuit.",
    ],
    tags: ["fête", "tomate", "riz"],
    featured: true,
  },
  // ---------------------------------------------------------- Soupe egusi
  {
    slug: "soupe-egusi",
    name: "Soupe egusi",
    countryCode: "NG",
    region: "Pays yoruba et igbo",
    course: "mijotes",
    shortDescription: "Sauce épaisse aux graines de melon moulues, légumes-feuilles et poisson fumé.",
    story:
      "L'egusi désigne les graines d'une variété de melon cultivée pour ses pépins, que l'on sèche puis que l'on moud. Au Nigeria, la soupe egusi se prépare aussi bien chez les Yorubas que chez les Igbos, chacun avec sa manière de cuire les graines : en petits grumeaux ou en sauce lisse.\n\nOn la déguste avec une boule d'igname pilée, d'eba ou de fufu, que l'on façonne du bout des doigts pour attraper la sauce.",
    prepMinutes: 25,
    cookMinutes: 50,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [250, "g", "graines d'egusi moulues", "graines-d-egusi"],
      [600, "g", "bœuf en morceaux"],
      [150, "g", "poisson fumé émietté", "poisson-fume"],
      [40, "g", "crevettes séchées moulues", "crevettes-sechees"],
      [12, "cl", "huile de palme rouge", "huile-de-palme-rouge"],
      [2, null, "oignons"],
      [2, null, "piments rouges"],
      [300, "g", "épinards frais (ou feuilles amères)"],
      [1, null, "cube de bouillon"],
      [null, null, "sel"],
    ],
    steps: [
      "Cuire le bœuf avec un oignon émincé, le cube de bouillon et 50 cl d'eau pendant 30 minutes. Réserver la viande et le bouillon.",
      "Mélanger les graines d'egusi moulues avec le second oignon mixé et un peu d'eau pour obtenir une pâte épaisse.",
      "Faire chauffer l'huile de palme dans une cocotte 2 minutes sans la laisser fumer, puis déposer la pâte d'egusi par cuillerées. Laisser frire 10 minutes en retournant délicatement pour former des grumeaux dorés.",
      "Verser le bouillon de cuisson, ajouter la viande, le poisson fumé, les crevettes séchées et les piments mixés. Couvrir et laisser mijoter 15 minutes à feu doux.",
      "Ajouter les épinards hachés, mélanger et cuire encore 5 minutes. Rectifier l'assaisonnement.",
    ],
    tips: [
      "Pour une sauce plus lisse, délayez l'egusi dans le bouillon au lieu de le frire.",
      "Servez avec du fufu ou de l'igname pilée.",
    ],
    tags: ["egusi", "huile de palme", "poisson fumé"],
    featured: false,
  },
  // ---------------------------------------------------------- Sauce graine
  {
    slug: "sauce-graine",
    name: "Sauce graine au poulet",
    countryCode: "CI",
    region: "Sud de la Côte d'Ivoire",
    course: "mijotes",
    shortDescription: "Poulet mijoté dans une sauce onctueuse à la pulpe de noix de palme.",
    story:
      "La « graine », c'est la noix de palme, que l'on fait bouillir puis que l'on pile pour en extraire une pulpe orangée et parfumée. La sauce graine est l'un des grands classiques de la cuisine ivoirienne, surtout dans le Sud forestier où poussent les palmiers à huile.\n\nOn la sert le dimanche avec du riz blanc, du foutou banane ou du placali, et chaque famille garde jalousement sa manière de la parfumer.",
    prepMinutes: 20,
    cookMinutes: 70,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [800, "g", "pulpe de noix de palme", "pulpe-de-noix-de-palme"],
      [1.2, "kg", "poulet fermier découpé"],
      [150, "g", "poisson fumé", "poisson-fume"],
      [2, null, "oignons"],
      [3, null, "tomates"],
      [3, "gousses", "ail"],
      [2, null, "piments frais"],
      [6, null, "gombos frais"],
      [1, "l", "eau"],
      [null, null, "sel et poivre"],
    ],
    steps: [
      "Assaisonner le poulet avec l'ail écrasé, un oignon émincé, du sel et du poivre. Le faire revenir 10 minutes dans une cocotte avec un fond d'eau, à couvert.",
      "Délayer la pulpe de noix de palme dans 1 litre d'eau chaude, puis la verser sur le poulet.",
      "Ajouter les tomates et le second oignon entiers, les piments et les gombos. Laisser cuire 20 minutes, puis retirer tomates, oignon et gombos, les écraser et les remettre dans la sauce.",
      "Ajouter le poisson fumé émietté et laisser mijoter 35 minutes à feu doux, en remuant de temps en temps, jusqu'à ce que l'huile rouge remonte en surface.",
      "Goûter, rectifier le sel et servir bien chaud.",
    ],
    tips: [
      "La sauce est prête quand une fine couche d'huile rouge brille à la surface.",
      "Accompagnez de riz blanc ou de foutou banane.",
    ],
    tags: ["noix de palme", "poulet", "dimanche"],
    featured: false,
  },
  // ---------------------------------------------------------- Garba
  {
    slug: "garba",
    name: "Garba",
    countryCode: "CI",
    region: "Abidjan",
    course: "accompagnements",
    shortDescription: "Attiéké et thon frit croustillant, piment et oignon : le plat de rue d'Abidjan.",
    story:
      "Le garba est né dans les petits kiosques d'Abidjan, les « garbadromes », tenus à l'origine par des vendeurs venus du Niger, selon la tradition populaire. Pour quelques pièces, on y sert une montagne d'attiéké, un morceau de thon frit et une poignée de piment.\n\nÉtudiants, travailleurs et noctambules en ont fait un véritable symbole de la ville, célébré jusque dans les chansons de coupé-décalé.",
    prepMinutes: 20,
    cookMinutes: 20,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [500, "g", "attiéké sec", "attieke-sec"],
      [800, "g", "thon frais en tranches épaisses"],
      [2, null, "oignons rouges"],
      [2, null, "tomates"],
      [3, null, "piments verts frais"],
      [1, null, "cube de bouillon"],
      [50, "cl", "huile de friture"],
      [null, null, "sel et poivre"],
    ],
    steps: [
      "Arroser l'attiéké sec de 30 cl d'eau tiède salée, bien l'égrainer avec les doigts et laisser gonfler 10 minutes à couvert.",
      "Cuire l'attiéké 10 minutes à la vapeur dans un couscoussier, puis l'égrainer de nouveau à la fourchette.",
      "Couper le thon en gros morceaux, l'assaisonner avec le cube de bouillon émietté, du sel et du poivre.",
      "Faire chauffer l'huile et frire le thon 6 à 8 minutes, jusqu'à ce qu'il soit bien doré et croustillant à l'extérieur. Égoutter sur du papier absorbant.",
      "Émincer finement les oignons, couper les tomates en dés et hacher les piments. Servir l'attiéké en dôme, le thon par-dessus, garni d'oignon, de tomate et de piment, avec un filet d'huile de friture.",
    ],
    tips: [
      "À Abidjan, on arrose souvent le garba d'un peu d'huile de friture du thon : c'est ce qui fait son goût.",
      "Mangez-le à la main, comme dans les garbadromes.",
    ],
    tags: ["plat de rue", "attiéké", "poisson"],
    featured: true,
  },
  // ---------------------------------------------------------- Kedjenou
  {
    slug: "kedjenou",
    name: "Kedjenou de poulet",
    countryCode: "CI",
    region: "Pays baoulé",
    course: "mijotes",
    shortDescription: "Poulet cuit à l'étouffée dans son jus, avec légumes et piment, sans ajout d'eau.",
    story:
      "Le kedjenou vient du pays baoulé, au centre de la Côte d'Ivoire. Son nom évoquerait le geste de secouer le canari, la marmite en terre cuite fermée par des feuilles de bananier, que l'on remue régulièrement au lieu d'ouvrir.\n\nLa viande cuit ainsi à l'étouffée, dans sa propre eau et celle des légumes, ce qui lui donne une chair tendre et une sauce courte, très parfumée.",
    prepMinutes: 20,
    cookMinutes: 60,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [1.5, "kg", "poulet fermier découpé"],
      [3, null, "tomates"],
      [2, null, "oignons"],
      [1, null, "aubergine"],
      [1, "morceau", "gingembre frais (4 cm)"],
      [3, "gousses", "ail"],
      [2, null, "piments frais"],
      [2, null, "feuilles de laurier"],
      [1, null, "cube de bouillon"],
      [null, null, "poivre de Penja", "poivre-de-penja"],
      [null, null, "sel"],
    ],
    steps: [
      "Couper les tomates, les oignons et l'aubergine en morceaux. Écraser l'ail et le gingembre en pâte.",
      "Mettre dans une cocotte en fonte (ou un canari) le poulet, les légumes, l'ail, le gingembre, les piments entiers, le laurier et le cube émietté. Saler et poivrer. Ne pas ajouter d'eau.",
      "Fermer hermétiquement : placer une feuille d'aluminium sous le couvercle pour qu'aucune vapeur ne s'échappe.",
      "Cuire 55 à 60 minutes à feu doux. Toutes les 10 minutes, secouer vigoureusement la cocotte en la tenant par les anses, sans l'ouvrir.",
      "Vérifier la cuisson : le poulet doit être tendre et nappé d'une sauce courte. Retirer les piments si l'on souhaite moins de piquant.",
    ],
    tips: [
      "Résistez à l'envie d'ouvrir la cocotte : toute la vapeur doit rester à l'intérieur.",
      "Servez avec de l'attiéké ou du riz blanc.",
    ],
    tags: ["poulet", "étouffée", "canari"],
    featured: false,
  },
  // ---------------------------------------------------------- Tô et sauce gombo
  {
    slug: "to-sauce-gombo",
    name: "Tô et sauce gombo",
    countryCode: "BF",
    region: "Plateau central",
    course: "accompagnements",
    shortDescription: "Pâte de maïs ferme servie avec une sauce gombo filante au soumbala.",
    story:
      "Le tô est la base des repas au Burkina Faso : une pâte ferme de farine de mil, de sorgho ou de maïs, que l'on découpe à la main et que l'on trempe dans la sauce. Chaque soir, dans les cours familiales, les grandes marmites de tô se préparent au feu de bois.\n\nLa sauce gombo, légèrement filante, en est la compagne la plus courante. Le soumbala, condiment fermenté à base de graines de néré, lui apporte son parfum profond si caractéristique.",
    prepMinutes: 20,
    cookMinutes: 45,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [600, "g", "farine de maïs blanc"],
      [2, "l", "eau"],
      [1, "c. à soupe", "jus de citron (ou d'eau de tamarin)"],
      [60, "g", "gombo séché en poudre", "gombo-seche"],
      [2, "c. à soupe", "soumbala", "soumbala"],
      [400, "g", "viande de mouton ou de bœuf en morceaux"],
      [100, "g", "poisson fumé", "poisson-fume"],
      [1, null, "oignon"],
      [2, null, "piments frais"],
      [5, "cl", "huile d'arachide"],
      [null, null, "sel"],
    ],
    steps: [
      "Sauce : faire revenir la viande dans l'huile avec l'oignon émincé, couvrir de 1 litre d'eau et cuire 30 minutes.",
      "Ajouter le soumbala écrasé, le poisson fumé émietté et les piments. Laisser frémir 5 minutes, puis verser la poudre de gombo en pluie en fouettant pour éviter les grumeaux. Cuire 8 minutes : la sauce doit devenir filante.",
      "Tô : délayer 150 g de farine dans 50 cl d'eau froide. Porter 1,5 litre d'eau à ébullition avec le jus de citron, puis y verser ce mélange en remuant pour obtenir une bouillie.",
      "Retirer un bol de bouillie et le réserver. Incorporer le reste de la farine au bâton ou à la spatule, par petites quantités, en écrasant la pâte contre la paroi pour qu'elle soit bien lisse.",
      "Quand la pâte devient ferme et se détache des bords, rajouter un peu de bouillie réservée si elle est trop épaisse, couvrir et laisser cuire 5 minutes à feu très doux.",
      "Façonner le tô en dômes à l'aide d'une louche mouillée et servir avec la sauce gombo à côté.",
    ],
    tips: [
      "Le jus de citron ou de tamarin donne au tô sa légère acidité et l'empêche de coller.",
      "On mange le tô à la main droite, en formant une petite boulette que l'on plonge dans la sauce.",
    ],
    tags: ["gombo", "soumbala", "quotidien"],
    featured: false,
  },
  // ---------------------------------------------------------- Thiéré mbuum
  {
    slug: "thiere-mbuum",
    name: "Thiéré mbuum",
    countryCode: "SN",
    region: "Saloum et pays sérère",
    course: "riz-cereales",
    shortDescription: "Couscous de mil aux feuilles de moringa, servi avec une sauce de viande et niébé.",
    story:
      "Le thiéré est le couscous de mil du Sénégal, roulé à la main et cuit à la vapeur. Associé au mbuum, les feuilles de moringa (nébédaye en wolof), il devient un plat de fête très apprécié, notamment chez les Sérères et dans le Saloum.\n\nOn le prépare en grande quantité pour la Tamkharit, le Nouvel An musulman, ou pour recevoir. Les feuilles donnent au couscous une couleur verte et une saveur végétale légèrement poivrée.",
    prepMinutes: 30,
    cookMinutes: 75,
    servings: 6,
    difficulty: 2,
    ingredients: [
      [750, "g", "couscous de mil (thiéré)", "couscous-de-mil"],
      [40, "g", "feuilles de moringa séchées", "feuilles-de-moringa"],
      [150, "g", "niébé (haricots cornille)"],
      [800, "g", "viande de mouton en morceaux"],
      [150, "g", "pâte d'arachide", "pate-d-arachide"],
      [2, null, "oignons"],
      [2, "c. à soupe", "concentré de tomate"],
      [1, "c. à café", "poivre de Sélim moulu", "poivre-de-selim"],
      [5, "cl", "huile d'arachide"],
      [30, "g", "beurre"],
      [null, null, "sel"],
    ],
    steps: [
      "Faire tremper le niébé 2 heures (ou la veille), puis le cuire 40 minutes à l'eau salée.",
      "Sauce : faire revenir le mouton dans l'huile avec les oignons émincés, ajouter le concentré de tomate et couvrir de 1,2 litre d'eau. Cuire 45 minutes, puis délayer la pâte d'arachide dans la sauce et laisser mijoter encore 15 minutes. Ajouter le niébé en fin de cuisson.",
      "Humecter le couscous de mil avec 15 cl d'eau salée, l'égrainer et le cuire 20 minutes à la vapeur au-dessus d'une marmite d'eau frémissante.",
      "Réhydrater les feuilles de moringa 5 minutes dans un peu d'eau tiède, les égoutter, puis les mélanger au couscous avec le beurre et le poivre de Sélim.",
      "Remettre le couscous 15 minutes à la vapeur pour qu'il s'imprègne du parfum des feuilles, puis l'égrainer à la main.",
      "Servir le thiéré en large plat, arrosé de sauce, avec la viande et le niébé par-dessus.",
    ],
    tips: [
      "Le couscous doit rester bien égrainé : travaillez-le avec les mains légèrement huilées entre deux cuissons.",
      "À la Tamkharit, on le sert souvent avec une sauce tomate au poulet.",
    ],
    tags: ["mil", "moringa", "fête"],
    featured: false,
  },
  // ---------------------------------------------------------- Caldou
  {
    slug: "caldou",
    name: "Caldou de poisson",
    countryCode: "SN",
    region: "Casamance, Ziguinchor",
    course: "mijotes",
    shortDescription: "Poisson poché dans un bouillon citronné, relevé de piment et de gombo.",
    story:
      "Le caldou est un plat emblématique de la Casamance, au sud du Sénégal. Son nom viendrait du portugais « caldo », bouillon, un héritage des échanges anciens avec les comptoirs portugais de la région.\n\nFrais et acidulé, il met en valeur le poisson du fleuve et de la côte : un bouillon léger au citron, relevé de piment, que l'on verse sur un riz blanc bien cuit.",
    prepMinutes: 20,
    cookMinutes: 35,
    servings: 4,
    difficulty: 1,
    ingredients: [
      [1.2, "kg", "poisson blanc à chair ferme (thiof, capitaine ou dorade) en tranches"],
      [2, null, "oignons"],
      [2, null, "tomates"],
      [3, null, "citrons verts"],
      [8, null, "gombos frais"],
      [1, null, "piment frais"],
      [3, "gousses", "ail"],
      [1, "c. à soupe", "guedj émietté", "guedj"],
      [5, "cl", "huile d'arachide"],
      [null, null, "poivre de Penja", "poivre-de-penja"],
      [null, null, "sel"],
    ],
    steps: [
      "Nettoyer le poisson et le frotter avec le jus d'un citron, l'ail écrasé, du sel et du poivre. Laisser mariner 15 minutes.",
      "Dans une cocotte, faire revenir doucement les oignons émincés dans l'huile, sans les colorer. Ajouter les tomates coupées en dés et cuire 5 minutes.",
      "Verser 1 litre d'eau, ajouter le guedj, le piment entier et les gombos. Porter à frémissement et cuire 10 minutes.",
      "Déposer délicatement les tranches de poisson dans le bouillon et les pocher 12 à 15 minutes à feu doux, sans remuer pour ne pas les briser.",
      "Hors du feu, ajouter le jus des deux citrons restants, goûter et rectifier l'assaisonnement.",
    ],
    tips: [
      "Servez sur du riz blanc, en arrosant généreusement de bouillon.",
      "Ajoutez le citron au dernier moment pour garder toute sa fraîcheur.",
    ],
    tags: ["poisson", "citron", "Casamance"],
    featured: false,
  },
  // ---------------------------------------------------------- Fufu et light soup
  {
    slug: "fufu-light-soup",
    name: "Fufu et light soup",
    countryCode: "GH",
    region: "Pays ashanti, Kumasi",
    course: "accompagnements",
    shortDescription: "Boule de fufu moelleuse plongée dans une soupe légère à la tomate et au piment.",
    story:
      "Au Ghana, le fufu est traditionnellement obtenu en pilant manioc et plantain cuits dans un grand mortier, un travail à deux qui rythme la vie des cours ashanti. La « light soup », comme son nom l'indique, est un bouillon clair de tomate et de piment, sans pâte d'arachide ni noix de palme.\n\nL'association des deux est un grand classique du déjeuner du dimanche. On ne mâche pas le fufu : on en détache un morceau du bout des doigts et on l'avale avec la soupe.",
    prepMinutes: 25,
    cookMinutes: 50,
    servings: 4,
    difficulty: 2,
    ingredients: [
      [500, "g", "farine de foufou", "farine-de-foufou"],
      [1, "kg", "poulet ou chèvre en morceaux"],
      [4, null, "tomates"],
      [2, null, "oignons"],
      [1, "morceau", "gingembre frais (3 cm)"],
      [2, null, "piments scotch bonnet"],
      [2, null, "aubergines africaines (garden eggs)"],
      [100, "g", "poisson fumé", "poisson-fume"],
      [null, null, "sel"],
    ],
    steps: [
      "Assaisonner la viande avec un oignon mixé, le gingembre râpé et du sel. La faire suer 10 minutes à couvert dans une marmite, sans eau.",
      "Ajouter 1,5 litre d'eau, les tomates, le second oignon, les piments et les aubergines entiers. Cuire 15 minutes, puis retirer les légumes.",
      "Mixer les légumes cuits avec un peu de bouillon, puis les passer au tamis au-dessus de la marmite. Ajouter le poisson fumé et laisser mijoter 20 minutes.",
      "Pendant ce temps, porter 75 cl d'eau à ébullition. Hors du feu, verser la farine de foufou en pluie en remuant vigoureusement avec une spatule solide.",
      "Remettre sur feu doux et travailler la pâte 5 à 8 minutes en la rabattant sans cesse, jusqu'à ce qu'elle soit lisse, élastique et brillante. Former des boules avec les mains mouillées.",
      "Déposer une boule de fufu dans chaque bol creux et la recouvrir de light soup bien chaude, avec les morceaux de viande.",
    ],
    tips: [
      "Mouillez vos mains à l'eau froide pour façonner le fufu sans qu'il colle.",
      "Pour une soupe plus relevée, écrasez un piment dans le bol au moment de servir.",
    ],
    tags: ["fufu", "soupe", "dimanche"],
    featured: false,
  },
  // ---------------------------------------------------------- Waakye
  {
    slug: "waakye",
    name: "Waakye",
    countryCode: "GH",
    region: "Nord du Ghana et Accra",
    course: "riz-cereales",
    shortDescription: "Riz et haricots cuits ensemble, teintés de rouge brun par les feuilles de sorgho.",
    story:
      "Le waakye (prononcer « waa-tchi ») viendrait des peuples haoussas du nord du Ghana, avant de conquérir Accra et tout le pays. Son nom signifierait simplement « riz et haricots » en haoussa.\n\nSa couleur brun-rouge caractéristique vient des feuilles de sorgho séchées que l'on fait cuire avec le riz. Le matin, les vendeuses le servent sur une feuille de bananier avec du shito, du gari, des spaghettis, un œuf dur et du poisson frit.",
    prepMinutes: 15,
    cookMinutes: 70,
    servings: 6,
    difficulty: 1,
    ingredients: [
      [400, "g", "riz long grain"],
      [250, "g", "haricots rouges ou niébé secs"],
      [6, null, "feuilles de sorgho séchées", "feuilles-de-sorgho"],
      [0.5, "c. à café", "bicarbonate de soude (facultatif)"],
      [1.5, "l", "eau"],
      [null, null, "sel"],
      [6, null, "œufs durs (pour servir)"],
      [150, "g", "gari (semoule de manioc, pour servir)"],
    ],
    steps: [
      "Faire tremper les haricots 8 heures dans l'eau froide, puis les égoutter.",
      "Rincer les feuilles de sorgho et les déchirer en gros morceaux. Les mettre dans une marmite avec les haricots, le bicarbonate et 1,5 litre d'eau.",
      "Cuire 40 minutes à feu moyen, jusqu'à ce que les haricots soient presque tendres et que l'eau ait pris une couleur rouge sombre.",
      "Rincer le riz jusqu'à ce que l'eau soit claire, l'ajouter à la marmite avec du sel. L'eau doit dépasser le riz d'environ 1 cm ; en rajouter si besoin.",
      "Couvrir et cuire 25 minutes à feu doux, jusqu'à absorption complète du liquide. Retirer les feuilles de sorgho et égrainer à la fourchette.",
      "Servir avec des œufs durs, du gari et, selon les goûts, du shito, du poisson frit et une salade de chou.",
    ],
    tips: [
      "Le bicarbonate accentue la couleur rouge, mais n'en mettez pas trop : une demi-cuillère suffit.",
      "Le waakye se déguste traditionnellement au petit-déjeuner, sur une feuille de bananier.",
    ],
    tags: ["riz", "haricots", "plat de rue"],
    featured: true,
  },
];
